import type { Topic } from '../types'

export const healthTopics: Topic[] = [
  {
    id: 'topic-health-insurance',
    slug: 'health-insurance-basics',
    title: 'Health insurance: what the words mean before you need a doctor',
    category: 'health',
    oneLiner:
      'In the US, the price of the same visit depends entirely on your insurance, and the four numbers that decide everything are premium, deductible, copay and out-of-pocket maximum.',
    whyItMatters:
      'People avoid doctors because they are afraid of the bill — and then a manageable problem becomes a $50,000 emergency. Meanwhile the rules for immigrants changed in 2026 and 2027, eligibility depends on your specific status, and "insurance" sold by phone is one of the most active fraud markets targeting newcomers.',
    keywords: [
      'health insurance', 'aca', 'marketplace', 'healthcare.gov', 'medicaid',
      'medicare', 'deductible', 'copay', 'premium', 'out of pocket',
      'no insurance', 'doctor visit cost', 'emergency medicaid', 'subsidy',
      'open enrollment', 'special enrollment',
    ],
    explain: [
      'Learn the four numbers first, because they are what every plan is actually compared on. Premium: what leaves your account every month whether you use care or not. Deductible: what you pay yourself before the insurer starts paying for most services. Copay: a fixed amount you pay for a specific visit, like $25 for a primary care appointment. Out-of-pocket maximum: the ceiling on what you pay in a year for covered in-network care — after that, the insurer pays 100%. A plan with a low premium usually has a high deductible and vice versa. There is no plan that is cheap on all four.',
      'The second idea is the network. In-network providers have agreed prices with your insurer; out-of-network providers bill whatever they want and you may owe the difference. Before any appointment, ask two questions: "Are you in network for my plan?" and "Is this visit covered as preventive care?" Preventive care — annual check-ups, many vaccines, some screenings — is generally covered without cost sharing in compliant plans, which means routine care can be genuinely free.',
      'For immigrants, eligibility depends on status, and this is the part that changed. Federal law restricts many federal benefits for people who are not "qualified" immigrants, and there is a five-year waiting period for many programs. Emergency Medicaid exists for emergency care regardless of status, community health centers serve everyone on a sliding scale, and Marketplace subsidies were restricted in 2026 with further limits in 2027. Because the rules shifted recently and vary by status and by state, use the official eligibility screener rather than any summary — including this one. Your state\'s exchange or Medicaid office will tell you what you qualify for, for free.',
      'If a stranger calls offering cheap insurance, or an "agent" wants your SSN and a payment to "activate coverage today", stop. Legitimate coverage is bought through an employer, healthcare.gov or your state exchange, or a licensed broker who gives you plan documents and a license number. A plan that cannot tell you the deductible, the network, and the insurer\'s legal name is not a product — it is a scam with paperwork.',
    ],
    facts: [
      {
        id: 'f-aca-eligibility-immigrants',
        claim: 'Marketplace eligibility depends on immigration status and income: most lawfully present immigrants can use the Marketplace, but low-income lawfully present immigrants who are barred from Medicaid by their status lost premium tax credit eligibility starting January 1, 2026, with further restrictions taking effect January 1, 2027.',
        detail:
          'This landscape changed twice in two years. Check your own situation through the official screener or your state exchange rather than relying on any summary.',
        asOf: '2026-04',
        source: { name: 'HealthCare.gov — Immigrants and coverage', url: 'https://www.healthcare.gov/immigrants/lawfully-present-immigrants/' },
        volatility: 'volatile',
        alsoCheck: [
          { name: 'Georgetown Center for Children and Families — Marketplace 2026 changes', url: 'https://ccf.georgetown.edu/2025/10/21/what-to-expect-for-open-enrollment-2026-edition/' },
        ],
      },
      {
        id: 'f-marketplace-oep',
        claim: 'Federal Marketplace open enrollment runs November 1 through January 15 for coverage starting the following calendar year; outside that window you need a qualifying life event to get a special enrollment period, generally within 60 days of the event.',
        detail:
          'Qualifying events include losing other coverage, moving, marriage, divorce, and having a baby. The income-based special enrollment period that low-income people used outside open enrollment was eliminated starting in 2026.',
        asOf: '2026-01',
        source: { name: 'HealthCare.gov — Special enrollment periods', url: 'https://www.healthcare.gov/coverage-outside-open-enrollment/special-enrollment-period/' },
        volatility: 'annual',
      },
      {
        id: 'f-aptc-repayment-uncapped',
        claim: 'Beginning with tax year 2026, the caps on how much you must repay if you received more advance premium tax credit than you were entitled to were removed, so an income estimate that is too low can produce an unexpected tax bill.',
        detail:
          'If your income changes during the year, update it in your Marketplace account immediately. That is the single best defense against a surprise repayment.',
        asOf: '2026-01',
        source: { name: 'HealthCare.gov — Premium tax credit repayments', url: 'https://www.healthcare.gov/help/premium-tax-credit-repayments/' },
        volatility: 'volatile',
      },
      {
        id: 'f-emergency-medicaid',
        claim: 'Emergency Medicaid may cover emergency medical care, including labor and delivery, for people who meet state income rules but do not meet the immigration requirements for full Medicaid.',
        detail:
          'Applying for emergency Medicaid is not the same as applying for full Medicaid. Rules and application processes are run by states.',
        asOf: '2026-09',
        source: { name: 'Medicaid.gov — Eligibility', url: 'https://www.medicaid.gov/medicaid/eligibility/' },
        volatility: 'annual',
      },
      {
        id: 'f-preventive-free',
        claim: 'Non-grandfathered private plans generally must cover recommended preventive services — including many vaccines, screenings and annual visits — without charging you a copay or deductible.',
        asOf: '2026-09',
        source: { name: 'HealthCare.gov — Preventive care benefits', url: 'https://www.healthcare.gov/coverage/preventive-care-benefits/' },
        volatility: 'annual',
      },
      {
        id: 'f-health-center-sliding',
        claim: 'Federally funded community health centers provide primary care to everyone regardless of insurance or immigration status, with fees on a sliding scale based on income.',
        asOf: '2026-09',
        source: { name: 'HRSA — Find a Health Center', url: 'https://findahealthcenter.hrsa.gov/' },
        volatility: 'annual',
      },
      {
        id: 'f-health-insurance-scam',
        claim: 'Health insurance scams commonly sell "discount plans" or limited indemnity products that are not comprehensive coverage, and legitimate help with the Marketplace is free.',
        asOf: '2026-09',
        source: { name: 'FTC — Health insurance scams', url: 'https://consumer.ftc.gov/articles/health-insurance-scams' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'Premium', plain: 'The monthly cost of the plan itself.', watchOut: '"Low premium" plans that cover almost nothing.' },
      { term: 'Deductible', plain: 'What you pay before insurance pays most things.', watchOut: 'Not knowing it, so a "covered" visit still costs $1,800.' },
      { term: 'Copay / coinsurance', plain: 'A fixed amount or a percentage you pay per service.', watchOut: 'Coinsurance of 40% on a big hospital bill.' },
      { term: 'Out-of-pocket maximum', plain: 'Your yearly ceiling for covered in-network care.', watchOut: 'Plans with a very high maximum that leave you exposed.' },
      { term: 'In-network', plain: 'Providers with negotiated prices in your plan.', watchOut: 'An in-network hospital with out-of-network doctors. Ask about everyone who will bill you.' },
      { term: 'Referral', plain: 'A note from your primary doctor letting you see a specialist.', watchOut: 'Seeing a specialist without a referral and paying the whole bill.' },
      { term: 'Prior authorization', plain: 'Insurer approval required before some treatments.', watchOut: 'Assuming your doctor\'s recommendation is automatically paid for.' },
      { term: 'Emergency Medicaid', plain: 'Coverage for emergency care only, for people who do not qualify for full Medicaid.', watchOut: 'Believing the emergency room is your only option for routine care.' },
      { term: 'FQHC / community health center', plain: 'A clinic that serves everyone and charges by income.', watchOut: 'Paying a full private-clinic price when a health center is nearby.' },
    ],
    steps: [
      'Get covered: your employer, healthcare.gov or your state exchange, or your state Medicaid office. Use the official eligibility screener for your status.',
      'Write down your four numbers (premium, deductible, copay, out-of-pocket max) and store a photo of your insurance card in your phone.',
      'Find the nearest community health center now, before you are sick, and save its address. Fees are based on income and no status questions are required to be turned away.',
      'Learn what your plan covers as preventive care, and use those visits — they cost nothing and create a medical history that helps later.',
      'Update your income in your Marketplace account any time it changes, so you do not face a surprise repayment at tax time.',
      'If you lose coverage mid-year, act within 60 days — that is your special enrollment window.',
      'Never buy a plan from someone who contacted you and asks for payment immediately without plan documents.',
    ],
    timeline: [
      { when: 'November 1 – January 15', what: 'Marketplace open enrollment. Compare plans and confirm your subsidy.' },
      { when: 'Any time', what: 'Medicaid and CHIP applications for children, and community health center enrollment, often year-round.' },
      { when: 'Within 60 days of a life event', what: 'Special enrollment period: loss of coverage, move, marriage, birth.' },
      { when: 'Any time income changes', what: 'Update the Marketplace so your subsidy matches reality.' },
      { when: 'Before any appointment', what: 'Confirm in-network status and preventive coverage.' },
    ],
    traps: [
      'Going without care because you are afraid of what it will cost. Health centers and emergency Medicaid exist precisely for that.',
      'Buying a health "discount plan" that is not insurance, and discovering it at the hospital.',
      'Paying a "navigator" or "agent" for Marketplace help that is free.',
      'Not updating your income and getting a tax bill for premium tax credits you were not entitled to.',
      'Assuming the emergency room is free. EMTALA requires treatment, not forgiveness of the bill.',
      'Letting a plan lapse because you missed a payment, then discovering you have no coverage for an entire year until open enrollment.',
      'Ignoring mail from insurance or Medicaid. Recertification notices often require a reply within a deadline.',
      'Telling a clinic you have no immigration papers when you have a valid status that qualifies you for more.',
    ],
    questionsToAsk: [
      'Are you in network for my specific plan?',
      'Is this service covered as preventive care with no cost to me?',
      'What will I owe after insurance for this visit, and can I get that in writing first?',
      'Does this plan cover emergency care, prescriptions, and maternity care?',
      'What is my out-of-pocket maximum for the year, and how much of it have I already used?',
    ],
    officialLinks: [
      { name: 'HealthCare.gov — Coverage for immigrants', url: 'https://www.healthcare.gov/immigrants/lawfully-present-immigrants/' },
      { name: 'HealthCare.gov — Special enrollment periods', url: 'https://www.healthcare.gov/coverage-outside-open-enrollment/special-enrollment-period/' },
      { name: 'Medicaid.gov — Eligibility', url: 'https://www.medicaid.gov/medicaid/eligibility/' },
      { name: 'HRSA — Find a community health center', url: 'https://findahealthcenter.hrsa.gov/' },
      { name: 'CMS — No Surprises Act', url: 'https://www.cms.gov/nosurprises/consumers' },
    ],
    relatedScamIds: ['health-insurance-scam', 'gov-impersonation', 'immigration-services-fraud'],
  },

  {
    id: 'topic-medical-bills',
    slug: 'medical-bills',
    title: 'Medical bills: how to pay less than the first number',
    category: 'health',
    oneLiner:
      'The first bill you receive is an opening offer, not a final price. Errors are common, financial assistance exists by law at nonprofit hospitals, and medical debt affects your credit differently from other debt.',
    whyItMatters:
      'People treat a hospital bill the way they treat a tax bill — as unappealable. Immigrants who already fear official correspondence just pay, or ignore it until it goes to collections. Both are expensive. There is a process, and it is on your side if you use it.',
    keywords: [
      'medical bill', 'hospital bill', 'surprise bill', 'bill too high',
      'financial assistance', 'charity care', 'hospital debt', 'collections',
      'no surprises act', 'negotiate bill', 'payment plan', 'itemized bill',
    ],
    explain: [
      'Start by asking for an itemized bill — the line-by-line version rather than the summary. Errors on hospital bills are common: duplicate charges, services you never received, wrong codes, and out-of-network charges that should have been in-network. Compare it against your insurance explanation of benefits. Where the two disagree, call the hospital\'s billing department and ask them to correct it. This one step frequently removes real money.',
      'Then ask for two things by name. First, the financial assistance policy. Nonprofit hospitals — which is most hospitals — are required as a condition of their tax status to have a written financial assistance policy, and to tell you about it. Second, a self-pay discount. If you have no insurance, or your insurance paid little, the cash price is often dramatically lower than the first number, and hospitals will usually accept a payment plan if you ask before the account goes to collections.',
      'Know your legal protections too. The No Surprises Act protects people with most forms of coverage from certain surprise out-of-network bills, especially for emergency care, and there is a complaint process if you receive one anyway. If your bill was for an emergency, and you are not eligible for regular Medicaid, emergency Medicaid may cover it — ask the hospital\'s financial counselor.',
      'Finally, do not let it become a collections problem. Under the credit bureaus\' current voluntary policies, paid medical collections are removed from reports, unpaid medical collections under $500 are not reported, and unpaid medical debt gets a one-year grace period before it can appear. That is a window to fix the bill. Note also that if you put a medical bill on a credit card, it stops being "medical debt" for these purposes and becomes ordinary card debt with none of those protections.',
    ],
    facts: [
      {
        id: 'f-itemized-bill',
        claim: 'You can request a line-by-line itemized bill from a hospital, and billing errors and duplicate charges are common enough that reviewing it is standard advice.',
        asOf: '2026-09',
        source: { name: 'CMS — Hospital price transparency and billing', url: 'https://www.cms.gov/priorities/key-initiatives/hospital-price-transparency' },
        volatility: 'annual',
      },
      {
        id: 'f-501r-financial-assistance',
        claim: 'Nonprofit hospitals must have a written financial assistance policy and must widely publicize it as a condition of their tax-exempt status under section 501(r).',
        detail:
          'Ask specifically for the "financial assistance policy" and the application form. Many hospitals will reduce or eliminate bills for households under income thresholds.',
        asOf: '2026-09',
        source: { name: 'IRS — Financial assistance requirements under section 501(r)', url: 'https://www.irs.gov/charities-non-profits' },
        volatility: 'stable',
      },
      {
        id: 'f-nosurprises-detail',
        claim: 'The No Surprises Act bans balance billing for most emergency services and for certain out-of-network services at in-network facilities, and provides a federal complaint process.',
        asOf: '2026-09',
        source: { name: 'CMS — No Surprises Act consumer information', url: 'https://www.cms.gov/nosurprises/consumers' },
        volatility: 'stable',
      },
      {
        id: 'f-credit-reporting-medical',
        claim: 'The credit bureaus voluntarily do not report paid medical collections, do not report unpaid medical collections under $500, and give unpaid medical debt about one year before it can appear on a report.',
        detail:
          'A federal rule that would have removed medical debt from credit reports entirely was vacated by a court in July 2025, so these voluntary policies and state laws are what remain. A hospital bill paid with a credit card loses these protections and becomes ordinary card debt.',
        asOf: '2026-05',
        source: { name: 'Consumer Financial Protection Bureau — Medical debt', url: 'https://www.consumerfinance.gov/consumer-tools/medical-debt/' },
        volatility: 'volatile',
      },
      {
        id: 'f-hipaa-privacy',
        claim: 'HIPAA protects the privacy of your health information, and providers generally may not share details of your care without your authorization.',
        asOf: '2026-09',
        source: { name: 'HHS — HIPAA for individuals', url: 'https://www.hhs.gov/hipaa/for-individuals/index.html' },
        volatility: 'stable',
      },
      {
        id: 'f-medical-bill-scam',
        claim: 'Fake medical bills are used in collection scams: an unexpected email or text demanding payment for a hospital visit, with a link or phone number to pay.',
        asOf: '2026-09',
        source: { name: 'FTC — Fake and imposter scams', url: 'https://consumer.ftc.gov/features/scams' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'Itemized bill', plain: 'The full list of every charge.', watchOut: 'Being charged for days or services that never happened.' },
      { term: 'Explanation of Benefits (EOB)', plain: 'Your insurer\'s statement of what was billed, allowed, and paid.', watchOut: 'Throwing it away, then having no way to check the hospital bill.' },
      { term: 'Balance billing', plain: 'A provider billing you the gap between their charge and the insurer\'s payment.', watchOut: 'Out-of-network providers at an in-network hospital. Sometimes illegal, sometimes not.' },
      { term: 'Charity care / financial assistance', plain: 'A hospital program that reduces or cancels bills based on income.', watchOut: 'Nobody telling you it exists. You have to ask for it by name.' },
      { term: 'Self-pay discount', plain: 'A lower price for people paying without insurance.', watchOut: 'Paying the full billed amount because nobody asked.' },
      { term: 'Payment plan', plain: 'An agreement to pay over months, often interest-free.', watchOut: 'A collections agency offering a plan with fees attached.' },
      { term: 'Collections', plain: 'A debt collector takes over the account. Usually after 90–180 days.', watchOut: 'Ignoring it until it is on your credit report.' },
    ],
    steps: [
      'Do not pay the first bill. Ask for the itemized bill and the explanation of benefits from your insurer.',
      'Compare them. Circle anything duplicated, unfamiliar, or incorrectly coded, and call billing to dispute each item.',
      'Ask by name for the hospital\'s financial assistance policy and application. Fill it out, even if you think you earn too much.',
      'Ask for a self-pay or prompt-pay discount, and for an interest-free payment plan you can realistically afford. Get the agreement in writing.',
      'If it was emergency care and you lack full Medicaid eligibility, ask the financial counselor about emergency Medicaid.',
      'If you receive a surprise out-of-network bill for emergency care, file a complaint through the No Surprises Act process.',
      'If a "biller" contacts you unexpectedly, hang up and call the number on the hospital\'s own website. Never pay from a link in a text or email.',
    ],
    traps: [
      'Paying the whole bill immediately out of fear, without asking about financial assistance.',
      'Putting a hospital bill on a credit card, which converts protected medical debt into unprotected card debt.',
      'Ignoring bills until they reach collections, then paying a collection agency that adds fees.',
      'Assuming you do not qualify for charity care because you have a job. Many hospitals\' thresholds are higher than people expect.',
      'Believing the emergency room is a free clinic. EMTALA requires screening and stabilization; it does not erase the bill.',
      'Giving a collector your bank details by phone before they have validated the debt in writing.',
      'Paying a "medical billing advocate" a percentage when the hospital will do the same negotiation with you for free.',
      'Not keeping copies of the financial assistance application and payment plan.',
    ],
    questionsToAsk: [
      'Can you send me an itemized bill, and can you explain each line I do not recognize?',
      'What is your financial assistance policy, and how do I apply?',
      'What is the self-pay price for this service, and is there a prompt-pay discount?',
      'Can we set up an interest-free payment plan, and will you put it in writing?',
      'Was any of this out of network, and does the No Surprises Act apply to me?',
    ],
    officialLinks: [
      { name: 'CMS — No Surprises Act (consumers)', url: 'https://www.cms.gov/nosurprises/consumers' },
      { name: 'IRS — Hospital financial assistance requirements', url: 'https://www.irs.gov/charities-non-profits' },
      { name: 'CFPB — Medical debt', url: 'https://www.consumerfinance.gov/consumer-tools/medical-debt/' },
      { name: 'CFPB — Submit a complaint', url: 'https://www.consumerfinance.gov/complaint/' },
      { name: 'HHS — HIPAA for individuals', url: 'https://www.hhs.gov/hipaa/for-individuals/index.html' },
    ],
    relatedScamIds: ['debt-collection', 'medical-bill-scam', 'gov-impersonation'],
  },

  {
    id: 'topic-emergency-care',
    slug: 'emergency-room-or-clinic',
    title: 'Emergency room, urgent care, or a clinic: choosing correctly saves you thousands',
    category: 'health',
    oneLiner:
      'The emergency room must treat you regardless of insurance or status, but it is also the most expensive option. Urgent care and community health centers handle most everyday problems for a fraction of the cost.',
    whyItMatters:
      'The single most expensive decision a newcomer makes in a normal month is choosing the wrong door for a health problem. And because emergency care carries legal protections for everyone, knowing the difference lets you stop avoiding care out of fear.',
    keywords: [
      'emergency room', 'er', 'urgent care', 'clinic', 'emtala', 'no insurance doctor',
      'where to go', '911', 'ambulance', 'chest pain', 'fever', 'insurance no',
      'free clinic', 'dental',
    ],
    explain: [
      'The rule that protects everyone: hospitals with emergency departments that participate in Medicare must provide a medical screening exam and stabilizing treatment for anyone who comes in, regardless of insurance, ability to pay, or immigration status. That is a federal law (EMTALA). It does not mean the visit is free — it means you cannot be turned away at the door, and you can be asked about payment afterward. Do not let fear of a bill stop you from going in a real emergency. An untreated heart attack or stroke is not a financial risk, it is a permanent one.',
      'The cheaper doors: urgent care centers handle sprains, fevers, infections, stitches and simple tests, usually for a few hundred dollars instead of a few thousand. Community health centers (federally qualified health centers) provide primary care, pediatrics, dental and mental health services with sliding-scale fees based on income, and they serve everyone regardless of status. For prescriptions, ask about generic options and discount programs — the price difference is often 5x to 10x.',
      'Call 911 for a real emergency: chest pain, difficulty breathing, severe bleeding, signs of stroke (face drooping, arm weakness, speech trouble), unconsciousness, or a serious accident. An ambulance is expensive, so people hesitate — that hesitation is what kills. If you cannot afford it afterward, ask the hospital\'s financial counselor for the financial assistance policy. You can address the bill later; you cannot address a stroke later.',
      'One more practical thing: many communities have free or low-cost clinics run by nonprofits, immigrant organizations and religious groups, plus school-based health centers and mobile clinics. Ask at a library, at a 211 line, or at the pharmacy counter. It is not disreputable to ask — half the country is asking the same question.',
    ],
    facts: [
      {
        id: 'f-emtala',
        claim: 'Under EMTALA, hospitals with emergency departments must provide a medical screening examination and stabilizing treatment to anyone who comes to the emergency department, regardless of insurance, citizenship or ability to pay.',
        asOf: '2026-09',
        source: { name: 'CMS — EMTALA information', url: 'https://www.cms.gov/priorities/your-patient-rights/emergency-room-rights' },
        volatility: 'stable',
      },
      {
        id: 'f-sliding-scale-clinics',
        claim: 'Federally qualified health centers provide care to all patients regardless of ability to pay, with fees adjusted by income and family size.',
        asOf: '2026-09',
        source: { name: 'HRSA — Find a Health Center', url: 'https://findahealthcenter.hrsa.gov/' },
        volatility: 'annual',
      },
      {
        id: 'f-911',
        claim: '911 is free to call and dispatches emergency medical services, fire and police; you are not charged for making the call, though ambulance transport may be billed.',
        asOf: '2026-09',
        source: { name: 'USA.gov — Emergency resources', url: 'https://www.usa.gov/disasters-and-emergencies' },
        volatility: 'stable',
      },
      {
        id: 'f-hipaa-anyone',
        claim: 'HIPAA protects your health information regardless of immigration status, so a hospital generally cannot report your immigration status to authorities as part of providing care.',
        detail:
          'HIPAA has narrow exceptions, and healthcare providers are not immigration enforcement. If you have specific concerns, ask to speak with a patient advocate or a hospital social worker before treatment.',
        asOf: '2026-09',
        source: { name: 'HHS — HIPAA for individuals', url: 'https://www.hhs.gov/hipaa/for-individuals/index.html' },
        volatility: 'stable',
      },
      {
        id: 'f-vaccines',
        claim: 'Vaccines are widely available and often free or low-cost at health centers, pharmacies and public health departments, and public health departments provide immunizations regardless of insurance status in most areas.',
        asOf: '2026-09',
        source: { name: 'Vaccines.gov', url: 'https://www.vaccines.gov/' },
        volatility: 'annual',
      },
      {
        id: 'f-mental-health-988',
        claim: '988 is the Suicide and Crisis Lifeline: a free, confidential phone, text and chat line available 24/7 in the US, with interpretation in multiple languages.',
        asOf: '2026-09',
        source: { name: '988 Suicide and Crisis Lifeline', url: 'https://988lifeline.org/' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'EMTALA', plain: 'The law requiring emergency departments to screen and stabilize everyone.', watchOut: 'Believing it means treatment is free. It means treatment is required.' },
      { term: 'Urgent care', plain: 'A walk-in clinic for problems that are not life-threatening.', watchOut: 'Going to the ER for a sprain and paying ten times more.' },
      { term: 'FQHC / community health center', plain: 'A sliding-scale clinic for everyone.', watchOut: 'Not knowing where the nearest one is when you need it.' },
      { term: 'Ambulance bill', plain: 'A separate charge from a transport company, sometimes plus a fire service charge.', watchOut: 'Not calling 911 for a stroke because of the cost.' },
      { term: 'Patient advocate / social worker', plain: 'Hospital staff whose job includes helping with bills and benefits.', watchOut: 'Never asking for one.' },
      { term: 'Patient assistance program', plain: 'Manufacturer programs giving free or cheap prescription drugs.', watchOut: 'Paying full price for a drug that has a free program.' },
      { term: '988', plain: 'The mental health and suicide crisis line.', watchOut: 'Nobody has to face a crisis alone, in any language.' },
    ],
    steps: [
      'Save the nearest community health center and urgent care center in your phone today, before you need them.',
      'Learn the emergency signs that mean call 911: chest pain, trouble breathing, stroke symptoms, severe bleeding, loss of consciousness.',
      'Keep your insurance card, your ID, and a list of medications in one place you can grab quickly.',
      'If you get a bill afterward that you cannot pay, ask for the financial assistance policy — not a loan, not a credit card.',
      'If you have no insurance, ask every provider for the self-pay rate and always ask whether the nearest health center could handle this.',
      'Ask about interpretation services. Hospitals that receive federal funds must generally provide language assistance at no cost to you, and you are allowed to refuse to sign anything you cannot understand.',
    ],
    traps: [
      'Avoiding care for fear of the bill, until a small problem becomes an emergency admission.',
      'Using the emergency room for prescriptions, check-ups, or minor illness, at enormous cost per visit.',
      'Agreeing to sign financial responsibility forms you cannot read without asking for an interpreter.',
      'Assuming a hospital will not treat you without insurance. That is not how EMTALA works.',
      'Not asking about patient assistance programs for expensive prescriptions.',
      'Calling a rideshare instead of an ambulance for a genuine emergency.',
      'Not asking for language interpretation and instead using a child as a translator for medical decisions.',
    ],
    questionsToAsk: [
      'Would this be safe to treat at urgent care or my health center instead?',
      'Do you have an interpreter available, and can I have one?',
      'What will this cost me, roughly, before you do it?',
      'Is there a financial counselor or patient advocate I can talk to about the bill?',
      'Can you prescribe a generic version of this medication?',
    ],
    officialLinks: [
      { name: 'CMS — EMTALA information', url: 'https://www.cms.gov/priorities/your-patient-rights/emergency-room-rights' },
      { name: 'HRSA — Find a community health center', url: 'https://findahealthcenter.hrsa.gov/' },
      { name: '988 — Suicide and Crisis Lifeline', url: 'https://988lifeline.org/' },
      { name: 'HHS — HIPAA for individuals', url: 'https://www.hhs.gov/hipaa/for-individuals/index.html' },
      { name: '211 — Local help', url: 'https://www.211.org/' },
    ],
    relatedScamIds: ['medical-bill-scam', 'debt-collection'],
  },
]
