import type { Topic } from '../types'

export const homeTopics: Topic[] = [
  {
    id: 'topic-renting-first-apartment',
    slug: 'rent-your-first-apartment',
    title: 'Renting your first US apartment without being overcharged',
    category: 'home',
    oneLiner:
      'Renting is a chain of small documents: application, credit or background screening, deposit, lease, and a condition report. Each step has a number attached, and each number is negotiable more often than people think.',
    whyItMatters:
      'Housing is the largest monthly cost and the easiest place to be cheated when you do not know what is normal. New arrivals pay double deposits, rent apartments they never see, lose deposits to invented cleaning charges, and accept illegal rules — like paying rent only in cash with no receipt — because nobody told them otherwise.',
    keywords: [
      'rent', 'apartment', 'lease', 'landlord', 'deposit', 'security deposit',
      'credit check for apartment', 'no credit history apartment', 'sublease',
      'roommate', 'guarantor', 'cosigner', 'application fee', 'rent increase',
      'illegal lease clause', 'fair housing', 'eviction',
    ],
    explain: [
      'Start with the fair housing rule, because it is your strongest protection: a landlord in the US may not refuse to rent to you, or treat you differently, because of your race, color, national origin, religion, sex (including sexual orientation and gender identity), familial status or disability. Asking about your national origin or immigration status in a screening context, or refusing you because you "sound foreign", can be illegal. If that happens, you can file a complaint with HUD for free.',
      'Then learn the money chain. An application fee pays for a screening report. A security deposit is your money held against damage — not a fee, and not the landlord\'s money to keep. First month\'s rent is rent. Anything else has to be named and explained. If a landlord asks for a "move-in fee" that is explicitly non-refundable, ask what it covers and get it in writing; in some places those are capped or restricted. All of it belongs on the lease.',
      'When you do not have US credit history, say so up front and offer alternatives: a larger deposit where legally allowed, a co-signer or guarantor, proof of income (offer letter, pay stubs, bank statements), or a letter from a previous landlord. Landlords care about getting paid reliably, and documents that show stability usually beat a thin credit file. Many screening companies also accept alternative data such as rent payment history.',
      'Finally, protect the evidence. Photograph and video every room before you move your things in, note existing damage on the move-in checklist, and pay rent in a traceable way — bank transfer or a check — because cash rent with no receipt is how people end up accused of not paying. If a problem appears later (mold, no heat, a broken lock, a leak), ask for repairs in writing. Keep a copy. Every state has a rule about what a landlord must fix and how long they have, and the state agencies listed in your state panel are where you check the specifics.',
    ],
    facts: [
      {
        id: 'f-fha-protected',
        claim: 'The Fair Housing Act prohibits discrimination in housing based on race, color, national origin, religion, sex (including sexual orientation and gender identity), familial status, and disability.',
        detail:
          'Complaints can be filed with HUD at no cost. Retaliation for filing a complaint is itself prohibited.',
        asOf: '2026-09',
        source: { name: 'HUD — Fair Housing: it is your right', url: 'https://www.hud.gov/program_offices/fair_housing_equal_opp' },
        volatility: 'stable',
      },
      {
        id: 'f-adverse-action',
        claim: 'If a landlord denies your application based on a tenant screening or credit report, you are generally entitled to an adverse action notice telling you the reason and which company provided the report, so you can check it for errors.',
        detail:
          'This is the fastest route to fixing a wrong file: get the notice, get the report, dispute the errors directly with the screening company.',
        asOf: '2026-09',
        source: { name: 'Consumer Financial Protection Bureau — Adverse action notices', url: 'https://www.consumerfinance.gov/ask-cfpb/what-is-an-adverse-action-notice-under-the-eco-en-1695/' },
        volatility: 'stable',
      },
      {
        id: 'f-deposit-is-your-money',
        claim: 'A security deposit is your money held in trust against unpaid rent or damage, not a fee; most states set a maximum amount and a deadline for returning it with an itemized list of deductions.',
        detail:
          'Deposit caps, return deadlines (often 14–60 days) and rules about normal wear and tear vary by state — check your state\'s official tenant guide, linked per state in the roadmap.',
        asOf: '2026-09',
        source: { name: 'HUD — Tenant rights, responsibilities and fair housing', url: 'https://www.hud.gov/topics/rental_assistance/tenantrights' },
        volatility: 'annual',
      },
      {
        id: 'f-notice-to-enter',
        claim: 'Landlords must generally give advance notice (commonly 24–48 hours) before entering a rented home except in genuine emergencies, and may only enter for stated reasons.',
        asOf: '2026-09',
        source: { name: 'HUD — Tenant rights, responsibilities and fair housing', url: 'https://www.hud.gov/topics/rental_assistance/tenantrights' },
        volatility: 'annual',
      },
      {
        id: 'f-eviction-court',
        claim: 'An eviction must go through a court process. Lockouts without a court order — changing locks, removing belongings, shutting off utilities — are illegal self-help evictions everywhere in the US.',
        detail:
          'If this happens to you, treat it as an emergency: contact legal aid immediately and document everything with photos and dates.',
        asOf: '2026-09',
        source: { name: 'USA.gov — Housing and eviction help', url: 'https://www.usa.gov/housing-help' },
        volatility: 'annual',
      },
      {
        id: 'f-rent-receipts',
        claim: 'Renters should keep proof of every rent payment — bank transfers, cancelled checks, or written receipts — because accepted payment history is what decides a dispute about nonpayment or a future landlord reference.',
        asOf: '2026-09',
        source: { name: 'Consumer Financial Protection Bureau — Rent payment reporting', url: 'https://www.consumerfinance.gov/consumer-tools/credit-reports-and-scores/' },
        volatility: 'stable',
      },
      {
        id: 'f-rental-scam',
        claim: 'The classic rental scam is an attractive listing, a landlord who cannot meet you, and a demand for a deposit or first month by wire or payment app to "hold" the unit.',
        detail:
          'Never send money for a home you have not entered and whose ownership you have not verified.',
        asOf: '2026-09',
        source: { name: 'FTC — Rental listing scams', url: 'https://consumer.ftc.gov/articles/rental-listing-scams' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'Security deposit', plain: 'Your money held against damage or unpaid rent. Refundable in principle.', watchOut: 'A "deposit" that the lease calls non-refundable.' },
      { term: 'Application fee', plain: 'Pays for the screening report. Usually modest, and it should be disclosed before you pay.', watchOut: 'Large per-adult fees that never produce a decision.' },
      { term: 'Guarantor / co-signer', plain: 'A person who promises to pay if you do not. Often needed without US credit history.', watchOut: 'A paid "guarantor service" that charges a big fee and guarantees nothing.' },
      { term: 'Lease term', plain: 'How long the agreement lasts — commonly 12 months.', watchOut: 'A 12-month lease with an auto-renew clause that traps you in a rent increase.' },
      { term: 'Month-to-month', plain: 'A rolling tenancy that either side can end with proper notice.', watchOut: 'Verbal month-to-month with no rent receipts and no written notice rules.' },
      { term: 'Wear and tear', plain: 'Normal aging of a home that cannot be charged to you.', watchOut: '"Cleaning fee" and "repainting" deducted from a deposit for a clean apartment.' },
      { term: 'Move-in checklist', plain: 'The written record of existing damage at the start.', watchOut: 'Not filling one out, then being blamed for damage that was already there.' },
      { term: 'Sublease', plain: 'Renting from a tenant rather than the owner.', watchOut: 'No written approval from the landlord — you can be removed even if you paid.' },
      { term: 'Section 8 / HCV', plain: 'A federal voucher program that pays part of the rent to the landlord.', watchOut: 'Anyone charging a fee to "get you a voucher". Applications are free through your housing authority.' },
    ],
    steps: [
      'Before applying, ask: total move-in cost, deposit amount and its legal cap in your state, whether utilities are included, and whether the lease is 12 months or month-to-month.',
      'Get everything in writing before paying: address, unit, rent amount, deposit, fees, and what is included.',
      'Visit the apartment in person and check that the name on the lease matches the person you are paying. If you absolutely must rent unseen, use a video walkthrough plus a payment to a verified company — never to an individual.',
      'Pay with a traceable method and get a receipt. Keep a copy of the signed lease and every payment record.',
      'Complete a move-in condition report the same day, with photos and video of every room, appliance and pre-existing damage. Email a copy to the landlord so there is a dated record.',
      'If you do not understand the lease, have someone you trust translate it — not the landlord\'s friend. Never sign a document you cannot read.',
      'Ask about repairs in writing when problems appear, and keep the paper trail. Then use your state agency if the landlord does not act.',
    ],
    timeline: [
      { when: '2–6 weeks before move-in', what: 'Budget the full move-in cost (first month + deposit + fees + utilities deposits), not just monthly rent.' },
      { when: 'Application day', what: 'Ask for the screening criteria in writing before paying a fee.' },
      { when: 'Lease signing day', what: 'Read the whole lease. Photograph each page. Confirm deposit and fee amounts match what was promised.' },
      { when: 'Move-in day', what: 'Complete the condition report with photos before furniture arrives.' },
      { when: 'Every month', what: 'Pay rent traceably. Keep receipts. Report habitability problems in writing.' },
      { when: '60–90 days before lease end', what: 'Decide to renew or move. Ask for the renewal rent in writing.' },
    ],
    traps: [
      'Paying a deposit by wire, gift card or app to a "landlord" you have never met, for an apartment you have never seen.',
      'Paying cash rent with no receipt, then being unable to prove you paid.',
      'Signing a lease in a language you do not understand without a translation you trust.',
      'Accepting a lease clause that says the landlord may enter without notice, or that you waive your right to repairs. Some clauses are unenforceable, but you have to object.',
      'Believing a "no credit, no problem" ad that requires a $2,000 upfront "insurance" payment.',
      'Not asking who pays for utilities, trash, parking, and the internet — then discovering the lease includes a billing service that adds 30% to your bills.',
      'Being pressured into a "cash only, no lease" arrangement where you have no tenancy rights to prove.',
      'Missing the deadline to give notice you are not renewing, and being automatically renewed at a higher rent.',
      'Assuming a verbal promise ("we will fix the heat next week") has any value. Put it in writing or it did not happen.',
    ],
    questionsToAsk: [
      'What is the total amount due before I get the keys, itemized?',
      'What is the deposit amount, and what does my state say the maximum is?',
      'Which utilities are included, and what was the average monthly bill last year?',
      'Is there a non-refundable fee of any kind, and what does it cover?',
      'Can I see the lease before I pay the application fee?',
      'How do I request repairs, and how long do I wait before I can escalate?',
      'Will you provide written receipts for every rent payment?',
    ],
    officialLinks: [
      { name: 'HUD — Fair housing complaints', url: 'https://www.hud.gov/program_offices/fair_housing_equal_opp/online-complaint' },
      { name: 'HUD — Tenant rights and responsibilities', url: 'https://www.hud.gov/topics/rental_assistance/tenantrights' },
      { name: 'USA.gov — Housing help and rental assistance', url: 'https://www.usa.gov/housing-help' },
      { name: 'FTC — Rental listing scams', url: 'https://consumer.ftc.gov/articles/rental-listing-scams' },
      { name: 'CFPB — Tenant screening reports', url: 'https://www.consumerfinance.gov/ask-cfpb/what-is-a-tenant-screening-report-en-1979/' },
    ],
    relatedScamIds: ['rental-listing', 'deposit-scam', 'landlord-cash'],
  },

  {
    id: 'topic-moving-out-deposit',
    slug: 'get-your-deposit-back',
    title: 'Getting your security deposit back',
    category: 'home',
    oneLiner:
      'Landlords may only deduct for unpaid rent and damage beyond normal wear and tear, must usually provide an itemized list, and must meet a statutory deadline to return the rest.',
    whyItMatters:
      'A deposit is often one to two months of rent — for a new arrival, that is the entire next move. Most deposit disputes are won or lost on evidence created months earlier, not on argument at the end.',
    keywords: [
      'security deposit', 'deposit back', 'landlord kept my deposit', 'move out',
      'cleaning fee', 'damage', 'itemized', 'wear and tear', 'small claims',
      'move out inspection', 'deductions',
    ],
    explain: [
      'The law protects you on paper: the deposit is your property, deductions must be itemized, and ordinary wear and tear cannot be charged to you. In practice, whether you get it back depends enormously on what you documented at move-in and move-out. If you never wrote down that the carpet was stained in month one, you will probably pay for it in month twelve.',
      'When you prepare to leave, request a move-in-style inspection before you hand over the keys if your state allows it, take date-stamped photos and video of a clean, empty apartment, return the keys in a way you can prove — a receipt or a witness — and give your forwarding address in writing. That last item matters more than people realize: in many states the landlord\'s clock to return your deposit starts when they receive your forwarding address.',
      'If the deadline passes with no deposit and no itemized statement, send a written demand letter (email is fine, keep a copy) citing your state\'s deadline and saying you will pursue it in small claims court. Small claims court is designed for exactly this: no lawyer needed, low filing fees, and judges are used to deposit cases with clear paperwork. What wins is a folder, not a speech.',
    ],
    facts: [
      {
        id: 'f-deposit-itemized',
        claim: 'Most states require the landlord to provide an itemized written statement of deductions and return the remaining deposit within a set number of days (commonly 14–30 days) after the tenant vacates.',
        asOf: '2026-09',
        source: { name: 'HUD — Tenant rights', url: 'https://www.hud.gov/topics/rental_assistance/tenantrights' },
        volatility: 'annual',
      },
      {
        id: 'f-wear-tear',
        claim: 'Deposits may not generally be used to cover normal wear and tear, such as minor scuffs, faded paint or a carpet at the end of its useful life.',
        asOf: '2026-09',
        source: { name: 'USA.gov — Housing help', url: 'https://www.usa.gov/housing-help' },
        volatility: 'annual',
      },
      {
        id: 'f-small-claims',
        claim: 'Small claims courts handle deposit disputes with low filing fees and usually without lawyers, and state court self-help websites publish the forms and limits.',
        asOf: '2026-09',
        source: { name: 'USA.gov — Small claims court', url: 'https://www.usa.gov/small-claims-court' },
        volatility: 'annual',
      },
      {
        id: 'f-photos-evidence',
        claim: 'Date-stamped photos and a signed move-in condition report are the standard evidence used to rebut improper deposit deductions.',
        asOf: '2026-09',
        source: { name: 'Consumer Financial Protection Bureau — Renters and housing', url: 'https://www.consumerfinance.gov/consumer-tools/credit-reports-and-scores/' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'Itemized statement', plain: 'A list of each deduction with an amount.', watchOut: 'A single line saying "cleaning $400" with no receipts or detail.' },
      { term: 'Normal wear and tear', plain: 'The unavoidable aging of a home.', watchOut: 'Being charged for repainting a unit you lived in for three years.' },
      { term: 'Forwarding address', plain: 'Where the landlord must send your deposit.', watchOut: 'Not giving one in writing — in many states, that is what starts their clock.' },
      { term: 'Move-out inspection', plain: 'A documented walkthrough before you return keys.', watchOut: 'A verbal walkthrough with no written list.' },
      { term: 'Small claims court', plain: 'A simplified court for money disputes under a state-set limit.', watchOut: 'Paying a "deposit recovery company" half your money for a form you can file yourself.' },
      { term: 'Demand letter', plain: 'A written request with a deadline before you escalate.', watchOut: 'Only ever complaining by phone. Nothing is provable.' },
    ],
    steps: [
      'At move-in: photograph and video everything, note every scratch on the condition report, and email the report to the landlord so the date is recorded.',
      'During the tenancy: report problems in writing and keep copies. Do not make major repairs yourself without written agreement on who pays.',
      'Before you move out: read your lease for required notice (often 30–60 days) and give written notice on time.',
      'Clean the unit, then photograph and video it empty, with todays date visible — wide shots and close-ups of every room, appliance and floor.',
      'Return the keys in a provable way and give your forwarding address in writing. Ask for a receipt or send the address by email.',
      'If the deadline passes with no money and no itemized statement, send a written demand with a 10-day deadline, referencing your state\'s statute.',
      'If they still do not pay, file in small claims court. Bring your photos, the lease, the receipts and the demand letter.',
    ],
    timeline: [
      { when: 'Move-in day 0', what: 'Photos, video, written condition report, emailed copy.' },
      { when: 'Every year', what: 'Re-photograph the unit in reasonable condition to prove you maintained it.' },
      { when: '60 days before move-out', what: 'Give written notice per your lease. Confirm the exact last day and rent owed.' },
      { when: 'Move-out day', what: 'Clean, photograph, return keys with proof, provide forwarding address.' },
      { when: 'State deadline (often 14–30 days later)', what: 'Deposit should arrive. If not, send a written demand.' },
      { when: 'After demand deadline', what: 'File in small claims court. Filing fees are low and lawyers are usually unnecessary.' },
    ],
    traps: [
      'No move-in photos. Without them, you cannot disprove a damage claim.',
      'Paying a "deposit recovery" company a large percentage to do what you can do in small claims court for a filing fee.',
      'Not giving a forwarding address, so the landlord "cannot" return the deposit.',
      'Leaving items behind, which gives the landlord a reason to charge for removal.',
      'Believing a landlord who says deposits are never returned in the US. That is not the law.',
      'Signing a move-out statement saying you are satisfied before you actually receive the money.',
      'Letting the landlord keep the deposit because you are moving abroad and think you cannot pursue it. Small claims can often be handled remotely or by a trusted representative with your written authorization.',
      'Throwing away the lease or the receipts when you move.',
    ],
    questionsToAsk: [
      'What is the exact deadline in this state for returning my deposit with an itemized statement?',
      'Can we do a move-out inspection, and will you give me the written result?',
      'Which deductions are you claiming, and do you have receipts for the repairs or replacement?',
      'Will you put your agreement to keep part of the deposit in writing?',
    ],
    officialLinks: [
      { name: 'USA.gov — Small claims court', url: 'https://www.usa.gov/small-claims-court' },
      { name: 'HUD — Tenant rights', url: 'https://www.hud.gov/topics/rental_assistance/tenantrights' },
      { name: 'USA.gov — Housing help', url: 'https://www.usa.gov/housing-help' },
      { name: 'Consumer Financial Protection Bureau — Submit a complaint', url: 'https://www.consumerfinance.gov/complaint/' },
    ],
    relatedScamIds: ['deposit-scam', 'landlord-cash'],
  },

  {
    id: 'topic-utilities-setup',
    slug: 'set-up-utilities',
    title: 'Utilities, bills and the "shut-off" phone call',
    category: 'home',
    oneLiner:
      'Electricity, gas, water, internet and phone each have their own account, deposit and shut-off rules — and each one is impersonated by scammers who threaten immediate disconnection.',
    whyItMatters:
      'Loss of electricity in winter is a crisis, and the threat of it is the single most effective pressure tactic used against people who are new to the system. Meanwhile, the genuine programs that reduce these bills are under-used because nobody mentions them at the moment of setup.',
    keywords: [
      'utilities', 'electric bill', 'gas bill', 'water bill', 'internet', 'wifi',
      'shut off notice', 'disconnection', 'deposit for utilities', 'LIHEAP',
      'phone plan', 'utility scam', 'autopay', 'account number',
    ],
    explain: [
      'When you set up an account, a utility may ask for a deposit if you have no credit history or a previous unpaid balance. That is normal. What is not normal is a deposit paid to an individual, in cash, with no account number and no receipt. Legitimate utilities give you an account number the same day and send a confirmation.',
      'Set up autopay or a calendar reminder the day you get the account number. In the US, a missed bill does not just mean a late fee — it can mean a shut-off notice, a reconnection charge, and a deposit requirement before service resumes. If you genuinely cannot pay, contact the utility before the deadline: most have payment plans, hardship protections, and winter or hot-weather moratoriums that stop disconnection entirely for a period.',
      'Then there is the impersonation layer. Someone calls saying your power will be cut in 45 minutes unless you pay by prepaid card, gift card or app right now. The threat of an imminent shut-off, the refusal to let you hang up and call back, and the demand for an untraceable payment are the three signals. Real utilities send you a written notice with an account number and give you a way to pay through your own account portal. Hang up and call the number printed on your own bill.',
      'Ask about the real programs while you set up: LIHEAP for heating and cooling costs, state and utility hardship funds, and the federal Lifeline program for phone or internet discounts. These are legitimate, free to apply for, and rarely involve any fee. If someone charges you a fee to "enroll" you in a government assistance program, that is the scam.',
    ],
    facts: [
      {
        id: 'f-liheap',
        claim: 'LIHEAP is a federal program that helps eligible households pay heating and cooling bills, and it is administered through states, tribes and territories.',
        asOf: '2026-09',
        source: { name: 'Administration for Children and Families — LIHEAP', url: 'https://www.acf.hhs.gov/ocs/programs/liheap' },
        volatility: 'annual',
      },
      {
        id: 'f-lifeline',
        claim: 'The FCC Lifeline program provides a monthly discount on phone or broadband service for qualifying low-income households, and you can check eligibility and apply through the official Lifeline site.',
        asOf: '2026-09',
        source: { name: 'FCC — Lifeline Program', url: 'https://www.lifelinesupport.org/' },
        volatility: 'annual',
      },
      {
        id: 'f-utility-scam',
        claim: 'Utility impersonation scams use a fake urgent shut-off threat and demand payment by prepaid card, gift card or payment app; utilities do not demand untraceable payment and give written notice before disconnection.',
        asOf: '2026-09',
        source: { name: 'FTC — Utility scams', url: 'https://consumer.ftc.gov/articles/utility-scams' },
        volatility: 'stable',
      },
      {
        id: 'f-disconnection-rules',
        claim: 'Disconnection rules, notice requirements, payment plans, and seasonal moratoriums are set by state utility commissions, and consumer advocates at those commissions can help if you are facing a shut-off.',
        asOf: '2026-09',
        source: { name: 'National Association of Regulatory Utility Commissioners — Consumer resources', url: 'https://www.naruc.org/consumer/' },
        volatility: 'annual',
      },
      {
        id: 'f-211',
        claim: 'The 211 service connects callers in the US to local help with utility bills, food, housing and other needs, in many languages.',
        asOf: '2026-09',
        source: { name: 'United Way — 211', url: 'https://www.211.org/' },
        volatility: 'annual',
      },
    ],
    jargon: [
      { term: 'Deposit', plain: 'Money a utility holds until you build payment history with them.', watchOut: 'A deposit demanded in cash with no account number or receipt.' },
      { term: 'Autopay', plain: 'Automatic bill payment from your bank or card.', watchOut: 'Autopay on an account you do not monitor, so a price increase goes unnoticed.' },
      { term: 'Shut-off / disconnection notice', plain: 'A written warning that service will end on a date.', watchOut: 'A phone call threatening shut-off in the next hour. Real notices are in writing.' },
      { term: 'Moratorium', plain: 'A period when utilities cannot disconnect, often winter or extreme heat.', watchOut: 'Not knowing it exists when you need it most.' },
      { term: 'Budget billing', plain: 'A flat monthly payment averaged over the year.', watchOut: 'A big "settle-up" bill at the end of the year that you did not expect.' },
      { term: 'Lifeline', plain: 'A federal discount on phone or internet service.', watchOut: 'Anyone charging a fee to sign you up for a free government program.' },
      { term: 'LIHEAP', plain: 'Federal help paying heating and cooling bills.', watchOut: 'A "consultant" taking a cut of your benefit.' },
    ],
    steps: [
      'When you move, set up accounts in your own name, with your own address and contact details. Never keep an account in someone else\'s name.',
      'Ask each provider: is a deposit required, how much, what is the payment plan option, and is there a low-income rate?',
      'Turn on autopay or set a monthly reminder, and check the first three bills carefully for charges you did not expect.',
      'If you cannot pay, call before the due date and ask for a payment plan or hardship program in writing.',
      'Apply for LIHEAP, Lifeline and any state or utility hardship funds — free applications, no broker needed.',
      'Save your account numbers in your phone and on paper. When someone calls demanding payment, you will need the real number to call back.',
      'If a caller threatens immediate shut-off: hang up, look up your utility\'s number yourself, and report it to the FTC.',
    ],
    traps: [
      'Paying a "reconnection fee" by gift card or app to someone who called you.',
      'Keeping an account in a former roommate\'s or partner\'s name, so the debt and the shut-off risk are not yours to control.',
      'Paying a broker to enroll you in LIHEAP or Lifeline. These programs are free.',
      'Ignoring a shut-off notice out of embarrassment, until the fee and deposit both double.',
      'Giving a utility "verification" caller your SSN over the phone because the caller ID looked right. Caller ID is trivially faked.',
      'Using a prepaid debit card from a store to pay any bill, ever. That is the scam payment rail.',
      'Not reading the first bills, then discovering an "equipment rental" or "administrative" charge every month.',
    ],
    questionsToAsk: [
      'What is my account number, and what is the total due to start service?',
      'Is there a low-income rate or a payment plan I qualify for?',
      'What is the process and the notice period before disconnection in this state?',
      'Is there a seasonal moratorium that protects me right now?',
      'How do I enroll in LIHEAP or Lifeline through the official program?',
    ],
    officialLinks: [
      { name: 'LIHEAP — Federal energy bill assistance', url: 'https://www.acf.hhs.gov/ocs/programs/liheap' },
      { name: 'FCC — Lifeline program', url: 'https://www.lifelinesupport.org/' },
      { name: 'FTC — Utility scams', url: 'https://consumer.ftc.gov/articles/utility-scams' },
      { name: '211 — Local help', url: 'https://www.211.org/' },
    ],
    relatedScamIds: ['utility-shutoff', 'gov-impersonation', 'bank-impersonation'],
  },

  {
    id: 'topic-roommates-sublease',
    slug: 'roommates-and-sublets',
    title: 'Roommates and sublets: the informal housing that costs people the most',
    category: 'home',
    oneLiner:
      'If your name is not on the lease, you have almost no housing rights — and if it is on the lease, you are responsible for the whole rent, not just your share.',
    whyItMatters:
      'New arrivals often start in a room rented from a friend of a friend, with cash, no lease, and no receipts. That is the arrangement where people get robbed, evicted without process, or left holding a debt they never agreed to. A few documents turn an informal arrangement into a safe one.',
    keywords: [
      'roommate', 'sublet', 'sublease', 'rent a room', 'shared apartment',
      'cash rent', 'no lease', 'craigslist room', 'lease agreement with roommates',
      'joint and several liability', 'kick out roommate',
    ],
    explain: [
      'Two words explain the main danger: joint and several liability. When several people sign one lease, the landlord can usually collect the entire rent from any one of them. If your roommate stops paying, you owe their share, and their missed payment becomes your eviction record. That is why the decision to sign a lease with someone is a financial decision about them, not just a living arrangement.',
      'The second danger is being invisible. If you sublet a room from a tenant without the landlord\'s written approval, you can be removed even after paying in full. If you have no written agreement, you cannot prove what you paid, when your notice period is, or what the rules are. Cash rent with no receipts is how people end up paying twice for the same month, or accused of not paying at all.',
      'The fix is small and cheap: a one-page written roommate agreement (rent share, due date, deposits, who pays which utility, guest rules, notice period to leave, and what happens if someone stops paying), the landlord\'s written approval for any sublet, and a rule that rent moves through a bank transfer or a written receipt. If you are the tenant taking in a roommate, put the same things in writing — it protects you too.',
      'And if the relationship sours, do not self-help. Changing the locks, throwing belongings outside, or withholding a roommate\'s money can make you the defendant. Landlords and courts handle removal; you document and ask. If you are worried about your safety, contact a domestic violence or legal aid organization — many states have expedited lease-termination protections for survivors, which is a legal protection most people do not know they have.',
    ],
    facts: [
      {
        id: 'f-joint-liability',
        claim: 'When multiple tenants sign a single lease, most leases make them jointly and severally liable, meaning the landlord may collect the full rent from any one of them.',
        asOf: '2026-09',
        source: { name: 'HUD — Tenant rights', url: 'https://www.hud.gov/topics/rental_assistance/tenantrights' },
        volatility: 'stable',
      },
      {
        id: 'f-sublet-approval',
        claim: 'Subletting without the landlord\'s written consent usually violates the lease, and a subtenant without a written agreement with the head tenant can be removed with little process.',
        asOf: '2026-09',
        source: { name: 'HUD — Tenant rights', url: 'https://www.hud.gov/topics/rental_assistance/tenantrights' },
        volatility: 'stable',
      },
      {
        id: 'f-dv-protections',
        claim: 'Many states allow survivors of domestic violence, sexual assault or stalking to terminate a lease early without penalty, usually with written notice and documentation.',
        detail:
          'Rules and documentation requirements differ by state. Local legal aid or a domestic violence hotline can explain exactly what your state requires.',
        asOf: '2026-09',
        source: { name: 'USA.gov — Housing help', url: 'https://www.usa.gov/housing-help' },
        volatility: 'annual',
      },
      {
        id: 'f-roommate-agreement',
        claim: 'A written roommate agreement documenting each person\'s rent share, deposit contribution, utility responsibility and notice period is the standard way to avoid disputes the lease does not cover.',
        asOf: '2026-09',
        source: { name: 'Consumer Financial Protection Bureau — Renters', url: 'https://www.consumerfinance.gov/consumer-tools/' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'Joint and several liability', plain: 'Each signer can be held responsible for the entire rent.', watchOut: 'Signing with a roommate who has less to lose than you do.' },
      { term: 'Head tenant', plain: 'The person whose name is on the lease who takes in a roommate.', watchOut: 'A head tenant who disappears with everyone\'s share.' },
      { term: 'Subtenant', plain: 'You, if you rent from a tenant rather than the owner.', watchOut: 'No written approval from the landlord.' },
      { term: 'Notice period', plain: 'How much warning you must give before leaving.', watchOut: 'A "month to month" arrangement with no written notice rule.' },
      { term: 'Security deposit share', plain: 'What portion of the deposit is yours.', watchOut: 'Paying a deposit to a roommate who never passes it to the landlord, then losing it.' },
      { term: 'Squatter', plain: 'Someone occupying without any agreement.', watchOut: 'Letting a guest move in permanently with no agreement — removal becomes a court process.' },
      { term: 'Lease takeover / assignment', plain: 'Taking over the whole lease with the landlord\'s approval.', watchOut: 'Doing this verbally and discovering later you were never added to the lease.' },
    ],
    steps: [
      'Before moving in, meet the people and see the actual unit. If you cannot, do not send money.',
      'Ask to see the lease and confirm your name or your written sublet arrangement with the landlord.',
      'Get landlord approval in writing for any sublet, even if the head tenant says it is fine.',
      'Sign a one-page roommate agreement: rent share, due date, deposit, utilities, guests, notice to leave, and who is responsible if someone stops paying.',
      'Pay rent by bank transfer or against a written receipt. Never pay cash with no record.',
      'Keep your own copy of everything: lease, sublet approval, agreement, receipts, and photos of the room\'s condition when you moved in.',
      'If there is a conflict, put your position in writing, ask for what you want in writing, and get legal aid involved before doing anything physical with locks or belongings.',
    ],
    traps: [
      'Paying cash to a roommate who then claims you never paid.',
      'Signing a lease with someone you barely know and discovering what joint liability means when they leave.',
      'Renting a room from a "head tenant" with no landlord approval, then being removed with two days\' notice.',
      'Letting someone stay "temporarily" for months without a written agreement, then being unable to remove them.',
      'Changing the locks or moving a roommate\'s belongings to force them out. That is an illegal self-help eviction and can make you liable.',
      'Handling an abusive situation alone because you do not know your state lets survivors end a lease early.',
      'Not photographing the room, then being charged for damage caused by the previous occupant.',
    ],
    questionsToAsk: [
      'Whose name is on the lease, and can I see it?',
      'Does the landlord know about and approve this arrangement, and can I have that in writing?',
      'How much is my share, when is it due, and how will I prove I paid?',
      'If a roommate stops paying, what is my responsibility under the lease?',
      'What is the notice period if I need to leave?',
    ],
    officialLinks: [
      { name: 'HUD — Tenant rights', url: 'https://www.hud.gov/topics/rental_assistance/tenantrights' },
      { name: 'USA.gov — Housing help', url: 'https://www.usa.gov/housing-help' },
      { name: 'FTC — Rental listing scams', url: 'https://consumer.ftc.gov/articles/rental-listing-scams' },
      { name: 'USA.gov — Legal aid', url: 'https://www.usa.gov/legal-aid' },
    ],
    relatedScamIds: ['rental-listing', 'landlord-cash', 'deposit-scam'],
  },
]
