import type { Topic } from '../types'

export const moneyTopics: Topic[] = [
  {
    id: 'topic-bank-account',
    slug: 'open-a-bank-account',
    title: 'Opening a bank account (and why cash under the mattress costs you)',
    category: 'money',
    oneLiner:
      'A checking account is the backbone of American life: rent, paychecks, credit history and proof of address all flow through it. You do not need an SSN or a credit score to open one.',
    whyItMatters:
      'Immigrants who keep cash lose it to theft and to fees for money orders, cannot build credit, and cannot prove income or address when a landlord asks. Cashing a paycheck at a check-cashing store can cost a meaningful percentage of your pay every single time.',
    keywords: [
      'bank account', 'checking account', 'no ssn bank', 'itin bank account',
      'open account', 'direct deposit', 'debit card', 'overdraft', 'fees',
      'second chance account', 'cash paycheck', 'unbanked',
    ],
    explain: [
      'Banks in the US are generally required to verify your identity, not your immigration status. In practice that means many banks accept a foreign passport, a consular ID, an ITIN, or a combination of documents. Individual bank policies differ, so the skill is: ask a specific branch what it needs from someone in your situation, and if the answer is no, ask another bank. Credit unions, especially community and immigrant-serving ones, are often more flexible than big national banks.',
      'Once you have an account, set up direct deposit if you have a job and can be paid that way. It is faster, it creates a paper trail of income, and some banks drop monthly fees for it. Then read one document: the fee schedule. The fees that hurt immigrants most are monthly maintenance fees, overdraft fees and minimum balance requirements. Ask for the "no-fee if you do X" version in writing.',
      'Treat your account as something that must never be shared. In the US, money you deposit and move can be traced to you personally. That is why "receive this money and send it on for me" job offers are not a job — see the money mule topic. No legitimate employer, landlord, government agency or charity ever sends you money and asks you to forward it.',
    ],
    facts: [
      {
        id: 'f-bank-no-ssn',
        claim: 'A Social Security number is not universally required to open a US bank account; institutions set their own identification requirements within federal customer-identification rules, and many accept a passport, consular ID, or ITIN.',
        asOf: '2026-09',
        source: { name: 'FDIC — Consumer Resource Center', url: 'https://www.fdic.gov/consumer-resource-center' },
        volatility: 'stable',
      },
      {
        id: 'f-bank-id-rule',
        claim: 'Under the Customer Identification Program rule, banks must collect identifying information such as name, date of birth, address and an identification number, and must verify identity.',
        asOf: '2026-09',
        source: { name: 'FDIC — Bank Secrecy Act / Customer Identification Program', url: 'https://www.fdic.gov/regulations/examinations/bsa.html' },
        volatility: 'stable',
      },
      {
        id: 'f-direct-deposit',
        claim: 'Direct deposit of wages is normal and free, and wages must generally be paid by a method that does not cost the employee money to access.',
        asOf: '2026-09',
        source: { name: 'US Department of Labor — Payroll and wage payment', url: 'https://www.dol.gov/agencies/whd/faqs' },
        volatility: 'stable',
      },
      {
        id: 'f-overdraft',
        claim: 'Banks generally must get your consent before charging overdraft fees on ATM and debit card transactions, and you can withdraw that consent to avoid those fees.',
        asOf: '2026-09',
        source: { name: 'Consumer Financial Protection Bureau — Overdraft fees', url: 'https://www.consumerfinance.gov/consumer-tools/bank-accounts/' },
        volatility: 'annual',
      },
      {
        id: 'f-bankon',
        claim: 'Bank On certified accounts are designed for people with no banking history or past account problems, with low or no fees and no overdraft charges.',
        asOf: '2026-09',
        source: { name: 'Cities for Financial Empowerment Fund — Bank On', url: 'https://joinbankon.org/' },
        volatility: 'annual',
      },
      {
        id: 'f-fdic-insurance',
        claim: 'Deposits at an FDIC-insured bank are insured up to $250,000 per depositor, per bank, for each ownership category. Credit unions have equivalent NCUA insurance.',
        asOf: '2026-09',
        source: { name: 'FDIC — Deposit Insurance FAQ', url: 'https://www.fdic.gov/resources/deposit-insurance/' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'Checking account', plain: 'The account you spend from day to day.', watchOut: 'A monthly "maintenance fee" that you can usually avoid by meeting one condition.' },
      { term: 'Savings account', plain: 'An account for holding money, slightly better interest, less convenient.', watchOut: 'Aggressive savings products paying far above market rates, sold by strangers on social media.' },
      { term: 'Overdraft', plain: 'The bank pays a purchase you cannot cover and charges you a fee for it.', watchOut: 'Opting in by default, then paying $35 for a $4 coffee.' },
      { term: 'Routing and account number', plain: 'The two numbers that let people deposit or withdraw money from your account.', watchOut: 'Anyone asking for these over chat, "to send your paycheck".' },
      { term: 'Check-cashing store', plain: 'A shop that cashes your paycheck for a percentage fee.', watchOut: 'Losing 1–5% of every paycheck forever, plus no record of income.' },
      { term: 'Second chance account', plain: 'An account for people who had an account closed or a negative record (like ChexSystems).', watchOut: 'Paying a large "enrollment" fee. Bank On certified accounts are low-cost by design.' },
      { term: 'Zelle / Cash App / Venmo', plain: 'Fast payment apps that move money between people.', watchOut: 'They have far fewer fraud protections than credit cards. Treat them like handing over cash.' },
    ],
    steps: [
      'Bring: passport (and visa/I-94 if you have it), ITIN or SSN if you have one, proof of address (lease, utility bill, or a letter), and your phone number.',
      'Ask two or three institutions — a community credit union, a minority/immigrant-serving bank, and a large bank — what a person with your documents needs. Compare in writing.',
      'Open a checking account and, if the bank requires a minimum balance to avoid fees, choose the option you can actually maintain.',
      'Ask them to turn OFF overdraft coverage on debit card purchases, so a small purchase is simply declined rather than costing you a fee.',
      'Set up direct deposit, then set one automatic transfer to savings on payday — even $20. It is the beginning of your "I can say no" fund.',
      'Turn on account alerts for every transaction over a small amount. Text alerts catch fraud fast.',
      'Never share your routing number, account number, PIN or one-time codes with anyone who contacted you first.',
    ],
    traps: [
      'Letting a check-cashing store take a cut of every paycheck for years instead of opening an account.',
      'Paying a fee to a "banking consultant" to open an account you can open yourself.',
      'Opting into overdraft "protection" and treating the fee as normal.',
      'Depositing a check from a stranger and forwarding part of it. That is the money-mule scheme and it is a crime you can be prosecuted for.',
      'Using a friend\'s account to receive your wages "just for now". The money is legally theirs and you have no proof.',
      'Keeping your whole savings in a payment app instead of an insured bank or credit union account.',
      'Ignoring an account closure notice; a negative record can lock you out of banking for years.',
    ],
    questionsToAsk: [
      'What documents do you accept from someone with my immigration status?',
      'What are all the monthly fees, and what exactly do I need to do to avoid each one?',
      'Can I turn off overdraft coverage on debit purchases today?',
      'Is this account FDIC or NCUA insured?',
      'Is there a minimum balance, and what happens if I go below it?',
    ],
    officialLinks: [
      { name: 'CFPB — Bank accounts and services', url: 'https://www.consumerfinance.gov/consumer-tools/bank-accounts/' },
      { name: 'FDIC — Consumer Resource Center', url: 'https://www.fdic.gov/consumer-resource-center' },
      { name: 'Bank On — certified accounts', url: 'https://joinbankon.org/' },
      { name: 'NCUA — Share insurance', url: 'https://www.ncua.gov/consumers/share-insurance-credit-unions' },
    ],
    relatedScamIds: ['money-mule', 'fake-check', 'bank-impersonation'],
  },

  {
    id: 'topic-credit-score',
    slug: 'build-credit-from-zero',
    title: 'Building credit from absolutely nothing',
    category: 'money',
    oneLiner:
      'A credit score is a number lenders use to predict whether you will repay. Immigrants start with an empty file, which is different from a bad file — and an empty file can be built in about six months.',
    whyItMatters:
      'In the US, credit decides your apartment application, your car loan interest rate, your car insurance price, sometimes your job, and your ability to get a phone plan without a deposit. Most countries do not work this way, which is why newcomers are blindsided. Worse, everyone offering to "fix" your credit knows you do not know the rules.',
    keywords: [
      'credit score', 'credit history', 'fico', 'build credit', 'no credit',
      'secured card', 'credit card', 'credit limit', 'utilization', 'credit karma',
      'how to get credit', 'apartment rejected my credit',
    ],
    explain: [
      'Your US credit file is built from accounts and payment history reported by lenders. If you have never borrowed here, the file is thin or empty, and a landlord sees "no history" — which many interpret as risk. There is no trick to fixing this. There is only: get one small account, use it, and pay it on time, every time.',
      'The standard ladder is: (1) a secured credit card — you deposit a few hundred dollars and get a card with a limit near your deposit; (2) use it for something small and predictable, like a phone bill or groceries; (3) pay the full balance before the due date, not the minimum; (4) after six to twelve months of on-time payments, apply for an unsecured card. Some banks and credit unions let newcomers start with a "credit builder" loan or a card linked to a checking account with no credit check at all.',
      'The scoring factors that matter most are payment history (never pay late) and how much of your limit you use (keep it low — under about 30%, and lower is better). Length of history matters, so do not close your first card once you get a better one; keep it open with a small recurring charge. Then protect the whole thing: repayment history is only useful if nobody else is borrowing in your name.',
    ],
    facts: [
      {
        id: 'f-uti-30',
        claim: 'Credit utilization — the share of your available credit you use — is a major scoring factor, and borrowers are commonly advised to keep it under about 30% of the limit.',
        asOf: '2026-09',
        source: { name: 'Consumer Financial Protection Bureau — How to build credit', url: 'https://www.consumerfinance.gov/consumer-tools/credit-reports-and-scores/' },
        volatility: 'stable',
      },
      {
        id: 'f-secured-card',
        claim: 'A secured credit card requires a refundable security deposit and reports to credit bureaus like a normal card, making it the standard starting point for someone with no US credit history.',
        asOf: '2026-09',
        source: { name: 'Consumer Financial Protection Bureau — Secured credit cards', url: 'https://www.consumerfinance.gov/ask-cfpb/what-is-a-secured-credit-card-en-1371/' },
        volatility: 'stable',
      },
      {
        id: 'f-free-reports',
        claim: 'You can get free credit reports from each of the three national bureaus through AnnualCreditReport.com, and checking your own report does not lower your score.',
        asOf: '2026-09',
        source: { name: 'Consumer Financial Protection Bureau — Free credit reports', url: 'https://www.consumerfinance.gov/consumer-tools/credit-reports-and-scores/' },
        volatility: 'stable',
      },
      {
        id: 'f-credit-repair-orgs',
        claim: 'Credit repair organizations may not charge you before they perform services, and no one can lawfully remove accurate negative information from your credit report.',
        asOf: '2026-09',
        source: { name: 'FTC — Credit repair: how to help yourself', url: 'https://consumer.ftc.gov/articles/credit-repair-how-help-yourself' },
        volatility: 'stable',
      },
      {
        id: 'f-thin-file',
        claim: 'Having no credit history at all produces either no score or a score that lenders treat cautiously, which is why some landlords and lenders accept alternative proof such as rental payment history, utility payments, or a co-signer.',
        asOf: '2026-09',
        source: { name: 'Consumer Financial Protection Bureau — Credit reports and scores', url: 'https://www.consumerfinance.gov/consumer-tools/credit-reports-and-scores/' },
        volatility: 'stable',
      },
      {
        id: 'f-no-credit-file-loan',
        claim: 'Credit-builder loans and cards from community banks and credit unions are designed for people without a US credit file and often do not require a credit check.',
        asOf: '2026-09',
        source: { name: 'FDIC — Money Smart financial education', url: 'https://www.fdic.gov/consumer-resource-center/money-smart' },
        volatility: 'annual',
      },
    ],
    jargon: [
      { term: 'Credit score / FICO', plain: 'A number, roughly 300–850, predicting repayment risk. Higher is better.', watchOut: 'Paying for a score you can get free through your bank or a bureau.' },
      { term: 'Secured card', plain: 'A credit card backed by a cash deposit you make.', watchOut: 'Cards with huge annual fees targeted at people with no credit.' },
      { term: 'Utilization', plain: 'How much of your limit you are using. Keep it low.', watchOut: 'Maxing a $300 card every month and wondering why the score does not move.' },
      { term: 'Hard inquiry', plain: 'A credit check when you apply for credit. Too many hurt slightly.', watchOut: '"Pre-approved" offers that actually run a hard check and cost you points.' },
      { term: 'Authorized user', plain: 'Being added to someone else\'s card to inherit their history.', watchOut: 'Paying a stranger to "rent" their credit history — that is fraud.' },
      { term: 'Charge-off', plain: 'A debt the lender gave up on. Serious negative mark.', watchOut: 'Paying a "debt fixer" who promises to erase it.' },
      { term: 'Credit repair', plain: 'Disputing genuine errors on your report, which you can do yourself for free.', watchOut: 'Companies charging monthly fees and mailing dispute letters you could have mailed.' },
    ],
    steps: [
      'Pull your free reports at AnnualCreditReport.com first. Sometimes you already have a file you do not know about, including from a bank account or a store card.',
      'Open a secured credit card or a credit-builder account at a credit union. Deposit the smallest amount that gives you a usable limit.',
      'Put ONE recurring small charge on it — a phone bill is ideal — and turn on autopay for the full statement balance.',
      'Never use more than about 30% of the limit, and never pay late. One 30-day late payment can sit on your file for years.',
      'After 6–12 months, ask the issuer to upgrade to an unsecured card or apply for a second card. Keep the first card open.',
      'Freeze your credit at all three bureaus when you are not applying for anything, so nobody builds a file in your name while you build yours.',
    ],
    timeline: [
      { when: 'Month 0', what: 'Check reports. Open a secured card or credit-builder account.' },
      { when: 'Month 1–6', what: 'One small charge per month, paid in full. Do not apply for anything else.' },
      { when: 'Month 6–12', what: 'Expect a score to appear. Ask about upgrading to unsecured.' },
      { when: 'Month 12+', what: 'Add a second product only if you can pay it in full. Keep old accounts open.' },
      { when: 'Ongoing', what: 'Freeze credit when not applying. Check reports every few months.' },
    ],
    traps: [
      'Paying a "credit repair" company an upfront fee. It is illegal for them to charge before performing services, and nobody can remove accurate history.',
      'Believing you need to borrow money to have credit, then taking a high-interest loan you do not need.',
      'Closing your oldest card and shortening your history.',
      'Being added as an authorized user on a stranger\'s card for a fee.',
      'Using a debit card and expecting it to build credit. It does not.',
      'Co-signing a loan for a friend or a "business partner". If they stop paying, the debt is yours and the damage is on your file.',
      'Ignoring a collections notice and letting it age from a small problem into a rejected apartment application.',
    ],
    questionsToAsk: [
      'Does this card report to all three credit bureaus?',
      'What is the annual fee, and is there a no-fee version I qualify for?',
      'Do you run a credit check for this product, and is it a hard inquiry?',
      'Can I upgrade this secured card to an unsecured card later, and when?',
      'Can I drop my deposit after a period of on-time payments?',
    ],
    officialLinks: [
      { name: 'CFPB — Credit reports and scores', url: 'https://www.consumerfinance.gov/consumer-tools/credit-reports-and-scores/' },
      { name: 'AnnualCreditReport.com', url: 'https://www.annualcreditreport.com/' },
      { name: 'FTC — Credit repair: how to help yourself', url: 'https://consumer.ftc.gov/articles/credit-repair-how-help-yourself' },
      { name: 'FTC — Free credit freezes', url: 'https://consumer.ftc.gov/articles/place-security-freeze-your-credit-file' },
    ],
    relatedScamIds: ['credit-repair-scam', 'identity-theft', 'advance-fee-loan'],
  },

  {
    id: 'topic-taxes-basics',
    slug: 'taxes-for-immigrants',
    title: 'Taxes for immigrants: more reasons to file than to skip',
    category: 'money',
    oneLiner:
      'The US taxes your worldwide income if you are a resident for tax purposes, filing is how you claim money back, and a filed return is often the only official proof that you earned what you earned.',
    whyItMatters:
      'People who work "off the books" to stay under the radar end up unable to prove income for an apartment, a loan, or an immigration case, and they lose refundable credits worth thousands. Meanwhile, missing foreign-account and foreign-gift reporting requirements can produce penalties far larger than the tax.',
    keywords: [
      'taxes', 'tax return', 'w-2', '1040', 'tax refund', 'w-4', 'withholding',
      'itin taxes', 'file taxes without ssn', 'tax deadline', '1040-nr',
      'fbar', 'foreign account', 'tax credits', 'child tax credit', 'vita',
    ],
    explain: [
      'Most employees have tax withheld from every paycheck. Filing a return compares what was withheld with what you actually owe, and often gets you a refund — which is why skipping filing usually means giving the government your own money. Anyone with a filing obligation can file using an SSN or an ITIN, regardless of immigration status: the IRS is a tax agency, not an immigration agency.',
      'The form you use depends on your tax residency, which is not the same as your immigration status. If you are a "resident alien" for tax purposes you file Form 1040 like a citizen and can claim credits like the Earned Income Tax Credit or the Child Tax Credit. If you are a "nonresident alien" you generally file Form 1040-NR, and many credits are unavailable. This one distinction is the most expensive thing to get wrong, and it is why you should not just copy a friend\'s return.',
      'Then there is the layer almost nobody explains to newcomers: if you still have bank accounts or investments in your home country, or you receive a large gift or inheritance from abroad, there are separate reporting forms with their own thresholds — and their own penalties. If you own or sign on a foreign account, ask a tax professional about FBAR and Form 8938 before the deadline, not after. Free help exists: the IRS-run VITA program prepares returns for free for people under income limits, and many immigrant organizations have tax clinics.',
    ],
    facts: [
      {
        id: 'f-tax-deadline',
        claim: 'The federal individual income tax return deadline is generally April 15, with automatic extensions available to October 15 if you request one by the April deadline.',
        detail:
          'An extension to file is not an extension to pay. If you owe, interest and penalties accrue from April even if you filed late.',
        asOf: '2026-09',
        source: { name: 'IRS — Filing season and due dates', url: 'https://www.irs.gov/filing' },
        volatility: 'annual',
      },
      {
        id: 'f-tax-residency',
        claim: 'For tax purposes you are either a resident alien or a nonresident alien, decided by tests based on your presence and status — not by your immigration status.',
        detail:
          'Resident aliens file Form 1040 and can qualify for many credits. Nonresident aliens generally file Form 1040-NR.',
        asOf: '2026-09',
        source: { name: 'IRS — Publication 519, U.S. Tax Guide for Aliens', url: 'https://www.irs.gov/publications/p519' },
        volatility: 'stable',
      },
      {
        id: 'f-tax-withholding',
        claim: 'Form W-4 tells your employer how much tax to withhold from each paycheck; getting it wrong can mean a surprise bill or an interest-free loan to the government.',
        asOf: '2026-09',
        source: { name: 'IRS — Tax Withholding Estimator', url: 'https://www.irs.gov/individuals/tax-withholding-estimator' },
        volatility: 'annual',
      },
      {
        id: 'f-vita',
        claim: 'The IRS VITA and TCE programs prepare tax returns for free for people who qualify by income and age, and for people with limited English.',
        asOf: '2026-09',
        source: { name: 'IRS — Free tax return preparation', url: 'https://www.irs.gov/individuals/free-tax-return-preparation-for-you-by-volunteers' },
        volatility: 'annual',
      },
      {
        id: 'f-fbar',
        claim: 'US persons with a financial interest in or signature authority over foreign financial accounts exceeding $10,000 in aggregate at any point in the year generally must file an FBAR (FinCEN Report 114).',
        detail:
          'This catches newcomers with home-country accounts. Penalties for non-willful failures are still expensive, and willful ones are severe. Get advice the first year you are unsure.',
        asOf: '2026-09',
        source: { name: 'IRS — Report of Foreign Bank and Financial Accounts (FBAR)', url: 'https://www.irs.gov/businesses/small-businesses-self-employed/report-of-foreign-bank-and-financial-accounts-fbar' },
        volatility: 'annual',
        alsoCheck: [
          { name: 'FinCEN — FBAR filing (BSA E-Filing)', url: 'https://bsaefiling.fincen.gov/' },
        ],
      },
      {
        id: 'f-foreign-gifts',
        claim: 'Receiving certain large gifts or inheritances from a foreign person may require filing Form 3520, even though no tax is owed.',
        asOf: '2026-09',
        source: { name: 'IRS — About Form 3520', url: 'https://www.irs.gov/forms-pubs/about-form-3520' },
        volatility: 'annual',
      },
      {
        id: 'f-tax-scam',
        claim: 'The IRS does not demand immediate payment by gift card, cryptocurrency, wire transfer or payment app, and does not threaten arrest by phone for a tax bill.',
        asOf: '2026-09',
        source: { name: 'FTC — IRS impersonation scams', url: 'https://consumer.ftc.gov/features/scams' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'W-2', plain: 'The form your employer sends you each January showing what you were paid and what was withheld.', watchOut: 'An employer who will not give you one — that is a wage and tax problem you should document.' },
      { term: '1099', plain: 'A form for money paid to you without withholding, used by gig and contract workers.', watchOut: 'Being called a "contractor" so the employer avoids payroll taxes while controlling your schedule.' },
      { term: 'Withholding', plain: 'Tax taken out of each paycheck in advance.', watchOut: 'A job paying all cash with no withholding and no record — you lose refunds and proof of income.' },
      { term: 'Refundable credit', plain: 'A credit that can pay you money back even if you owed no tax.', watchOut: 'A preparer who claims credits you do not qualify for. You are responsible for your return.' },
      { term: '1040-NR', plain: 'The return for nonresident aliens, with fewer credits.', watchOut: 'Filing 1040 when you are a nonresident alien and losing the case later.' },
      { term: 'ITIN filer', plain: 'Someone filing with a tax ID instead of an SSN. It is normal and legal.', watchOut: 'A preparer telling you it is not allowed, then charging extra.' },
      { term: 'FBAR', plain: 'A separate report of foreign bank accounts, filed with FinCEN, not the IRS.', watchOut: '"Nobody declares those" — the penalty is per-account, per-year, and it is real.' },
      { term: 'Preparer', plain: 'Anyone who helps you file, from a free clinic to an accountant.', watchOut: 'Unlicensed "tax preparers" who promise huge refunds and charge a percentage.' },
    ],
    steps: [
      'Collect every W-2, 1099 and interest statement from the year. If an employer refuses to give a W-2, get advice — you may still need to report the income.',
      'Decide your tax residency, or better: let a free VITA clinic or a professional decide it with you the first time, and learn the rule.',
      'File. If you cannot get an SSN, get an ITIN with Form W-7 and file with it — do not skip filing because you lack a number.',
      'Check whether you have foreign accounts, foreign income, or a large foreign gift or inheritance, and ask specifically about FBAR, Form 8938 and Form 3520.',
      'Keep a copy of every return and every notice forever. These are financial proof of income for apartments, loans and immigration cases.',
      'For next year: revisit your W-4 so withholding matches reality, and set up an automatic transfer to savings for the year ahead.',
    ],
    timeline: [
      { when: 'January–February', what: 'W-2s and 1099s arrive. Start collecting documents; do not file yet if a 1099 is missing.' },
      { when: 'Through April 15', what: 'File. Book a free VITA appointment early — slots fill quickly.' },
      { when: 'April 15', what: 'Deadline to file and to pay what you owe. Request an extension if needed.' },
      { when: 'Every April for ITIN holders', what: 'Renew an expired ITIN with Form W-7 alongside your return.' },
      { when: 'When you move or your income changes', what: 'Update your address with the IRS and adjust your W-4.' },
    ],
    traps: [
      'Not filing because you do not have an SSN. An ITIN solves that.',
      'Working entirely off the books and later being unable to prove income for a lease, loan or immigration case.',
      'Using a "tax preparer" who invents dependents or credits. You sign the return, you carry the penalty.',
      'Forgetting foreign accounts or foreign income entirely. This is the most common expensive mistake for newcomers.',
      'Paying a percentage of your refund to a preparer instead of a flat fee.',
      'Ignoring an IRS letter. Most IRS notices are fixable in a phone call or a letter — silence is what makes them expensive.',
      'Filing a joint return with an expired ITIN and having the whole refund frozen until the ITIN is renewed.',
      'Assuming your tax return and your immigration case are separate systems. In practice, tax records become evidence about you.',
    ],
    questionsToAsk: [
      'Am I a resident alien or a nonresident alien for tax purposes this year, and what makes that true?',
      'Do I have a filing requirement for foreign accounts, foreign gifts or foreign income?',
      'Will you sign the return as the preparer, and what is your PTIN or credential?',
      'Is this fee flat, and does it include the state return?',
      'Can you explain this credit in a way I can repeat to someone else?',
    ],
    officialLinks: [
      { name: 'IRS — Free tax return preparation (VITA/TCE)', url: 'https://www.irs.gov/individuals/free-tax-return-preparation-for-you-by-volunteers' },
      { name: 'IRS — Publication 519, U.S. Tax Guide for Aliens', url: 'https://www.irs.gov/publications/p519' },
      { name: 'IRS — Report of Foreign Bank and Financial Accounts (FBAR)', url: 'https://www.irs.gov/businesses/small-businesses-self-employed/report-of-foreign-bank-and-financial-accounts-fbar' },
      { name: 'IRS — Taxpayer Advocate Service', url: 'https://www.taxpayeradvocate.irs.gov/' },
      { name: 'IRS — Where is my refund?', url: 'https://www.irs.gov/wheres-my-refund' },
    ],
    relatedScamIds: ['irs-impersonation', 'tax-prep-fraud', 'notario-fraud'],
  },

  {
    id: 'topic-remittances',
    slug: 'send-money-home',
    title: 'Sending money home without losing 8% of it',
    category: 'money',
    oneLiner:
      'Sending money abroad has three costs — the transfer fee, the exchange rate markup, and the time it takes — and the exchange rate markup is usually the biggest and least visible.',
    whyItMatters:
      'Remittances are often a family\'s largest recurring expense. Small percentage differences compound into hundreds of dollars a year, and informal "hand-carry" and hawala-style arrangements leave no legal record and no recourse when they fail.',
    keywords: [
      'send money home', 'remittance', 'transfer', 'wire', 'exchange rate',
      'western union', 'remitly', 'wise', 'fees', 'money order', 'family support',
    ],
    explain: [
      'Most transfer services advertise a low or zero fee and earn their money on the exchange rate. That means the advertised fee tells you almost nothing. The honest comparison is: how many units of the destination currency does my family actually receive, in total, after all costs? Compare that number across providers on the same day and the ranking is often surprising.',
      'The second thing to control is the record. Sending through a regulated service gives you a receipt, a transaction number, and a complaint channel. Sending cash with a friend or through an informal network gives you nothing — no proof of payment, no recourse, and a possible question at tax time about where your money went.',
      'Regulated remittance transfers also come with legal protections. Under the CFPB\'s remittance rule, providers must generally give you a disclosure showing the exchange rate, the fees, and the amount your recipient will get, and you have error-resolution rights. If a provider will not put those numbers in writing, that is the whole answer.',
    ],
    facts: [
      {
        id: 'f-remittance-disclosure',
        claim: 'Under the CFPB remittance rule, covered providers must give you a written receipt showing the exchange rate, fees and the amount to be received, and you have a right to resolve errors within specified periods.',
        asOf: '2026-09',
        source: { name: 'Consumer Financial Protection Bureau — Remittance transfers', url: 'https://www.consumerfinance.gov/consumer-tools/sending-money/' },
        volatility: 'annual',
      },
      {
        id: 'f-remittance-cancel',
        claim: 'For covered transfers, you generally have at least 30 minutes after payment to cancel and get a full refund, and error resolution rights that can extend to 180 days for certain problems.',
        asOf: '2026-09',
        source: { name: 'CFPB — Remittance transfer rule (Regulation E subpart B)', url: 'https://www.consumerfinance.gov/rules-policy/regulations/1005/' },
        volatility: 'annual',
      },
      {
        id: 'f-remittance-compare',
        claim: 'The World Bank tracks the cost of sending remittances and publishes global averages and corridor-specific costs, which makes it possible to see whether your provider is expensive.',
        asOf: '2026-09',
        source: { name: 'World Bank — Remittance Prices Worldwide', url: 'https://remittanceprices.worldbank.org/' },
        volatility: 'annual',
      },
      {
        id: 'f-money-transmitter-license',
        claim: 'Money transmitters must be licensed and registered, and you can check a provider\'s registration with FinCEN\'s MSB registration search or your state financial regulator.',
        asOf: '2026-09',
        source: { name: 'FinCEN — Money Services Business registrant search', url: 'https://www.fincen.gov/msb-state-selector' },
        volatility: 'stable',
      },
      {
        id: 'f-remittance-scam',
        claim: 'Requests to send money urgently to help a relative in trouble, or to pay a fee to release a prize, immigration benefit or package, are consistently among the most reported frauds.',
        asOf: '2026-09',
        source: { name: 'FTC — Sending money to someone you do not know', url: 'https://consumer.ftc.gov/articles/how-avoid-scam' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'Exchange rate markup', plain: 'The hidden profit a provider makes by giving you a worse rate than the real one.', watchOut: 'A "zero fee" transfer with a bad rate is usually more expensive than a small fee with a good rate.' },
      { term: 'Spread', plain: 'The gap between the real market rate and the rate you are offered.', watchOut: 'Comparing "no fee" offers without comparing the received amount.' },
      { term: 'Correspondent bank fee', plain: 'An extra charge by an intermediary bank on some transfers.', watchOut: 'Wire transfers where the recipient receives less than you expected.' },
      { term: 'MSB registration', plain: 'Money Services Business registration with FinCEN. Legitimate transmitters have one.', watchOut: 'An "agent" who takes cash and promises a transfer with no receipt.' },
      { term: 'Cancel window', plain: 'Your short legal window to cancel a transfer and get your money back.', watchOut: 'Being rushed to send before you can reconsider.' },
      { term: 'Click-to-cancel / refund', plain: 'Your right to a refund if the money was never delivered as disclosed.', watchOut: 'Being told the money is "gone" when the provider failed to deliver.' },
    ],
    steps: [
      'Pick three licensed providers that serve your destination country and compare the total amount received for the same amount sent, on the same day, in one table.',
      'Choose the one that maximizes the received amount, not the one with the lowest advertised fee.',
      'Write down the total you send per month and multiply by twelve. Then look for a cheaper route once, and keep it forever.',
      'Always keep the receipt with the transaction number. Photograph it.',
      'Set a family rule: no money is ever sent to fix an emergency that arrives by text from an unknown number, even if it sounds like your relative. Call the relative on a number you already have.',
      'If a transfer goes wrong, complain to the provider in writing within the legal window, then escalate to the CFPB if unresolved.',
    ],
    traps: [
      'Comparing only the advertised fee and missing the exchange-rate markup.',
      'Sending cash with a friend or an informal courier with no receipt.',
      'Sending money in response to an urgent message that appears to be from a family member — a very common impersonation scheme.',
      'Paying a "release fee" to receive money someone supposedly sent you. Real transfers do not require you to pay to receive.',
      'Using an unregistered agent who operates from a shop or a chat group.',
      'Not telling your family what kinds of calls and messages are scams, so they become the entry point.',
      'Sending from a payment app to a person you do not know. Those transfers are usually not reversible.',
    ],
    questionsToAsk: [
      'Exactly how much will my recipient receive, in their currency, after all fees? Write it on the receipt.',
      'What is the exchange rate you are applying, and what is the market rate today?',
      'Can I cancel within 30 minutes and get a full refund?',
      'What is your FinCEN or state registration number?',
      'What do I do if the money never arrives — what is the complaint process?',
    ],
    officialLinks: [
      { name: 'CFPB — Sending money (remittance transfers)', url: 'https://www.consumerfinance.gov/consumer-tools/sending-money/' },
      { name: 'CFPB — Submit a complaint', url: 'https://www.consumerfinance.gov/complaint/' },
      { name: 'World Bank — Remittance Prices Worldwide', url: 'https://remittanceprices.worldbank.org/' },
      { name: 'FinCEN — MSB registration search', url: 'https://www.fincen.gov/msb-state-selector' },
    ],
    relatedScamIds: ['family-emergency', 'advance-fee-loan', 'romance'],
  },

  {
    id: 'topic-insurance-basics',
    slug: 'insurance-you-actually-need',
    title: 'Insurance: the three kinds you actually need, and the one you are usually overpaying for',
    category: 'money',
    oneLiner:
      'Renters insurance is cheap and prevents a total loss. Auto liability insurance is legally required in almost every state and protects you from a lawsuit. Health insurance is the difference between a $200 bill and a $40,000 one.',
    whyItMatters:
      'In many countries insurance is optional or provided by the state. In the US, an uninsured car accident or a hospital stay can destroy years of savings and follow you into credit and immigration decisions. Insurance sellers also target newcomers with unnecessary products, so knowing the minimums matters as much as buying.',
    keywords: [
      'insurance', 'renters insurance', 'car insurance', 'liability', 'deductible',
      'premium', 'minimum coverage', 'uninsured motorist', 'policy', 'claim',
      'insurance scam', 'life insurance', 'umbrella',
    ],
    explain: [
      'Start with the vocabulary because the words decide how much you pay. A premium is what you pay monthly. A deductible is what you pay yourself before the insurer pays. A limit is the most the insurer will pay. A claim is your request for them to pay. If someone sells you a policy without putting those four numbers in front of you, stop the conversation.',
      'Renters insurance is usually the biggest no-brainer: for a small monthly amount it covers your belongings and, importantly, liability if you accidentally cause damage or injury in your apartment. Many leases require it. Auto liability insurance is legally required in nearly every state, and the state minimum is usually the cheapest legal option — but consider uninsured/underinsured motorist coverage, because a meaningful share of drivers carry no insurance at all, and if they hit you their policy cannot pay you.',
      'The health side is covered separately in this library, but the rule is the same: never go without, understand your deductible and out-of-pocket maximum, and remember that an emergency room visit has a legal protection (the No Surprises Act) against certain surprise bills. And be skeptical of anything sold by a stranger on the phone: legitimate insurers send you documents, take payment through traceable methods, and have a licensing number you can verify with your state insurance department.',
    ],
    facts: [
      {
        id: 'f-auto-required',
        claim: 'Nearly every state requires drivers to carry a minimum amount of auto liability insurance, and driving without it can bring fines, license suspension and personal liability for damages.',
        asOf: '2026-09',
        source: { name: 'USA.gov — Car insurance', url: 'https://www.usa.gov/car-insurance' },
        volatility: 'annual',
      },
      {
        id: 'f-uninsured-motorist',
        claim: 'Uninsured and underinsured motorist coverage pays you when the at-fault driver has no insurance or too little, and it is optional in many states.',
        asOf: '2026-09',
        source: { name: 'Insurance Information Institute — Uninsured motorist coverage', url: 'https://www.iii.org/article/what-is-uninsured-motorist-coverage' },
        volatility: 'annual',
      },
      {
        id: 'f-renters-liability',
        claim: 'Renters insurance typically covers personal property plus personal liability, and landlords frequently require it as a lease condition.',
        asOf: '2026-09',
        source: { name: 'Insurance Information Institute — Renters insurance', url: 'https://www.iii.org/article/renters-insurance-basics' },
        volatility: 'annual',
      },
      {
        id: 'f-nosurprises',
        claim: 'The No Surprises Act protects people with most forms of health coverage from certain surprise out-of-network bills, including many emergency services and some out-of-network providers at in-network facilities.',
        asOf: '2026-09',
        source: { name: 'CMS — No Surprises Act consumer information', url: 'https://www.cms.gov/nosurprises/consumers' },
        volatility: 'stable',
      },
      {
        id: 'f-insurance-license',
        claim: 'Insurance agents and companies must be licensed in the state where they sell, and consumers can verify a license through their state insurance department.',
        asOf: '2026-09',
        source: { name: 'National Association of Insurance Commissioners — Consumer resources', url: 'https://content.naic.org/consumer' },
        volatility: 'annual',
      },
      {
        id: 'f-vin-title',
        claim: 'A used car carries a "Buyers Guide" under the FTC Used Motor Vehicle Rule, and a car sold "as is" carries no warranty; the guide tells you which you are getting.',
        asOf: '2026-09',
        source: { name: 'FTC — Used car buying tips', url: 'https://consumer.ftc.gov/articles/used-car-buying-tips' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'Premium', plain: 'What you pay each month for the policy.', watchOut: '"Pay a lower premium today" offers that cut your coverage instead of your price.' },
      { term: 'Deductible', plain: 'What you pay before the insurer starts paying.', watchOut: 'Choosing a huge deductible to save money and then never using the insurance.' },
      { term: 'Liability only', plain: 'Covers damage you cause to others, not your own car.', watchOut: 'Driving a financed car with liability only — the lender requires more.' },
      { term: 'Uninsured motorist', plain: 'Pays you when the other driver has no insurance.', watchOut: 'Not having it and being hit by someone with nothing.' },
      { term: 'Claim', plain: 'Your formal request for payment.', watchOut: 'A "claims specialist" who calls first and asks for your banking details.' },
      { term: 'Lapse', plain: 'A gap in coverage. It raises your future prices.', watchOut: 'Cancelling before your new policy starts.' },
      { term: 'SR-22', plain: 'A form proving coverage, required after some violations.', watchOut: 'Paying an agency $500 to "file" a free form.' },
      { term: 'Buyers Guide', plain: 'The FTC window sticker on a used car that says whether there is a warranty.', watchOut: '"As is" on the guide means no warranty at all.' },
    ],
    steps: [
      'Get renters insurance the same week you sign a lease if the lease requires it or if you own anything worth more than your deposit.',
      'For auto: get the state minimum in writing, then ask for quotes that also include uninsured motorist and a realistic deductible. Compare at least three quotes.',
      'Write one page: policy numbers, insurer phone numbers, what to do in an accident, and where the documents are. Give a copy to the person who lives with you.',
      'Before signing anything for health, life or disability insurance, verify the agent\'s license with your state insurance department.',
      'Take photos and video of your apartment and car the day you move in or buy. Date-stamped evidence decides claims.',
      'If you buy a used car, insist on seeing the title in the seller\'s name and get a pre-purchase inspection. Meet at a bank or DMV, never in a parking lot with cash.',
    ],
    traps: [
      'Driving with no insurance because the premium feels like too much. One accident turns into wage garnishment and a license problem.',
      'Buying the cheapest liability-only policy, then being hit by an uninsured driver with no coverage to pay you.',
      'Cancelling old coverage before the new one starts, creating a lapse that raises prices for years.',
      'Buying "insurance" from someone who only sends you a WhatsApp message and a payment link.',
      'Believing a hospital or an insurer will always sort out a bill for you. You have to ask.',
      'Paying cash for a car and never transferring the title, then getting tickets for someone else\'s driving.',
      'Buying a policy you cannot read in a language you understand — demand the documents before paying.',
    ],
    questionsToAsk: [
      'What is my premium, deductible, and coverage limit for each part of this policy?',
      'Is this the state minimum, and what would comprehensive or uninsured motorist coverage add?',
      'What is your license number, and which state regulator can I check it with?',
      'If I cancel, what is the notice period, and can I get a refund of unused premium?',
      'Does this policy cover me if someone else drives my car, or if I drive someone else\'s?',
    ],
    officialLinks: [
      { name: 'USA.gov — Car insurance', url: 'https://www.usa.gov/car-insurance' },
      { name: 'NAIC — Consumer insurance resources', url: 'https://content.naic.org/consumer' },
      { name: 'CMS — No Surprises Act (consumers)', url: 'https://www.cms.gov/nosurprises/consumers' },
      { name: 'FTC — Used car buying tips', url: 'https://consumer.ftc.gov/articles/used-car-buying-tips' },
    ],
    relatedScamIds: ['insurance-scam', 'fake-check', 'accident-scam'],
  },

  {
    id: 'topic-buying-a-car',
    slug: 'buy-a-used-car-safely',
    title: 'Buying a used car without buying someone else\'s problem',
    category: 'money',
    oneLiner:
      'The two things that matter are whether the seller is the legal owner on the title, and whether the car is worth the price — everything else is negotiation.',
    whyItMatters:
      'A car is often an immigrant\'s biggest purchase after housing, and new arrivals are targeted by curbstoners (unlicensed dealers posing as owners), salvage-title cars with hidden crash damage, and "meet me with cash" robberies. Title problems can make a car impossible to register or insure.',
    keywords: [
      'buy a car', 'used car', 'car title', 'salvage', 'vin check', 'curbstoner',
      'cash for car', 'dealership', 'car loan', 'registration', 'test drive',
      'facebook marketplace car', 'odometer',
    ],
    explain: [
      'Do the paperwork before the excitement. Ask for the title and check that the name on it matches the seller\'s driver license exactly. Titles have a section for the legal owner and, on the back, for transfer — if the name does not match, or the seller says the car is "my cousin\'s", walk away. That is how stolen cars and unpaid liens end up in a buyer\'s driveway. Then check the VIN: it is visible through the windshield on the driver side and on the door jamb, and it appears on the title. If the VIN on the car does not match the title, there is no deal.',
      'Second, learn what a salvage or rebuilt title means: the car was declared a total loss at some point, usually by an insurer. Rebroadcast "clean title only" advice is not about snobbery — a rebuilt car can be perfectly safe, but it is worth less, harder to insure, and can hide structural damage. A cheap independent mechanic\'s inspection, before you pay anything, is the best money you will spend all month.',
      'Third, control the transaction itself. Meet in a public place — a bank lobby or a DMV office is ideal — during daylight, bring someone with you, and pay by a traceable method. "Curbstoning" is the practice of an unlicensed dealer posing as a private owner to dodge consumer protections; the tell is a seller with five cars, no title in their name, or an excuse for meeting in a parking lot with cash only. If it feels wrong, leave. There is always another car.',
    ],
    facts: [
      {
        id: 'f-ftc-buyers-guide',
        claim: 'A used car sold by a dealer must display an FTC Buyers Guide stating whether the vehicle is sold "as is" or with a warranty.',
        detail: 'A private-party sale is usually "as is" by default, which is why the inspection matters more, not less.',
        asOf: '2026-09',
        source: { name: 'FTC — Used car buying tips', url: 'https://consumer.ftc.gov/articles/used-car-buying-tips' },
        volatility: 'stable',
      },
      {
        id: 'f-title-transfer',
        claim: 'The buyer must usually receive a properly assigned title signed by the owner named on it, and register the vehicle with the state; a title in someone else\'s name means the transfer is invalid.',
        asOf: '2026-09',
        source: { name: 'USA.gov — Vehicle registration and titles', url: 'https://www.usa.gov/motor-vehicle-services' },
        volatility: 'stable',
      },
      {
        id: 'f-nmvtis',
        claim: 'The National Motor Vehicle Title Information System (NMVTIS) lets consumers check a vehicle\'s title history, including salvage and total-loss brands, through approved providers.',
        asOf: '2026-09',
        source: { name: 'NMVTIS — Consumer vehicle history', url: 'https://vehiclehistory.bja.ojp.gov/' },
        volatility: 'stable',
      },
      {
        id: 'f-odometer',
        claim: 'Federal law makes odometer fraud illegal, and a mismatched or rolled-back odometer reading can be a sign of a hidden salvage or insurance write-off.',
        asOf: '2026-09',
        source: { name: 'NHTSA — Odometer fraud', url: 'https://www.nhtsa.gov/equipment/odometer-fraud' },
        volatility: 'stable',
      },
      {
        id: 'f-vin-check',
        claim: 'VIN checks can reveal whether the car was reported stolen, flooded, or declared a total loss; free VIN decoders and paid history reports both exist.',
        asOf: '2026-09',
        source: { name: 'NHTSA — VIN decoder', url: 'https://www.nhtsa.gov/vin-decoder' },
        volatility: 'stable',
      },
      {
        id: 'f-cash-sale-safety',
        claim: 'Cash sales arranged with strangers online carry robbery risk; police departments and banks in many areas offer safe exchange locations.',
        asOf: '2026-09',
        source: { name: 'FTC — Online shopping and classified ad safety', url: 'https://consumer.ftc.gov/articles/how-avoid-scam' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'Clean title', plain: 'The car has never been declared a total loss.', watchOut: '"Clean" used with a shrug to describe a rebuilt car.' },
      { term: 'Salvage / rebuilt title', plain: 'Insurer declared the car a total loss; rebuilt means someone repaired it.', watchOut: 'Being sold as "just a rebuilt", when insurance and resale value drop sharply.' },
      { term: 'Curbstoner', plain: 'An unlicensed dealer pretending to be a private seller.', watchOut: 'Five "personal" cars, meetings in parking lots, cash only.' },
      { term: 'Lien', plain: 'A lender\'s claim on the car until the loan is paid.', watchOut: 'A lien still on the title: you may not be able to register the car.' },
      { term: 'Bill of sale', plain: 'A simple document recording the sale and price.', watchOut: 'Writing a fake low price to cut taxes — that is fraud and it hurts you if you claim a loss.' },
      { term: 'Pre-purchase inspection', plain: 'A mechanic checks the car before you buy it.', watchOut: 'Sellers who refuse to allow one. That is the answer.' },
      { term: 'Odometer rollback', plain: 'Turning back the mileage count to raise the price.', watchOut: 'Mileage that does not match the wear on the pedals and seats.' },
    ],
    steps: [
      'Decide your real budget including insurance, gas, registration and repairs — then look at cars priced below it.',
      'Ask for the VIN and the photo of the title before you travel to see the car. Compare names.',
      'Check the VIN in the NMVTIS system or through a history provider, and check for open recalls on NHTSA\'s site.',
      'Pay a mechanic for an inspection before buying. Meet at the mechanic\'s shop, not the seller\'s choice of location.',
      'Meet at a bank or a police-designated exchange area in daylight. Bring a person with you. Pay by traceable method and get a signed bill of sale with the odometer reading written on it.',
      'Complete the title transfer and registration with your state DMV promptly, and confirm your insurance is active before you drive away.',
    ],
    traps: [
      'Buying a car whose title is in a third party\'s name. The registration may be impossible.',
      'Skipping the pre-purchase inspection because the seller is in a hurry.',
      'Paying a deposit over an app to "hold" a car you have never seen. This is one of the most common online vehicle scams.',
      'Being told to pay for "shipping" so the car can be delivered to you. There is no car.',
      'Buying a salvage car without checking what your insurer will charge, or whether they will cover it at all.',
      'Signing a dealer finance contract without reading the total cost of the loan, only the monthly payment.',
      'Giving the seller your SSN "to check your financing" at a parking-lot dealership.',
    ],
    questionsToAsk: [
      'Is your name on the title, and can I photograph the title and your ID before we discuss price?',
      'Can I have my own mechanic inspect the car at my cost?',
      'Has the car ever been in an accident, flooded, or declared a total loss?',
      'Are there any open recalls or liens on this vehicle?',
      'What is the out-the-door price, including tax, title and registration fees?',
    ],
    officialLinks: [
      { name: 'FTC — Used car buying tips', url: 'https://consumer.ftc.gov/articles/used-car-buying-tips' },
      { name: 'NMVTIS — Title history check', url: 'https://vehiclehistory.bja.ojp.gov/' },
      { name: 'NHTSA — VIN decoder and recalls', url: 'https://www.nhtsa.gov/vin-decoder' },
      { name: 'USA.gov — Vehicle registration and titles', url: 'https://www.usa.gov/motor-vehicle-services' },
    ],
    relatedScamIds: ['fake-check', 'vehicle-shipping', 'curbstone'],
  },
]
