import type { Topic } from '../types'

/**
 * Paperwork: identity, status, and the documents that everything else depends on.
 * Every fact here is dated. When you re-verify one, bump `asOf`.
 */
export const paperworkTopics: Topic[] = [
  {
    id: 'topic-ssn-vs-itin',
    slug: 'ssn-vs-itin',
    title: 'SSN vs ITIN: the two numbers that unlock everything',
    category: 'paperwork',
    oneLiner:
      'A Social Security Number (SSN) is for people authorized to work in the US; an ITIN is a tax ID for people who must file taxes but cannot get an SSN. Many things you need — a bank account, an apartment, a phone plan — do not legally require either one.',
    whyItMatters:
      'People lose weeks and pay "agents" hundreds of dollars for numbers they can get for free. Others are told they cannot open a bank account or rent without an SSN, which is usually false. Getting this straight early removes the cover story every kind of fraudster uses on newcomers.',
    keywords: [
      'ssn', 'social security number', 'itin', 'tax id', 'taxpayer identification',
      'no ssn', 'without ssn', 'apply for social security', 'ss-5', 'w-7',
      'number for taxes', 'can i work without ssn',
    ],
    explain: [
      'Think of the SSN as the number tied to work and benefits. It is issued by the Social Security Administration (SSA), it is free, and you can only get one if you have work authorization or a specific qualifying status. The card itself says whether you can work ("VALID FOR WORK ONLY WITH DHS AUTHORIZATION" means your permission to work comes from your immigration status, not from the card).',
      'The ITIN is the number tied to taxes only. The IRS issues it to people who have to file a US tax return but are not eligible for an SSN — for example, a spouse or child on a return, or someone receiving US income. An ITIN never gives you permission to work, and it never gives you immigration status. Anyone who tells you otherwise is either wrong or stealing from you.',
      'The practical unlock is this: banks can open accounts with an ITIN or even a foreign passport in many cases, landlords can rent to you without an SSN, and states can issue a driver license or ID without one. Do not let a gatekeeper tell you that you need an SSN when the law does not require it. Ask them to show you where it says that in writing.',
    ],
    facts: [
      {
        id: 'f-ssn-free',
        claim: 'Applying for a Social Security number and card is free, and SSA never charges a fee for the application or the card.',
        detail:
          'If you have an application pending with USCIS, you can often request an SSN or replacement card on the same form (for example on Form I-485 or I-765) instead of making a separate trip.',
        asOf: '2026-09',
        source: { name: 'Social Security Administration — Social Security Number and Card', url: 'https://www.ssa.gov/number-card' },
        volatility: 'stable',
      },
      {
        id: 'f-itin-purpose',
        claim: 'An ITIN is for federal tax purposes only. It does not authorize you to work and does not give you immigration status.',
        asOf: '2026-09',
        source: { name: 'IRS — Individual Taxpayer Identification Number', url: 'https://www.irs.gov/individuals/individual-taxpayer-identification-number' },
        volatility: 'stable',
      },
      {
        id: 'f-itin-apply',
        claim: 'You apply for an ITIN with Form W-7, usually attached to a federal tax return, and processing takes about 7 weeks (9–11 weeks in peak filing season).',
        detail:
          'If you mail original documents, the IRS returns them, but it can take months. A Certifying Acceptance Agent (CAA) can verify your documents and return them to you in days, which is safer than mailing your passport. CAAs may charge a fee — that fee is legitimate, unlike a "fee" for the ITIN itself.',
        asOf: '2026-06',
        source: { name: 'IRS — About Form W-7, Application for IRS Individual Taxpayer Identification Number', url: 'https://www.irs.gov/forms-pubs/about-form-w-7' },
        volatility: 'annual',
      },
      {
        id: 'f-itin-expire',
        claim: 'An ITIN expires if you do not use it on a federal tax return for three consecutive years, and some ITINs with particular middle digits were expired in bulk.',
        detail:
          'Filing with an expired ITIN can delay your whole return and can disallow credits tied to that ITIN. Renewal uses the same Form W-7 and keeps the same number.',
        asOf: '2026-06',
        source: { name: 'IRS — Individual Taxpayer Identification Number (renewals)', url: 'https://www.irs.gov/individuals/individual-taxpayer-identification-number' },
        volatility: 'stable',
      },
      {
        id: 'f-ssn-ss-5',
        claim: 'To get an SSN you file Form SS-5 with evidence of identity, immigration status and work authorization, usually in person at a Social Security office or by mail.',
        asOf: '2026-09',
        source: { name: 'SSA — Form SS-5, Application for a Social Security Card', url: 'https://www.ssa.gov/forms/ss-5.pdf' },
        volatility: 'stable',
      },
      {
        id: 'f-no-person',
        claim: 'No private person, "agency", lawyer or service can sell you an SSN or ITIN. Any offer to obtain one for a fee beyond a legitimate document-preparation charge is a scam.',
        asOf: '2026-09',
        source: { name: 'FTC — Immigration services scams', url: 'https://consumer.ftc.gov/articles/immigration-services-scams' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'SSN', plain: 'Social Security Number. Your work-and-benefits ID. Free from the government. Format: 000-00-0000.', watchOut: 'A scammer asking you to "confirm" it over the phone or by text.' },
      { term: 'ITIN', plain: 'Individual Taxpayer Identification Number. Your tax-only ID. Starts with 9.', watchOut: 'Anyone claiming an ITIN gives you the right to work.' },
      { term: 'EAD', plain: 'Employment Authorization Document. The plastic work permit card.', watchOut: 'Anyone charging you to "activate" it.' },
      { term: 'CAA', plain: 'Certifying Acceptance Agent. An IRS-approved person who can verify your ID documents so you do not mail your passport.', watchOut: 'People who call themselves a CAA but are not on the IRS list.' },
      { term: 'A-number', plain: 'Alien registration number. Your 7–9 digit immigration ID, printed on USCIS documents (often as "USCIS#" or "A#").', watchOut: 'Anyone who already knows your A-number and calls you first — that number is on many documents.' },
      { term: 'Notice of Action', plain: 'The USCIS letter (Form I-797) that proves they received or approved something.', watchOut: 'Fake I-797s asking for a fee by gift card or wire.' },
    ],
    steps: [
      'Check what status you actually have and whether it includes work authorization. That single fact decides whether you can get an SSN today or need an ITIN.',
      'If you are work-authorized and have no SSN, file Form SS-5 — free. If you already have a pending USCIS application, see whether you can request the SSN on that form instead.',
      'If you must file a tax return but cannot get an SSN, file Form W-7 to get an ITIN. Ask a free tax clinic (VITA) or a Certifying Acceptance Agent for help before mailing your passport.',
      'Open a bank account and set up your income before you need credit. Both are possible with an ITIN or a foreign passport at many banks — ask specifically, and if the first branch says no, try another bank.',
      'Write your two numbers (and your A-number) into a paper record kept somewhere safe, and never send them by text, email or social media.',
    ],
    traps: [
      'Paying a "consultant" for an SSN or ITIN. Both are free. You are buying paperwork help at most — never the number itself.',
      'Believing you cannot rent, get a phone, or open a bank account without an SSN. Many institutions accept an ITIN, a passport, or a consular ID; policies vary by company, so ask each one.',
      'Mailing your only passport to the IRS without tracking. Use a CAA or a Taxpayer Assistance Center appointment instead when possible.',
      'Letting your ITIN lapse for three years and then discovering your whole refund is held up in April.',
      'Giving your SSN or ITIN to a landlord "for a background check" before you have seen the apartment or signed anything. Ask what they will do with it and whether a written application with a receipt is provided.',
      'Using a fake or borrowed SSN to work. It can destroy your ability to ever fix your immigration case and is a federal crime.',
    ],
    questionsToAsk: [
      'Where exactly does it say I need an SSN for this? Can you show me the policy in writing?',
      'Do you accept an ITIN or a foreign passport as identification instead?',
      'Is this fee for the government document itself, or for your help preparing paperwork?',
      'Will you give me a written receipt showing what I paid and what you filed on my behalf?',
    ],
    officialLinks: [
      { name: 'SSA — Social Security number and card', url: 'https://www.ssa.gov/number-card' },
      { name: 'IRS — ITIN information', url: 'https://www.irs.gov/individuals/individual-taxpayer-identification-number' },
      { name: 'IRS — Free tax return preparation (VITA/TCE locator)', url: 'https://www.irs.gov/individuals/free-tax-return-preparation-for-you-by-volunteers' },
      { name: 'IRS — Acceptance Agent Program', url: 'https://www.irs.gov/individuals/international-taxpayers/acceptance-agent-program' },
    ],
    relatedScamIds: ['notario-fraud', 'gov-impersonation', 'ssn-for-sale'],
  },

  {
    id: 'topic-work-permit-ead',
    slug: 'work-permit-renewal',
    title: 'Your work permit (EAD): renew early, because the safety net is gone',
    category: 'paperwork',
    oneLiner:
      'Your Employment Authorization Document has an expiry date. You must apply to renew it months in advance, and since October 30, 2025 most people no longer get an automatic extension while waiting.',
    whyItMatters:
      'This is the single most expensive date on an immigrant\'s calendar. Miss it and you lose your legal ability to work, your employer is legally required to stop paying you, and getting it back can take months. The rule changed recently and a lot of outdated advice is still circulating.',
    keywords: [
      'ead', 'work permit', 'i-765', 'renew work permit', 'work authorization',
      'expired work permit', 'can i work while waiting', 'auto extension', '540 days',
      '180 days', 'employment authorization', 'card expiring',
    ],
    explain: [
      'Your EAD is the card that proves to an employer you may work. It is tied to a category code (printed on the card, like C08, C09, A05). Renewals must generally be filed in the same category and normally cannot be filed more than 180 days before the card expires. So the workable window is usually "180 days before expiry" down to "as soon as possible".',
      'The change that is catching people out: DHS published an interim final rule on October 30, 2025 ending the automatic extension of EADs for renewal applications filed on or after that date. For years, filing on time bought you up to 540 extra days of work authorization. That protection is gone for most filers. If your renewal is filed late — or filed on time but USCIS is slow — you can be legally unable to work while you wait.',
      'That turns a paperwork task into a cash-flow emergency, which is exactly when people accept bad offers: cash-under-the-table work, a "sponsor" who wants money, or an employer who keeps paying you off the books and then threatens you. Plan for this date like a rent payment. If your card expires and you cannot work, you may still be able to keep income through severance, paid leave already accrued, a spouse\'s authorization, or a different work-authorized status — check with a licensed attorney or a free legal aid office before assuming you have no options.',
    ],
    facts: [
      {
        id: 'f-ead-auto-extension-ended',
        claim: 'DHS ended automatic extensions of EADs for renewal applications filed on or after October 30, 2025, so a pending renewal generally no longer keeps you work-authorized.',
        detail:
          'Some groups keep protection. If you filed a renewal before October 30, 2025 with a qualifying category code, the up-to-540-day automatic extension can still apply. TPS-related EADs extended by a Federal Register notice are a separate track. Confirm your specific category before relying on anything.',
        asOf: '2025-10-30',
        source: { name: 'USCIS — Interim Final Rule Published Ending the Practice of Automatically Extending Certain EADs', url: 'https://www.uscis.gov/save/current-user-agencies/news-alerts/interim-final-rule-published-ending-the-practice-of-automatically-extending-certain-eads' },
        volatility: 'volatile',
      },
      {
        id: 'f-ead-file-180',
        claim: 'USCIS recommends filing an EAD renewal 180 days before your card expires, and many categories cannot be renewed earlier than that.',
        asOf: '2026-09',
        source: { name: 'USCIS — Application for Employment Authorization (Form I-765)', url: 'https://www.uscis.gov/i-765' },
        volatility: 'annual',
      },
      {
        id: 'f-ead-processing',
        claim: 'EAD processing times vary widely by category and office, and published ranges routinely run from a couple of months to 12 months or more.',
        detail:
          'Check the official case processing times tool for your form and your category, not a lawyer blog. Then assume it will be slower than the range.',
        asOf: '2026-09',
        source: { name: 'USCIS — Check Case Processing Times', url: 'https://egov.uscis.gov/processing-times/' },
        volatility: 'volatile',
      },
      {
        id: 'f-ead-validity-shortened',
        claim: 'Work permit validity periods have been shortened for some categories, in some cases from five years to 18 months, which means more renewals and more chances to lapse.',
        asOf: '2026-08',
        source: { name: 'American Immigration Council — Recent Federal Changes to Employment Authorization', url: 'https://www.americanimmigrationcouncil.org/fact-sheet/employment-authorization-changes/' },
        volatility: 'volatile',
      },
      {
        id: 'f-ead-fees',
        claim: 'USCIS filing fees are set in the official fee schedule (Form G-1055), and some immigration categories carry additional statutory fees on top of the standard filing fee.',
        detail:
          'Fees change by rule and by fiscal year. Always price your case from the official fee schedule, not from a website that quotes a number without a date.',
        asOf: '2026-06',
        source: { name: 'USCIS — Form G-1055, Fee Schedule', url: 'https://www.uscis.gov/sites/default/files/document/forms/g-1055.pdf' },
        volatility: 'annual',
      },
      {
        id: 'f-ead-employer-i9',
        claim: 'Employers must verify work authorization using Form I-9 and cannot accept a document you offer if it has expired, unless the law provides an automatic extension for it.',
        asOf: '2026-09',
        source: { name: 'USCIS — Form I-9, Employment Eligibility Verification', url: 'https://www.uscis.gov/i-9' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'EAD', plain: 'Employment Authorization Document — the work permit card.', watchOut: '"We can renew it for you for a fee" from anyone who is not a licensed attorney or accredited representative.' },
      { term: 'Category code', plain: 'The letter-number on the card (C08, C09, A12 etc.) that identifies why you can work. Your renewal must match.', watchOut: 'Nobody checks it, you file in the wrong category, the case is denied, and the fee is gone.' },
      { term: 'Cap-gap', plain: 'Special protection for some F-1 students whose work authorization would end between their OPT end and the start of a new H-1B.', watchOut: 'Assuming cap-gap applies to you without confirming with your school\'s international office.' },
      { term: 'Receipt notice / I-797C', plain: 'The letter proving USCIS received your application. In some categories this used to keep you working; for renewals filed after Oct 30, 2025 it usually does not.', watchOut: 'An employer or "agent" telling you the receipt alone means you can keep working.' },
      { term: 'Premium processing', plain: 'An optional extra fee to speed up a specific form. It is not a premium fee to speed up your whole immigration case.', watchOut: 'Anyone promising a faster EAD for a cash payment off the books.' },
      { term: 'Unlawful presence / unauthorized work', plain: 'Working without authorization can be a problem later.', watchOut: 'An employer who insists you keep working while your card is expired, saying "nobody checks." You are the one who carries the risk.' },
    ],
    steps: [
      'Today: find your EAD expiry date and write it in your phone with two alarms — 200 days before and 180 days before.',
      'Confirm your category code on the card and check the current Form I-765 instructions for the fee and filing address for that category.',
      'At the 180-day mark, file. Track the mailing, keep the receipt notice, and take a photo of everything you sent.',
      'Tell your employer early, in writing, with the expiry date, so HR is not surprised. A good employer will plan with you; a bad one will reveal itself now rather than in your last week.',
      'If your card lapses anyway, do not simply keep working quietly. Get a free or low-cost consultation first — legal aid offices, law school clinics and some unions offer them.',
      'If a renewal is denied, the denial notice explains the reason and whether you can refile or appeal. Do not accept a verbal explanation from anyone.',
    ],
    timeline: [
      { when: '200 days before expiry', what: 'Check category code, fees, and whether your category has any automatic extension.' },
      { when: '180 days before expiry', what: 'File the renewal. This is the earliest allowed for many categories and the safest possible date.' },
      { when: 'Between filing and decision', what: 'Keep the receipt notice with your I-9 documents. Do not assume it keeps you work-authorized.' },
      { when: '30 days before expiry', what: 'Talk to your employer in writing about what happens if the new card is late.' },
      { when: 'Expiry date', what: 'If there is no new card, your work authorization for that status has ended. Get advice before doing anything else.' },
    ],
    traps: [
      'Treating the old "540-day automatic extension" as still available. It ended for renewals filed on or after October 30, 2025.',
      'Filing too early and having the application rejected because it was outside the window.',
      'Filing in the wrong category because a friend filed under a different status.',
      'Paying a "consultant" to file it while they keep the receipt notices, so you cannot prove anything later.',
      'Not telling your employer until the card expires. Good HR departments can plan around a known date; they cannot fix a surprise.',
      'Continuing to work after authorization lapses because your employer says it is fine. The penalty lands on you, permanently.',
      'Believing a "sponsor" who offers to file for you in exchange for a share of your wages.',
    ],
    questionsToAsk: [
      'What is my exact category code, and what does the current fee schedule say I owe for a renewal in that category?',
      'Does my category still get any automatic extension, or did the October 2025 rule remove it for me?',
      'Are you a licensed attorney or a DOJ-accredited representative? What is your bar number or accreditation?',
      'What is your total fee, and how much of that is the government filing fee?',
      'Can I have copies of everything you file, plus every receipt and notice?',
    ],
    officialLinks: [
      { name: 'USCIS — Form I-765, Application for Employment Authorization', url: 'https://www.uscis.gov/i-765' },
      { name: 'USCIS — Check Case Processing Times', url: 'https://egov.uscis.gov/processing-times/' },
      { name: 'USCIS — Form G-1055 Fee Schedule', url: 'https://www.uscis.gov/sites/default/files/document/forms/g-1055.pdf' },
      { name: 'USCIS — Case Status Online', url: 'https://egov.uscis.gov/casestatus' },
      { name: 'DOJ EOIR — List of Pro Bono Legal Service Providers', url: 'https://www.justice.gov/eoir/list-pro-bono-legal-service-providers' },
    ],
    relatedScamIds: ['notario-fraud', 'fake-uscis-fee', 'job-scam-cash'],
  },

  {
    id: 'topic-uscis-notices',
    slug: 'read-uscis-mail',
    title: 'Reading official mail without panicking (and spotting fake letters)',
    category: 'paperwork',
    oneLiner:
      'Real government mail has identifiers you can verify yourself on the agency\'s own website — without clicking any link in the letter.',
    whyItMatters:
      'Immigrants receive a lot of terrifying mail, and scams imitate it well because fear works. The defense is procedural, not emotional: verify the letter through a channel you chose, never one the letter gives you.',
    keywords: [
      'uscis letter', 'notice of action', 'i-797', 'court notice', 'immigration court',
      'real or fake letter', 'government letter', 'rfe', 'request for evidence',
      'nta', 'notice to appear', 'case number', 'receipt number',
    ],
    explain: [
      'USCIS, the IRS and immigration courts really do send letters, and some of them really are bad news. Ignoring real mail is far more dangerous than opening fake mail. So the skill is not "be suspicious of everything" — it is "verify everything through a door you picked yourself."',
      'There are three verification doors you should know: USCIS case status online (uses your receipt number, which starts with three letters like EAC, WAC, LIN, MSC, IOE followed by ten digits), the immigration court\'s automated case information line and website (uses your A-number), and the IRS (which tells you to call a number on the notice — but you should instead log into your own IRS account or call the number on irs.gov).',
      'A real USCIS notice will tell you what form and what decision, and gives you a deadline counted from the date of the notice. A fake one usually wants speed, a payment method, or a click. Money is never requested by gift card, cryptocurrency, wire transfer or payment app in a genuine government notice. That single rule ends most of these scams.',
    ],
    facts: [
      {
        id: 'f-uscis-case-status',
        claim: 'You can check the status of a USCIS case yourself using the receipt number printed on any USCIS notice, at egov.uscis.gov/casestatus.',
        asOf: '2026-09',
        source: { name: 'USCIS — Case Status Online', url: 'https://egov.uscis.gov/casestatus' },
        volatility: 'stable',
      },
      {
        id: 'f-eoir-hotline',
        claim: 'Immigration court case information can be checked with the EOIR automated case information hotline and website using your A-number.',
        detail:
          'The automated hotline is 1-800-898-7180 and the website is acis.eoir.justice.gov. A real hearing notice (Form EOIR-33/Notice to Appear/Notice of Hearing) will connect to a real case there.',
        asOf: '2026-09',
        source: { name: 'DOJ EOIR — Automated Case Information', url: 'https://acis.eoir.justice.gov/' },
        volatility: 'stable',
      },
      {
        id: 'f-uscis-never-fee-methods',
        claim: 'USCIS never asks for payment over the phone, by gift card, by cryptocurrency, by wire transfer or by payment app.',
        detail:
          'Fees are paid to USCIS through the methods listed on the official fee page, and you get a receipt.',
        asOf: '2026-09',
        source: { name: 'USCIS — Avoid Scams', url: 'https://www.uscis.gov/avoid-scams' },
        volatility: 'stable',
      },
      {
        id: 'f-ar11',
        claim: 'Most noncitizens must report a change of address to USCIS within 10 days using Form AR-11, and those in removal proceedings must also notify the immigration court.',
        detail:
          'This is one of the most commonly missed requirements in the entire system, and failing it can cause a hearing or decision to happen without you.',
        asOf: '2026-09',
        source: { name: 'USCIS — How to Change Your Address', url: 'https://www.uscis.gov/addresschange' },
        volatility: 'stable',
      },
      {
        id: 'f-eoir-ecourt',
        claim: 'Immigration court notices matter even when they look routine: a missed hearing can result in an in-absentia removal order entered against you.',
        asOf: '2026-09',
        source: { name: 'DOJ EOIR — Immigration Court Practice Manual', url: 'https://www.justice.gov/eoir/page/file/910611/download' },
        volatility: 'stable',
      },
      {
        id: 'f-no-appointed-lawyer',
        claim: 'There is no right to a government-appointed lawyer in immigration court, which is why fake "attorneys" target people in proceedings.',
        detail:
          'Free representation exists through legal aid organizations, law school clinics and the EOIR pro bono list — but you have to find them yourself, and they never charge you for the referral.',
        asOf: '2026-09',
        source: { name: 'DOJ EOIR — List of Pro Bono Legal Service Providers', url: 'https://www.justice.gov/eoir/list-pro-bono-legal-service-providers' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'Notice of Action (I-797)', plain: 'Generic USCIS letter: receipt, approval, or rejection.', watchOut: 'Fakes asking for a "processing fee" to release your case.' },
      { term: 'RFE', plain: 'Request for Evidence. USCIS wants more documents by a deadline.', watchOut: 'A person calling to "help you answer the RFE" for a fee, using the letter as proof they are official.' },
      { term: 'NTA', plain: 'Notice to Appear. The document that starts removal proceedings in immigration court.', watchOut: 'Anyone charging to "cancel" it informally. Only a lawyer or your case can resolve it.' },
      { term: 'A-number', plain: 'Your immigration file number.', watchOut: 'Scammers get this from data breaches and open with it to sound official.' },
      { term: 'In absentia order', plain: 'A removal order issued because you did not show up to court.', watchOut: 'Not being told you had a hearing because you moved without updating your address.' },
      { term: 'USCIS online account', plain: 'Your own login at my.uscis.gov where notices are also posted.', watchOut: 'Emails that look like USCIS login pages. Always type the address yourself.' },
    ],
    steps: [
      'Create your own USCIS online account and turn on paper + electronic notices so you have two channels.',
      'Photograph every notice the day it arrives, and keep the envelope (the postmark date can matter).',
      'Verify receipt numbers at egov.uscis.gov/casestatus and court information at acis.eoir.justice.gov — by typing the address, never by clicking a link.',
      'Calendar every deadline as "date of notice + their stated number of days", then add a personal alarm one week earlier.',
      'File the AR-11 address change online every single time you move, and separately notify the court if you are in proceedings.',
      'If a letter is confusing and the deadline is close, get a real lawyer the same week. Free options exist; see the pro bono list.',
    ],
    traps: [
      'Judging a letter by whether it "looks official." Scam letters use real seals, real form numbers and real case numbers from breaches.',
      'Calling the phone number printed on a suspicious notice. Look up the agency\'s number yourself instead.',
      'Ignoring a notice because you assume it is fake. Real notices expire on real deadlines.',
      'Moving without filing AR-11, then losing the case for a hearing you never heard about.',
      'Letting a "friend who speaks better English" handle the letter and never seeing it yourself.',
      'Paying anyone to "check your case." Case status is free and public with your receipt number.',
    ],
    questionsToAsk: [
      'What is the receipt number or A-number, and can I verify it myself right now?',
      'What exact form is this, and what is the deadline counted from?',
      'Is there anything here that requires a paid professional, or can I do it myself with the official instructions?',
      'Am I in immigration court proceedings? If yes, is there a free legal aid organization that covers my city?',
    ],
    officialLinks: [
      { name: 'USCIS — Case Status Online', url: 'https://egov.uscis.gov/casestatus' },
      { name: 'USCIS — Avoid Scams', url: 'https://www.uscis.gov/avoid-scams' },
      { name: 'USCIS — Change of address (AR-11)', url: 'https://www.uscis.gov/addresschange' },
      { name: 'EOIR — Automated Case Information', url: 'https://acis.eoir.justice.gov/' },
      { name: 'EOIR — List of Pro Bono Legal Service Providers', url: 'https://www.justice.gov/eoir/list-pro-bono-legal-service-providers' },
    ],
    relatedScamIds: ['gov-impersonation', 'fake-uscis-fee', 'notario-fraud'],
  },

  {
    id: 'topic-legal-help',
    slug: 'find-a-real-lawyer',
    title: 'Finding real legal help without being fleeced',
    category: 'paperwork',
    oneLiner:
      'Immigration advice may only be given by a licensed attorney or a DOJ-accredited representative working for a recognized organization — nobody else, no matter what their business card says.',
    whyItMatters:
      'This is where immigrants lose the most money and the most future. A notario, paralegal or "immigration consultant" who files the wrong form can destroy a case that a real lawyer could have won, and the deadline does not come back.',
    keywords: [
      'immigration lawyer', 'attorney', 'notario', 'consultant', 'legal aid',
      'free lawyer', 'accredited representative', 'doj accredited', 'bar number',
      'lawyer cost', 'how to find a lawyer', 'legal advice',
    ],
    explain: [
      'The line is simple and legal: only a licensed attorney or a DOJ-accredited representative at a recognized nonprofit organization can give you immigration advice or select a form for you. Everyone else can legally only type, translate or mail what you tell them to. When someone crosses that line, you have no malpractice protection, no bar to complain to, and usually no refund.',
      'In Latin America a "notario público" is a powerful legal professional. In the US a notary public is a person who stamps signatures — often a bank teller. Whole fraud industries exist on this one confusion, which is why "notario fraud" is a named category at the FTC.',
      'Good legal help is more available than people think. Nonprofits, legal aid offices, law school clinics and union legal plans serve people for free or on a sliding scale, and the government publishes a list of pro bono providers. What is genuinely scarce is trustworthy paid help at a fair price — so before you pay anyone, verify the license. Bar associations and the immigration court\'s own practitioner list let you check a name in minutes.',
    ],
    facts: [
      {
        id: 'f-accredited-only',
        claim: 'Only a licensed attorney or a DOJ-accredited representative may advise you on immigration matters or choose forms for you; notaries public and "immigration consultants" may not.',
        asOf: '2026-09',
        source: { name: 'USCIS — Avoid Scams (unauthorized practice of immigration law)', url: 'https://www.uscis.gov/avoid-scams' },
        volatility: 'stable',
      },
      {
        id: 'f-recognized-org-list',
        claim: 'The Department of Justice publishes the official list of recognized organizations and accredited representatives, so you can verify anyone who claims that status.',
        asOf: '2026-09',
        source: { name: 'DOJ — Recognition and Accreditation Program', url: 'https://www.justice.gov/eoir/recognition-and-accreditation-program' },
        volatility: 'stable',
      },
      {
        id: 'f-probono-list',
        claim: 'EOIR publishes a state-by-state list of free and low-cost legal service providers for people in immigration proceedings.',
        asOf: '2026-09',
        source: { name: 'DOJ EOIR — List of Pro Bono Legal Service Providers', url: 'https://www.justice.gov/eoir/list-pro-bono-legal-service-providers' },
        volatility: 'stable',
      },
      {
        id: 'f-no-guarantees',
        claim: 'No lawyer can guarantee a visa, green card, asylum grant or court outcome. A guarantee of a result is a hallmark of fraud, not expertise.',
        asOf: '2026-09',
        source: { name: 'FTC — Immigration services scams', url: 'https://consumer.ftc.gov/articles/immigration-services-scams' },
        volatility: 'stable',
      },
      {
        id: 'f-notario-fraud',
        claim: 'The FTC names "notario" fraud as a recurring immigration scam: notaries pretending to offer legal services, often charging large fees for filings they are not permitted to prepare.',
        asOf: '2026-09',
        source: { name: 'FTC — Immigration services scams', url: 'https://consumer.ftc.gov/articles/immigration-services-scams' },
        volatility: 'stable',
      },
      {
        id: 'f-scam-report',
        claim: 'You can report immigration service fraud to the FTC at ReportFraud.ftc.gov, and to your state attorney general or consumer protection office; USCIS also takes scam reports through its own tip line.',
        asOf: '2026-09',
        source: { name: 'FTC — Report Fraud', url: 'https://reportfraud.ftc.gov/' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'Notario público', plain: 'In the US: a notary. Stamps signatures. Cannot give immigration advice.', watchOut: 'Anyone using a "notario" title to sell legal services.' },
      { term: 'Accredited representative', plain: 'A non-lawyer authorized by the DOJ to represent you, working for a recognized nonprofit.', watchOut: 'Someone claiming this status who is not on the official list.' },
      { term: 'Retainer', plain: 'The upfront money you pay a lawyer to start a case.', watchOut: 'A retainer with no written agreement, no scope, and no refund policy.' },
      { term: 'Bar number', plain: 'The license ID of a lawyer. You can look it up on the state bar website.', watchOut: 'A lawyer who cannot or will not give you one.' },
      { term: 'UPL', plain: 'Unauthorized Practice of Law — giving legal advice without a license.', watchOut: 'Consultants who "know a guy" and fill out your forms.' },
      { term: 'Sliding scale', plain: 'A fee based on your income. Often very low, sometimes zero.', watchOut: 'Nobody is calling it sliding scale while charging $4,000 cash.' },
    ],
    steps: [
      'Write down your actual question in one sentence before you talk to anyone. Vague fear is what gets exploited.',
      'Start with free and low-cost routes: legal aid offices, nonprofit immigration organizations, law school clinics, and the EOIR pro bono list. Use the official links below.',
      'If you pay someone, verify their license the same day: state bar lookup for attorneys, DOJ list for accredited representatives.',
      'Get a written agreement: who does what, total cost, whether government fees are included, and what happens if the case is denied.',
      'Ask for copies of everything filed and every receipt. If a "preparer" refuses, that is your answer — walk away.',
      'Keep your own file: one folder, one cloud copy, with every notice, receipt and payment record.',
    ],
    traps: [
      'Paying a notary or "immigration consultant" to choose and file a form for you. That is unauthorized practice and it is exactly how cases are destroyed.',
      'Cash payments with no receipt, in an office with no written agreement.',
      'Guarantees: "100% approval", "we know someone at USCIS".',
      'Being told your case is "easy" so you do not need a lawyer — then losing an appeal window you did not know existed.',
      'Handing over original documents (passport, birth certificate, I-94) to be kept "for the file".',
      'Signing blank forms "so we can fill them in later."',
      'Using an out-of-state "agency" that only communicates on WhatsApp and demands gift card payments.',
    ],
    questionsToAsk: [
      'Are you a licensed attorney or a DOJ-accredited representative? What is your bar or accreditation number?',
      'What exactly will you file, and what is the deadline?',
      'What is the total cost including government filing fees, and can I pay it in stages?',
      'What happens if the case is denied — is any part refundable, and what is the next step?',
      'Will I get a copy of everything you file, and all notices?',
    ],
    officialLinks: [
      { name: 'EOIR — List of Pro Bono Legal Service Providers', url: 'https://www.justice.gov/eoir/list-pro-bono-legal-service-providers' },
      { name: 'DOJ — Recognition and Accreditation Program', url: 'https://www.justice.gov/eoir/recognition-and-accreditation-program' },
      { name: 'FTC — Immigration services scams', url: 'https://consumer.ftc.gov/articles/immigration-services-scams' },
      { name: 'USCIS — Avoid Scams', url: 'https://www.uscis.gov/avoid-scams' },
      { name: 'USA.gov — Legal aid', url: 'https://www.usa.gov/legal-aid' },
    ],
    relatedScamIds: ['notario-fraud', 'gov-impersonation'],
  },

  {
    id: 'topic-documents-vault',
    slug: 'protect-your-documents',
    title: 'The document set that decides your future — and how to protect it',
    category: 'paperwork',
    oneLiner:
      'A small set of documents (passport, I-94, work permit, SSN/ITIN, birth certificate, lease history, pay stubs, tax returns) is your entire legal and financial identity in the US. Losing control of it is far more expensive than losing cash.',
    whyItMatters:
      'Immigrants are targeted for identity theft because their numbers are often new to the credit system, which means an empty file that a scammer can load with debt. Also, replacing immigration documents from abroad can take months, which is why copies and cloud backups matter more than a safe.',
    keywords: [
      'i-94', 'passport', 'birth certificate', 'important documents', 'lost passport',
      'identity theft', 'documents checklist', 'keep documents safe', 'backup',
      'what documents do i need', 'replace documents',
    ],
    explain: [
      'Your US life runs on a short list of papers: passport with your visa, the I-94 arrival record (now usually electronic — get the official copy at i94.cbp.dhs.gov), your I-797 notices, your EAD, your SSN or ITIN, your birth certificate with a certified translation if needed, and later your state ID or driver license. Add to that the financial layer: lease, utility accounts, bank statements, pay stubs and filed tax returns.',
      'Two habits prevent almost every disaster here. First: keep a digital copy of everything in a place that is not the same place as the original, so a fire, a lost bag or a raid does not end your ability to prove who you are. Second: never hand originals to a stranger with a promise. You can almost always show a copy and keep the original.',
      'When something is genuinely lost, the replacement path is bureaucratic but real: the I-94 is downloadable online, immigration notices can be requested through USCIS, a passport comes from your country\'s consulate in the US, and a birth certificate from your home country\'s records office. Knowing this turns a catastrophe into an errand — and it is the reason someone who tells you they can "fix" your lost documents for cash is not needed.',
    ],
    facts: [
      {
        id: 'f-i94-online',
        claim: 'You can retrieve your official I-94 arrival/departure record online from CBP at i94.cbp.dhs.gov and print it yourself.',
        asOf: '2026-09',
        source: { name: 'US CBP — I-94 Official Website', url: 'https://i94.cbp.dhs.gov/' },
        volatility: 'stable',
      },
      {
        id: 'f-identitytheft-gov',
        claim: 'If your identity is stolen, identitytheft.gov produces a personalized recovery plan and an FTC Identity Theft Report you can use with police, banks and credit bureaus.',
        asOf: '2026-09',
        source: { name: 'FTC — IdentityTheft.gov', url: 'https://www.identitytheft.gov/' },
        volatility: 'stable',
      },
      {
        id: 'f-free-credit-reports',
        claim: 'You are entitled to free credit reports from each of the three national bureaus at AnnualCreditReport.com, the only federally authorized site for the free annual reports.',
        asOf: '2026-09',
        source: { name: 'Consumer Financial Protection Bureau — Free credit reports', url: 'https://www.consumerfinance.gov/consumer-tools/credit-reports-and-scores/' },
        volatility: 'stable',
      },
      {
        id: 'f-credit-freeze-free',
        claim: 'Placing a security freeze on your credit file is free with all three national bureaus, and a freeze is the strongest routine protection against someone opening credit in your name.',
        asOf: '2026-09',
        source: { name: 'Consumer Financial Protection Bureau — How to place a security freeze', url: 'https://www.consumerfinance.gov/ask-cfpb/how-do-i-place-a-security-freeze-on-my-credit-report-en-1325/' },
        volatility: 'annual',
      },
      {
        id: 'f-ar11-copies',
        claim: 'Keep copies of every form you file with USCIS and every notice you receive: USCIS may deny or decide a case based on what is in your file, and your copy is your only guaranteed record.',
        asOf: '2026-09',
        source: { name: 'USCIS — Avoid Scams / file your own case', url: 'https://www.uscis.gov/avoid-scams' },
        volatility: 'stable',
      },
      {
        id: 'f-selectiveservice',
        claim: 'Males living in the US between ages 18 and 25 generally must register with Selective Service, and immigrants in many statuses are included; failing to register can affect later immigration applications.',
        detail:
          'This is one of the most commonly missed requirements, and it is free to register online at sss.gov. Check the exceptions on the official site before assuming you are excluded.',
        asOf: '2026-09',
        source: { name: 'Selective Service System — Register', url: 'https://www.sss.gov/register/' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'I-94', plain: 'Your official record of entering the US, with your admitted status and how long you may stay.', watchOut: 'Websites that charge $30 for an I-94 you can download free from CBP.' },
      { term: 'Certified translation', plain: 'A translation with a signed statement that the translator is competent and the translation is accurate. A notary stamp is not a translation.', watchOut: 'Paying for expensive "certification" you can do yourself with the right statement.' },
      { term: 'Identity theft report', plain: 'The FTC document that formally records that you are a victim, which banks and police accept.', watchOut: 'A "credit repair" company that files things for you and charges monthly.' },
      { term: 'Security freeze', plain: 'A lock on your credit file so nobody can open credit in your name. Free to place and lift.', watchOut: 'Companies charging monthly fees for what the bureaus do free.' },
      { term: 'Fraud alert', plain: 'A note on your credit file asking lenders to verify your identity. One year, or seven with an identity theft report.', watchOut: 'Anyone selling you "identity protection" you can do yourself in 20 minutes.' },
      { term: 'Apostille', plain: 'A government authentication stamp that makes a document valid in another country.', watchOut: 'A "courier" who takes your originals and stops answering.' },
    ],
    steps: [
      'Build the folder today: passport page, visa, I-94 printout, all I-797 notices, EAD (both sides), SSN/ITIN card, birth certificate, and later your state ID.',
      'Scan or photograph everything. Store one copy in a cloud account and one with a person you trust in your home country.',
      'Write down expiry dates (EAD, visa, passport, driver license, lease) into one calendar with alarms.',
      'Check your credit report free at AnnualCreditReport.com, then place a free security freeze with each of the three bureaus if you are not applying for credit right now.',
      'Register with Selective Service if you are a male aged 18–25 and the official rules require it.',
      'Keep originals with you. Show copies. Never surrender an original document for "processing".',
    ],
    traps: [
      'Paying a third-party site for your I-94, which is free from CBP.',
      'Mailing your only passport somewhere without tracking, or giving it to a "consultant" as collateral.',
      'Keeping all documents in one bag that you carry everywhere.',
      'Assuming identity theft is only a problem for people with credit. An empty credit file is a target.',
      'Never checking your credit report, so a fraudulent account stays open for years.',
      'Paying a monthly fee for a "credit monitoring" service instead of using the free reports and freezes the law already gives you.',
      'Translating official documents with a friend and no signed certification statement, then having the document rejected.',
    ],
    questionsToAsk: [
      'Why do you need the original instead of a copy?',
      'When will I get it back, and what is the receipt for it?',
      'Is this document available directly from a government website for free?',
      'Which visa or case number on this document should I use to verify it myself?',
    ],
    officialLinks: [
      { name: 'CBP — I-94 Official Website', url: 'https://i94.cbp.dhs.gov/' },
      { name: 'FTC — IdentityTheft.gov', url: 'https://www.identitytheft.gov/' },
      { name: 'AnnualCreditReport.com', url: 'https://www.annualcreditreport.com/' },
      { name: 'Selective Service System', url: 'https://www.sss.gov/register/' },
      { name: 'USCIS — Change of address (AR-11)', url: 'https://www.uscis.gov/addresschange' },
    ],
    relatedScamIds: ['identity-theft', 'notario-fraud', 'gov-impersonation'],
  },
]
