import type { Topic } from '../types'

export const safetyTopics: Topic[] = [
  {
    id: 'topic-scam-shield',
    slug: 'seven-rules-that-stop-scams',
    title: 'Seven rules that stop almost every scam',
    category: 'safety',
    oneLiner:
      'Fraud against immigrants is not clever — it is repetitive. It uses the same five levers every time, and a short list of habits defeats all of them.',
    whyItMatters:
      'Scams in the US are industrialized: 3 million fraud reports and about $15.9 billion in reported losses in 2025 alone, with imposter scams the most reported category for a fifth straight year. For someone still learning how the system works, the scam is indistinguishable from the paperwork — which is exactly the point.',
    keywords: [
      'scam', 'scams', 'fraud', 'is this a scam', 'red flags', 'gift card',
      'wire transfer', 'crypto', 'phishing', 'text message', 'phone call',
      'someone called me', 'they asked for money', 'how to know if scam',
      'report a scam', 'stop scam calls',
    ],
    explain: [
      'Rule 1: nothing real happens in a hurry. Government agencies, banks, courts and utilities do not give you 20 minutes to pay. Urgency is manufactured and it is the single most reliable signal of fraud.',
      'Rule 2: they move you to a private channel. A real agency sends mail or a notice you can verify yourself. A scammer moves you to WhatsApp, Telegram, a personal cell number, or a "secure line". That move exists to get you away from anyone who could warn you.',
      'Rule 3: the payment method is the tell. Gift cards, cryptocurrency, crypto ATMs, prepaid cards, wire transfers to individuals, and payment apps are how the money disappears. No government agency, court, utility, landlord, employer or legitimate business collects payment this way. Ever.',
      'Rule 4: they already know something true about you. Your name, your A-number, your address, your case number — breached data and public records give all of it away. Knowing your details is not evidence that the caller is official.',
      'Rule 5: never call back a number someone gave you. Hang up and dial the number from your own statement, card, or the agency\'s official website. Caller ID is trivially faked, including to look like a government line.',
      'Rule 6: real officials never ask you to keep it secret from your family or bank. Isolation is the scam\'s operational requirement. If someone tells you not to tell anyone — including your spouse, your family, or your bank — you are being robbed.',
      'Rule 7: verify with a second channel, always, before money moves. Not a second person — a second channel. If the message came by text, open the official app or website yourself. If it came by phone, log in from your own browser. This one habit defeats nearly everything.',
      'If money already left: act fast. Report to the platform or bank immediately and say the words "fraudulent transfer" — for some payment types there is a short window to recall funds. Then report at ReportFraud.ftc.gov, contact your bank, freeze your credit, and if personal information was shared, follow the personalized plan at IdentityTheft.gov. Speed matters more than shame. Nobody who was defrauded is stupid; the system is engineered against people in transition.',
    ],
    facts: [
      {
        id: 'f-ftc-2025',
        claim: 'The FTC received about 3 million fraud reports in 2025 with roughly $15.9 billion in reported losses, and imposter scams were the most reported category for the fifth consecutive year.',
        asOf: '2026-04',
        source: { name: 'FTC — Consumer Sentinel Network data', url: 'https://www.ftc.gov/enforcement/consumer-sentinel-network' },
        volatility: 'annual',
      },
      {
        id: 'f-government-impersonation',
        claim: 'Government and business impersonation are among the highest-loss fraud categories, with bank impersonation and government impersonation together accounting for billions in reported losses.',
        asOf: '2026-04',
        source: { name: 'FTC — Consumer Sentinel data book', url: 'https://www.ftc.gov/reports/consumer-sentinel-network-data-book' },
        volatility: 'annual',
      },
      {
        id: 'f-social-media-contact',
        claim: 'Social media is frequently the contact point for scams, with losses originating there exceeding those from phone, text and email in recent data.',
        asOf: '2026-04',
        source: { name: 'FTC — Consumer warnings and data', url: 'https://consumer.ftc.gov/features/scams' },
        volatility: 'annual',
      },
      {
        id: 'f-gift-card-payment',
        claim: 'Government agencies, utilities, courts and legitimate businesses do not accept gift cards, cryptocurrency or prepaid cards as payment for debts, fines or fees.',
        asOf: '2026-09',
        source: { name: 'FTC — Gift card scams', url: 'https://consumer.ftc.gov/articles/gift-card-scams' },
        volatility: 'stable',
      },
      {
        id: 'f-report-fraud',
        claim: 'Fraud can be reported through ReportFraud.ftc.gov, which feeds reports to law enforcement, and identity theft through IdentityTheft.gov, which generates a recovery plan and a formal report.',
        asOf: '2026-09',
        source: { name: 'FTC — Report fraud', url: 'https://reportfraud.ftc.gov/' },
        volatility: 'stable',
      },
      {
        id: 'f-spoofing',
        claim: 'Caller ID and email sender names can be easily spoofed, including to display a government or bank name, so caller ID is not proof of identity.',
        asOf: '2026-09',
        source: { name: 'FCC — Caller ID spoofing and illegal robocalls', url: 'https://www.fcc.gov/consumers/guides/spoofing-and-caller-id' },
        volatility: 'stable',
      },
      {
        id: 'f-donotcall',
        claim: 'You can reduce unwanted calls by adding your number to the National Do Not Call Registry, and by registering with a carrier call-blocking service.',
        asOf: '2026-09',
        source: { name: 'FTC — National Do Not Call Registry', url: 'https://www.donotcall.gov/' },
        volatility: 'annual',
      },
    ],
    jargon: [
      { term: 'Phishing', plain: 'A fake message designed to make you log in or pay.', watchOut: 'Links in texts pretending to be your bank, the post office, or toll authority.' },
      { term: 'Spoofing', plain: 'Faking the sender of a call or email.', watchOut: 'Caller ID showing "USCIS" or your bank.' },
      { term: 'Gift card payment', plain: 'Telling you to buy cards and read the numbers aloud.', watchOut: 'No legitimate organization ever does this.' },
      { term: 'Crypto ATM', plain: 'A machine that converts cash into cryptocurrency.', watchOut: 'Being walked through a "safe deposit" into a crypto ATM. Money sent is unrecoverable.' },
      { term: 'Money mule', plain: 'A person who moves money for criminals.', watchOut: '"Receive this payment and send it on" — that makes you a defendant, not an employee.' },
      { term: 'Remote access', plain: 'Software letting someone else control your computer or phone.', watchOut: '"Tech support" asking you to install something or share your screen.' },
      { term: 'Overpayment scam', plain: 'A fake check for too much, with a request to refund the difference.', watchOut: 'The check bounces days later and the money you sent is gone.' },
      { term: 'Freeze', plain: 'Locking your credit file so nobody can borrow in your name.', watchOut: 'Paying a monthly fee for something the bureaus do free.' },
    ],
    steps: [
      'Agree with yourself now: no payment decisions under time pressure, ever. Say out loud: "I am going to hang up and verify."',
      'Save the real numbers you might need — bank, insurer, landlord, your immigration attorney, utility — in your phone contacts today, so you can call them without asking a stranger for a number.',
      'Place a free security freeze with all three credit bureaus if you are not currently applying for credit.',
      'Turn on transaction alerts in your banking app and check them weekly.',
      'Add your number to the Do Not Call Registry and enable your carrier\'s spam blocking.',
      'Tell two people in your life how these scams work — the strongest protection for a family is a shared rule like "we never send money in response to a message".',
      'If you are defrauded: report to your bank and the platform first (speed matters), then ReportFraud.ftc.gov, then IdentityTheft.gov if personal data was involved.',
    ],
    traps: [
      'Believing a caller because they knew your name, address or case number. That data is for sale.',
      'Calling back the number that called you instead of the number on your own statement.',
      'Being told to keep it secret "because it is an active investigation."',
      'Paying by Zelle, Cash App, Venmo, wire, gift card or crypto to someone you have only met online. These are all effectively cash.',
      'Accepting a "job" that deposits money into your account and asks you to forward it.',
      'Letting a "bank fraud department" walk you through moving money to a "safe account". Banks never do this.',
      'Installing remote-access software for someone who called you claiming to be tech support or your bank.',
      'Paying a fee before receiving money, a prize, a visa or a refund. Legitimate money does not require an upfront payment.',
      'Ignoring scams aimed at your children and elderly relatives, who are often the entry point in a family.',
    ],
    questionsToAsk: [
      'What is your full name, agency, and a case or reference number I can verify through the official website?',
      'What exactly will happen if I hang up and call the official number to confirm?',
      'Why can this only be paid by gift card, wire or cryptocurrency?',
      'Can you mail me this request on letterhead with a notice number?',
      'Why should this be kept secret from my family or my bank?',
    ],
    officialLinks: [
      { name: 'FTC — Report fraud', url: 'https://reportfraud.ftc.gov/' },
      { name: 'FTC — Consumer advice and scam alerts', url: 'https://consumer.ftc.gov/' },
      { name: 'FTC — IdentityTheft.gov', url: 'https://www.identitytheft.gov/' },
      { name: 'FCC — Caller ID spoofing', url: 'https://www.fcc.gov/consumers/guides/spoofing-and-caller-id' },
      { name: 'FTC — Do Not Call Registry', url: 'https://www.donotcall.gov/' },
      { name: 'USA.gov — Scams and fraud', url: 'https://www.usa.gov/scams-and-frauds' },
    ],
    relatedScamIds: [
      'gov-impersonation', 'bank-impersonation', 'fake-check', 'money-mule',
      'romance', 'crypto-investment', 'tech-support', 'delivery-package',
      'toll-text', 'utility-shutoff', 'advance-fee-loan',
    ],
  },

  {
    id: 'topic-money-mule',
    slug: 'never-move-money-for-someone',
    title: 'The "job" that makes you a criminal: receiving and forwarding money',
    category: 'safety',
    oneLiner:
      'Any offer where money arrives in your account and you send it somewhere else is money laundering, and the person prosecuted is you — not the person who sent the message.',
    whyItMatters:
      'This is the fastest way for a newcomer to acquire a criminal record, a frozen account, and an immigration problem in a single week. It arrives disguised as a remote job, a payment processing role, a "package reshipping" job, or a request from someone you met online. It is specifically aimed at people who need income and do not yet recognize the pattern.',
    keywords: [
      'money mule', 'receive and forward money', 'easy job from home', 'remote job',
      'payment processing job', 'keep a percentage', 'deposit this check',
      'reship packages', 'use my account', 'financial agent', 'crypto job',
      'work from home', 'someone sent me money',
    ],
    explain: [
      'Here is the mechanism. A criminal needs a bank account that is not connected to them. They recruit people — often newly arrived immigrants, students, and people who post in job groups — to receive money or checks and forward part of it elsewhere. You keep a "commission". Then the original payment is reversed as fraudulent, the money you forwarded is gone, and your account is closed, your credit is damaged, and you may be charged with money laundering or fraud. If you are a non-citizen, that charge can affect your immigration status for the rest of your life.',
      'The disguises are consistent. "Payment processing agent" or "financial representative" for an overseas company. A "remote assistant" whose first task is handling client payments. A "package forwarding" job where you receive goods bought with stolen cards and reship them. A new online friend or love interest who needs to move money out of another country and will "pay you for the favor". A "crypto arbitrage" scheme where you deposit money into an app and withdraw profits. Each one ends the same way.',
      'The rules that protect you are short. Never let anyone use your bank account. Never deposit a check from someone you do not know personally and trust completely, and never send money back against a check that has not fully cleared — that can take weeks, and banks will reverse it. Never accept money and forward it, for any reason, no matter how convincing the story is. Never open an account "for a company" you have never met in person.',
      'If it has already started: stop immediately, do not send anything further, do not spend the money, and contact your bank to report it. Keep every message. If you have already forwarded funds, tell your bank the same day — speed is the only defense. Then contact a legal aid organization or a criminal defense attorney before speaking to anyone about it, because what you say matters. Being a victim of recruitment is a real defense in many circumstances, but only with a lawyer and evidence.',
    ],
    facts: [
      {
        id: 'f-money-mule-legality',
        claim: 'Depositing funds and forwarding them on behalf of another person can constitute money laundering or fraud, and the account holder — not the recruiter — is the person banks and prosecutors pursue.',
        asOf: '2026-09',
        source: { name: 'FBI — Money mules', url: 'https://www.fbi.gov/how-we-can-help-you/scams-and-safety/common-frauds-and-scams/money-mules' },
        volatility: 'stable',
      },
      {
        id: 'f-fake-check',
        claim: 'In fake check scams, a bank must generally make funds available quickly, but a check can still be returned as fraudulent weeks later, at which point the bank reverses the deposit and the sender is unreachable.',
        asOf: '2026-09',
        source: { name: 'FTC — Fake checks', url: 'https://consumer.ftc.gov/articles/fake-checks' },
        volatility: 'stable',
      },
      {
        id: 'f-job-scam-growth',
        claim: 'Job and employment-agency scam reports nearly tripled between 2020 and 2024, with reported losses rising from about $90 million to about $501 million.',
        asOf: '2025-03',
        source: { name: 'FTC — Top scams of 2024', url: 'https://consumer.ftc.gov/consumer-alerts/2025/03/top-scams-2024' },
        volatility: 'annual',
      },
      {
        id: 'f-immigration-consequences',
        claim: 'Certain criminal offenses, including fraud and money laundering, can make a non-citizen inadmissible or deportable, so a "job" that involves moving money can have permanent immigration consequences.',
        asOf: '2026-09',
        source: { name: 'USCIS — Policy Manual on inadmissibility and criminal grounds', url: 'https://www.uscis.gov/policy-manual' },
        volatility: 'stable',
      },
      {
        id: 'f-reshipping',
        claim: 'Package reshipping jobs that use goods bought with stolen credit cards are a federal crime for the participant, and the "employer" vanishes.',
        asOf: '2026-09',
        source: { name: 'US Postal Inspection Service — Reshipping scams', url: 'https://www.uspis.gov/report' },
        volatility: 'stable',
      },
      {
        id: 'f-ftc-report',
        claim: 'Suspected money mule recruitment can be reported to the FBI\'s Internet Crime Complaint Center and to ReportFraud.ftc.gov.',
        asOf: '2026-09',
        source: { name: 'FBI — Internet Crime Complaint Center (IC3)', url: 'https://www.ic3.gov/' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'Money mule', plain: 'Someone who moves criminal money through their own account, knowingly or not.', watchOut: '"Just receive it and forward it, keep 5%."' },
      { term: 'Fake check', plain: 'A check that bounces after you have already sent money.', watchOut: '"Buy gift cards and send me the codes for the remainder."' },
      { term: 'Reshipping', plain: 'Receiving and forwarding packages bought with stolen cards.', watchOut: '"Work from home receiving packages" — you are the crime scene.' },
      { term: 'Funds availability', plain: 'When your bank lets you use deposited money.', watchOut: 'Confusing "available" with "cleared and real". These are different things.' },
      { term: 'Chargeback / reversal', plain: 'The original victim getting their money back.', watchOut: 'The money comes out of your account when this happens.' },
      { term: 'Account freeze', plain: 'Your bank locks the account during an investigation.', watchOut: 'Losing access to your rent money while a fraud case is investigated.' },
    ],
    steps: [
      'The rule, memorized: money that arrives must never be forwarded. Not a check, not a transfer, not crypto, not gift cards.',
      'Never share your account number, routing number, login, PIN or one-time codes with anyone who contacted you.',
      'If a "job" involves handling money or packages, stop and verify the employer independently: search the company name plus "scam", call the company\'s main number from its official website, and check whether the domain is a lookalike.',
      'If a check arrives that you did not expect, tell your bank before doing anything with it, and do not spend it.',
      'If a friend or online contact asks to use your account "just this once", refuse and end the conversation. Real friends do not ask.',
      'If it has started: stop, contact your bank today, keep all messages and records, and speak to a lawyer before giving any statement.',
      'Warn your family and community. These schemes spread through the same job groups and chat rooms.',
    ],
    traps: [
      'Believing you are safe because you "did not know". Knowledge is not the only test the law applies.',
      'Thinking a bank balance shown in your app is proof the money is real.',
      'Being told you will be paid a percentage, which makes it feel like employment rather than a favor.',
      'Receiving packages at your address for someone else. Your name is now attached to a crime.',
      'Sending the "overpayment" back by gift card, crypto or app transfer.',
      'Using your account for a romantic partner you have never met in person, especially one abroad.',
      'Ignoring a bank\'s warning call and continuing to receive transfers.',
      'Continuing to cooperate after you suspect something, hoping to get paid.',
    ],
    questionsToAsk: [
      'Who is the legal entity employing me, and where is it registered?',
      'Why does this role require me to receive and forward money rather than the company paying me directly?',
      'If this is legitimate, why can the company not receive these funds into its own account?',
      'Can I speak to a current employee and see the company\'s official website and business registration?',
    ],
    officialLinks: [
      { name: 'FBI — Money mules', url: 'https://www.fbi.gov/how-we-can-help-you/scams-and-safety/common-frauds-and-scams/money-mules' },
      { name: 'FTC — Fake checks', url: 'https://consumer.ftc.gov/articles/fake-checks' },
      { name: 'USPIS — Reshipping scams', url: 'https://www.uspis.gov/report' },
      { name: 'FBI — Internet Crime Complaint Center', url: 'https://www.ic3.gov/' },
      { name: 'FTC — Report fraud', url: 'https://reportfraud.ftc.gov/' },
    ],
    relatedScamIds: ['money-mule', 'fake-check', 'job-scam-equipment', 'romance'],
  },

  {
    id: 'topic-identity-theft',
    slug: 'identity-theft-recovery',
    title: 'Someone used your identity: the first 72 hours',
    category: 'safety',
    oneLiner:
      'Identity theft recovery is a defined sequence: report it formally, freeze your credit, dispute the fraudulent accounts, and keep a paper trail that proves you did all three.',
    whyItMatters:
      'New immigrants are targeted precisely because their credit file is thin — a mostly blank file is easier to load with fraud than an established one. And a fraudulent debt can turn into a rejected apartment, a denied loan, an unexpected tax problem, or an embarrassing question in an immigration interview.',
    keywords: [
      'identity theft', 'stolen identity', 'someone opened an account', 'fraud alert',
      'credit freeze', 'dispute', 'ssn stolen', 'tax return rejected', 'hacked',
      'my identity', 'fraudulent account', 'police report',
    ],
    explain: [
      'Do these in order, and keep proof at every step. First, go to IdentityTheft.gov. It generates a recovery plan and an FTC Identity Theft Report, which is the document banks, creditors and police accept. Second, place a free security freeze at all three bureaus — that stops new accounts from being opened. Third, get your free credit reports and mark every account you do not recognize, then dispute them with the bureau and the creditor in writing. Fourth, file a police report in your local jurisdiction, because some creditors require it. Fifth, tell your bank and, if your SSN was compromised, report it.',
      'The tax angle is often the first symptom. If the IRS rejects your return because a return was already filed with your SSN, you are likely a victim, and the IRS has a specific process: file Form 14039 (Identity Theft Affidavit) and follow the IRS identity protection guidance. This also affects ITIN holders occasionally, so do not assume it does not apply to you.',
      'Then close the loop. Change passwords, use unique passwords and two-factor authentication, and check whether your email itself was compromised. That matters because access to your email means access to password resets for everything else — banks, the IRS, USCIS, insurance, and your landlord portal.',
      'One more thing that is easy to miss: keep every document in one folder, dated. Recovery is a bureaucratic process, and the person who wins is the person who can produce: the police report number, the FTC report, the freeze confirmations, and the dispute letters with mailing dates. If you are asked about any of this in an immigration context later, that same folder proves you were a victim rather than a participant.',
    ],
    facts: [
      {
        id: 'f-idtheft-gov-plan',
        claim: 'IdentityTheft.gov produces a personalized recovery plan and an official FTC Identity Theft Report that can be used with credit bureaus, businesses and law enforcement.',
        asOf: '2026-09',
        source: { name: 'FTC — IdentityTheft.gov', url: 'https://www.identitytheft.gov/' },
        volatility: 'stable',
      },
      {
        id: 'f-freeze-free',
        claim: 'Security freezes and one-year fraud alerts are free at all three national credit bureaus, and a freeze can be lifted temporarily when you need credit.',
        asOf: '2026-09',
        source: { name: 'FTC — Place a security freeze', url: 'https://consumer.ftc.gov/articles/place-security-freeze-your-credit-file' },
        volatility: 'annual',
      },
      {
        id: 'f-irs-idtheft',
        claim: 'If your tax return is rejected because a return was already filed using your SSN, the IRS directs you to file Form 14039, Identity Theft Affidavit, and to follow the identity protection process.',
        asOf: '2026-09',
        source: { name: 'IRS — Identity theft victim assistance', url: 'https://www.irs.gov/individuals/identity-protection' },
        volatility: 'annual',
      },
      {
        id: 'f-dispute-rights',
        claim: 'You have the right to dispute inaccurate information with credit bureaus, which must generally investigate and respond within 30 days, and to dispute directly with the furnisher of the information.',
        asOf: '2026-09',
        source: { name: 'Consumer Financial Protection Bureau — Disputing credit report errors', url: 'https://www.consumerfinance.gov/ask-cfpb/how-do-i-dispute-an-error-on-my-credit-report-en-314/' },
        volatility: 'stable',
      },
      {
        id: 'f-ssn-identity',
        claim: 'If your Social Security number has been misused, the Social Security Administration and the FTC both publish step-by-step guidance, including when to consider a replacement number (which is rarely issued).',
        asOf: '2026-09',
        source: { name: 'SSA — Identity theft and your Social Security number', url: 'https://www.ssa.gov/ssnumber/scams.html' },
        volatility: 'stable',
      },
      {
        id: 'f-credit-monitoring-free',
        claim: 'Monitoring your own reports is free through AnnualCreditReport.com from all three bureaus, and reviewing them regularly is the standard way to detect identity theft.',
        asOf: '2026-09',
        source: { name: 'Consumer Financial Protection Bureau — Free credit reports', url: 'https://www.consumerfinance.gov/consumer-tools/credit-reports-and-scores/' },
        volatility: 'annual',
      },
    ],
    jargon: [
      { term: 'Fraud alert', plain: 'A notice on your credit file asking lenders to verify identity before extending credit.', watchOut: 'Paying for one. It is free.' },
      { term: 'Security freeze', plain: 'A lock on your credit file.', watchOut: 'Not knowing you can lift it temporarily for a specific lender.' },
      { term: 'Furnisher', plain: 'The company that reported the account to the credit bureau.', watchOut: 'Disputing only with the bureau and never with the creditor.' },
      { term: 'Identity Theft Report', plain: 'The FTC\'s official report proving you are a victim.', watchOut: 'Not filing one, then having no document to show anyone.' },
      { term: 'Form 14039', plain: 'The IRS identity theft affidavit.', watchOut: 'Waiting a year to resolve a rejected tax return.' },
      { term: 'Account takeover', plain: 'Someone logging into your existing account rather than opening a new one.', watchOut: 'Using the same password everywhere.' },
    ],
    steps: [
      'Report at IdentityTheft.gov and print the Identity Theft Report today. Keep the PDF.',
      'Place a security freeze at Equifax, Experian and TransUnion — free — and save the confirmation numbers.',
      'Pull all three free credit reports and mark every unrecognized account, inquiry or address.',
      'Dispute each fraudulent item with the bureau and separately with the creditor or lender, in writing, and keep copies.',
      'File a police report locally; get the report number.',
      'If the SSN was used for employment or taxes, report to the IRS using Form 14039 and follow the SSA guidance.',
      'Change all passwords, enable two-factor authentication, and check for changes to your mailing address and bank details.',
      'Check in 30, 60 and 90 days to confirm the fraudulent items are removed and that no new ones appeared.',
    ],
    timeline: [
      { when: 'Day 0', what: 'IdentityTheft.gov report + freeze all three bureaus.' },
      { when: 'Day 1–3', what: 'Pull reports, list fraudulent accounts, file police report.' },
      { when: 'Day 3–7', what: 'Send written disputes to bureaus and creditors. Notify banks. File IRS Form 14039 if tax-related.' },
      { when: 'Day 30', what: 'Follow up on disputes. Bureaus must generally respond within 30 days.' },
      { when: 'Day 60–90', what: 'Verify removals. Re-check reports and bank activity.' },
      { when: 'Ongoing', what: 'Keep freezes in place when not applying for credit; review reports every few months.' },
    ],
    traps: [
      'Paying an "identity theft protection" service before doing the free steps that legally resolve it.',
      'Not filing the FTC report because you are embarrassed, then having no official document.',
      'Only disputing with the credit bureau and never with the company that reported the debt.',
      'Ignoring a rejected tax return for months, letting the refund be delayed a full year.',
      'Using the same password across banking, email and USCIS accounts.',
      'Giving your SSN to a "verification" caller to "confirm the fraud". That is how the second theft happens.',
      'Assuming it cannot happen because your file is empty. An empty file is the easiest target.',
      'Not checking whether your address was changed on your accounts, which lets the thief persist.',
    ],
    questionsToAsk: [
      'Which accounts and inquiries are listed that I never authorized?',
      'What is the deadline for the bureau to respond to my dispute?',
      'Do you require a police report or an FTC Identity Theft Report to remove this account?',
      'Can you confirm in writing that the fraudulent account has been removed?',
      'Should I be concerned about my immigration case if my SSN was misused by someone else?',
    ],
    officialLinks: [
      { name: 'FTC — IdentityTheft.gov', url: 'https://www.identitytheft.gov/' },
      { name: 'FTC — Security freezes', url: 'https://consumer.ftc.gov/articles/place-security-freeze-your-credit-file' },
      { name: 'IRS — Identity protection', url: 'https://www.irs.gov/individuals/identity-protection' },
      { name: 'AnnualCreditReport.com', url: 'https://www.annualcreditreport.com/' },
      { name: 'CFPB — Disputing credit report errors', url: 'https://www.consumerfinance.gov/ask-cfpb/how-do-i-dispute-an-error-on-my-credit-report-en-314/' },
    ],
    relatedScamIds: ['identity-theft', 'bank-impersonation', 'irs-impersonation', 'ssn-for-sale'],
  },

  {
    id: 'topic-immigration-services-fraud',
    slug: 'immigration-services-fraud',
    title: 'Immigration services fraud: the specific schemes aimed at you',
    category: 'safety',
    oneLiner:
      'Fraud targeting immigrants is a category of its own, with recognizable names: notario fraud, visa fee scams, fake sponsors, fake marriage brokers, and "case officer" calls.',
    whyItMatters:
      'Immigration scams do the most damage of any fraud in this library, because the loss is not only money — it is time you cannot recover (a missed filing deadline) and a record that follows you into future applications. Knowing the named schemes is genuinely protective, because each one has a standard script.',
    keywords: [
      'notario', 'immigration scam', 'visa scam', 'green card scam', 'fake sponsor',
      'asylum fee', 'work permit scam', 'uscis called me', 'visa agent',
      'fake lawyer', 'marriage green card', 'lottery visa', 'immigration fraud',
    ],
    explain: [
      'Notario fraud. In many Latin American countries a "notario público" is a senior legal professional, so using the title in the US is a deliberate trap. A US notary public cannot give immigration advice or select forms. The FTC names this category explicitly.',
      'Fake government fees. Someone calls or emails posing as USCIS, ICE, or a "Department of Immigration" that does not exist, saying your case has a problem and a fee will fix it. Variations: a fee to "expedite" your work permit, a fee to "release" your green card, a fee because you "missed a deadline", a fee to avoid deportation. USCIS never collects payment by phone, gift card, crypto or payment app, and there is no such thing as a fee that only the caller can accept.',
      'Fake sponsorship. A "sponsor" offers to file for you, sometimes using religious-sounding language, in exchange for a large payment or a cut of your future wages. Alternatively an employer offers a visa in exchange for money and takes your passport. Both are forms of trafficking when money and documents are used as leverage, and both are prosecuted.',
      'Lottery and "expedited" schemes. Promises of a visa lottery win, or a guaranteed asylum approval for a fee. Note the difference between legitimate and fraudulent: legitimate processes have published forms, published fees, official receipts, and a case number you can verify yourself.',
      'The structural defense is the same every time. Verify that the person advising you is a licensed attorney or a DOJ-accredited representative. Get a written agreement and receipts for everything. Keep copies of every filing yourself, and never hand over original documents to be "held". And remember that the government already gives you free tools to check your own case: case status online with a receipt number, and the immigration court hotline with an A-number.',
    ],
    facts: [
      {
        id: 'f-notario-named',
        claim: 'The FTC identifies immigration services scams, including notario fraud, as a recurring fraud category in which unlicensed people sell legal services they are not allowed to provide.',
        asOf: '2026-09',
        source: { name: 'FTC — Immigration services scams', url: 'https://consumer.ftc.gov/articles/immigration-services-scams' },
        volatility: 'stable',
      },
      {
        id: 'f-uscis-no-phone-payment',
        claim: 'USCIS does not call to demand payment and does not accept payment by gift card, cryptocurrency, wire transfer or payment app; its site publishes the official payment methods and fee schedule.',
        asOf: '2026-09',
        source: { name: 'USCIS — Avoid Scams', url: 'https://www.uscis.gov/avoid-scams' },
        volatility: 'stable',
      },
      {
        id: 'f-uscis-verify-case',
        claim: 'You can verify essentially any USCIS claim yourself using the receipt number on official notices, which makes "the officer called me" a verifiable statement rather than a threat.',
        asOf: '2026-09',
        source: { name: 'USCIS — Case Status Online', url: 'https://egov.uscis.gov/casestatus' },
        volatility: 'stable',
      },
      {
        id: 'f-no-private-visa',
        claim: 'There is no private person, agency or agent through which a visa can be bought or guaranteed; the diversity visa program runs through an official government registration process with no fee to enter that flows through a private intermediary.',
        asOf: '2026-09',
        source: { name: 'US Department of State — Diversity Visa Program', url: 'https://travel.state.gov/content/travel/en/us-visas/immigrate/diversity-visa-program-entry.html' },
        volatility: 'annual',
      },
      {
        id: 'f-trafficking-documents',
        claim: 'Withholding a worker\'s passport or immigration documents to compel work is a form of human trafficking, and the National Human Trafficking Hotline can be contacted confidentially.',
        asOf: '2026-09',
        source: { name: 'National Human Trafficking Hotline', url: 'https://humantraffickinghotline.org/' },
        volatility: 'stable',
      },
      {
        id: 'f-t-visa',
        claim: 'Victims of certain crimes and of human trafficking may be eligible for immigration relief, including T and U visas, which exist precisely to allow victims to report without losing status.',
        asOf: '2026-09',
        source: { name: 'USCIS — Victims of trafficking and other crimes (T and U visas)', url: 'https://www.uscis.gov/humanitarian/victims-of-human-trafficking-and-other-crimes' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'Notario', plain: 'A notary in the US — signature witness, not a lawyer.', watchOut: 'Anyone using the title to sell immigration advice.' },
      { term: 'Sponsor', plain: 'A person or employer who files or supports an immigration petition.', watchOut: 'A sponsor who wants your passport, cash, or your wages as payment.' },
      { term: 'Case officer', plain: 'A USCIS employee who may call about a case in limited circumstances.', watchOut: 'A "case officer" demanding immediate payment to save your case.' },
      { term: 'A-number', plain: 'Your immigration file number.', watchOut: 'Scammers using it for credibility. Your own case is verifiable regardless.' },
      { term: 'T and U visas', plain: 'Immigration protection for trafficking and crime victims who cooperate.', watchOut: 'Not knowing they exist, so you stay in an exploitative situation.' },
      { term: 'Passport retention', plain: 'Someone holding your passport as leverage.', watchOut: 'This is a trafficking indicator, and it is a crime.' },
    ],
    steps: [
      'Verify any immigration "professional" against the state bar or the DOJ recognition and accreditation list before paying anything.',
      'Get everything in writing: scope of work, total fees, who is filing what, and what happens if the case is denied.',
      'Never pay a government fee to an individual. Pay government fees through official channels and keep the receipt.',
      'Keep copies of every form, receipt and notice. Verify case status yourself at egov.uscis.gov/casestatus.',
      'Never surrender original documents to be held as collateral. Show copies, keep originals.',
      'If someone is holding your passport or threatening your status to make you work or pay: contact the National Human Trafficking Hotline or a legal aid organization with immigration expertise. T and U visas exist for exactly this situation.',
      'Report immigration fraud to the FTC, your state attorney general, and — where a scammer is falsely impersonating an official — to USCIS through its scam reporting channel.',
    ],
    traps: [
      'Paying a notary or an "immigration consultant" for legal advice about which form to file.',
      'Paying a fee to "expedite" a case that has not been filed yet.',
      'Giving a "sponsor" your original passport, birth certificate or I-94.',
      'Believing a scammer\'s warning that you missed a deadline, without checking case status yourself with your receipt number.',
      'Signing blank forms so someone else can "fill them in later".',
      'Being told a marriage-based petition can be arranged for a fee. That is marriage fraud, a permanent bar to benefits.',
      'Continuing in an exploitative job because the employer holds your documents. Trafficking protections exist for this.',
      'Not telling anyone because of shame. Every one of these schemes depends on silence.',
    ],
    questionsToAsk: [
      'Are you a licensed attorney or DOJ-accredited representative, and what is your number?',
      'What form are you filing, what is the government fee, and how do I pay the government directly?',
      'Will I receive copies of everything you file, plus every receipt notice?',
      'What is the receipt number, so I can verify the case myself?',
      'Who did you say you work for, and what is the official website where I can confirm that?',
    ],
    officialLinks: [
      { name: 'USCIS — Avoid Scams', url: 'https://www.uscis.gov/avoid-scams' },
      { name: 'FTC — Immigration services scams', url: 'https://consumer.ftc.gov/articles/immigration-services-scams' },
      { name: 'DOJ — Recognition and Accreditation Program', url: 'https://www.justice.gov/eoir/recognition-and-accreditation-program' },
      { name: 'National Human Trafficking Hotline', url: 'https://humantraffickinghotline.org/' },
      { name: 'USCIS — T and U visas', url: 'https://www.uscis.gov/humanitarian/victims-of-human-trafficking-and-other-crimes' },
    ],
    relatedScamIds: ['notario-fraud', 'gov-impersonation', 'fake-uscis-fee', 'fake-sponsor', 'marriage-fraud', 'visa-lottery'],
  },

  {
    id: 'topic-driver-license',
    slug: 'driver-license-and-state-id',
    title: 'Getting a driver license or state ID',
    category: 'paperwork',
    oneLiner:
      'A state ID or driver license is the everyday proof of identity in the US, some states issue them without regard to immigration status, and every state requires proof of identity plus proof of residency.',
    whyItMatters:
      'Without a state ID, routine life becomes hard: renting, banking, picking up a prescription, entering a building, proving your address. And because the requirements differ by state and status, people pay "agents" for appointments and documents they can get themselves.',
    keywords: [
      'driver license', 'drivers license', 'state id', 'dmv', 'real id',
      'appointment', 'written test', 'road test', 'foreign license', 'learner permit',
      'no ssn license', 'undocumented license', 'proof of residency',
    ],
    explain: [
      'The general shape is the same everywhere: prove who you are, prove you live in the state, pass a knowledge test and a road test if you are getting a license, and pay a fee. What varies enormously is which documents are accepted as proof of identity and lawful presence — and a handful of states, plus Washington DC, issue licenses or IDs to residents regardless of immigration status.',
      'Real ID is the part that confuses people. REAL ID is a federal standard for state-issued IDs, and starting in May 2025 a REAL ID or another acceptable document (like a passport) is required for certain federal purposes, including boarding domestic flights and entering certain federal facilities. If you are eligible, getting a REAL ID saves you from carrying your passport everywhere; if you are not eligible, you may still get a standard license that is valid for driving but not for federal identification purposes.',
      'For the tests, do not overthink them: the state publishes the driver handbook, and the written test comes directly from it, and many states offer it in multiple languages. Practice with the official handbook rather than an app that might be wrong. For the road test, if you have been driving for years in another country, you still need to demonstrate the local habits — right turns on red, stop sign behavior, and highway merging are where experienced foreign drivers fail.',
      'Two warnings. First, never pay a stranger for a DMV appointment or for "help passing" — appointments are free through the state website, and paying someone to take a test for you is fraud with permanent consequences. Second, drive only with a valid license and insurance. Driving without them in the US is not a minor administrative issue: it can lead to arrest, vehicle impound, and immigration consequences.',
    ],
    facts: [
      {
        id: 'f-real-id-date',
        claim: 'Since May 7, 2025, US travelers need a REAL ID-compliant license/ID or another acceptable document such as a passport for domestic air travel and entry to certain federal facilities.',
        asOf: '2025-05-07',
        source: { name: 'DHS — REAL ID', url: 'https://www.dhs.gov/real-id' },
        volatility: 'stable',
      },
      {
        id: 'f-state-requirements',
        claim: 'Driver license and state ID requirements — including accepted proof of identity, residency and lawful presence — are set by each state, and the official list is published by the state licensing agency.',
        asOf: '2026-09',
        source: { name: 'USA.gov — Driver licenses and state IDs', url: 'https://www.usa.gov/motor-vehicle-services' },
        volatility: 'annual',
      },
      {
        id: 'f-license-regardless-status',
        claim: 'A number of states and the District of Columbia issue driver licenses or state IDs to residents who cannot prove lawful presence, with the document usually marked as not usable for federal identification purposes.',
        detail:
          'Which states do this, and what the license can be used for, changes with state law and elections. Confirm on your state licensing agency\'s own website.',
        asOf: '2026-09',
        source: { name: 'National Conference of State Legislatures — State laws on driver licenses for immigrants', url: 'https://www.ncsl.org/immigration' },
        volatility: 'annual',
      },
      {
        id: 'f-driving-without-license',
        claim: 'Driving without a valid license or insurance can result in arrest, fines, license suspension and vehicle impound, and in some circumstances can affect immigration proceedings.',
        asOf: '2026-09',
        source: { name: 'USA.gov — Motor vehicle services and requirements', url: 'https://www.usa.gov/motor-vehicle-services' },
        volatility: 'stable',
      },
      {
        id: 'f-dmv-appointments-free',
        claim: 'DMV appointments are free through official state websites; third parties charging for appointment access are unnecessary and often fraudulent.',
        asOf: '2026-09',
        source: { name: 'USA.gov — Driver licenses and state IDs', url: 'https://www.usa.gov/motor-vehicle-services' },
        volatility: 'stable',
      },
      {
        id: 'f-handbook',
        claim: 'Each state publishes an official driver handbook that is the source for the written knowledge test, and many states offer the handbook and the test in multiple languages.',
        asOf: '2026-09',
        source: { name: 'USA.gov — Driver licenses and state IDs', url: 'https://www.usa.gov/motor-vehicle-services' },
        volatility: 'annual',
      },
    ],
    jargon: [
      { term: 'REAL ID', plain: 'A federal standard for state IDs, needed for domestic flights and some federal buildings.', watchOut: 'Paying an agency to "upgrade" you when you can do it at the DMV.' },
      { term: 'Proof of residency', plain: 'Documents showing you live in the state: lease, utility bill, bank statement.', watchOut: 'Not having two documents in your own name, which stalls the application.' },
      { term: 'Knowledge test', plain: 'The written test, based on the official handbook.', watchOut: 'Studying from a random app instead of the state handbook.' },
      { term: 'Learner permit', plain: 'A limited license for practicing with a supervising driver.', watchOut: 'Driving alone on a permit, which counts as driving without a license.' },
      { term: 'Points', plain: 'A system where violations add points and can suspend your license.', watchOut: 'Not contesting a ticket you did not deserve, and accumulating points.' },
      { term: 'Impound', plain: 'Your car being towed and held by authorities.', watchOut: 'Driving unlicensed or uninsured and losing the car you need for work.' },
      { term: 'Consular ID', plain: 'An ID card from your country\'s consulate, accepted by some agencies and banks.', watchOut: 'Assuming it substitutes for a state ID everywhere. It does not.' },
    ],
    steps: [
      'Go to your state licensing agency\'s official website and read the document checklist for your exact situation. Print it.',
      'Gather identity documents, proof of residency (two documents are often required), and your SSN or ITIN if you have one.',
      'If you have a foreign license, check whether your state allows it to be exchanged or accepts it after a road test only.',
      'Study the official handbook and take the knowledge test. Ask whether it is available in a language you read.',
      'Book the road test online for free, and consider a licensed driving school — for new drivers, not for a "guaranteed pass" from a stranger.',
      'Buy the minimum required insurance before you drive, and keep proof of insurance in the car.',
      'Renew on time. A lapsed license plus an accident can create a cascade of legal and immigration problems.',
    ],
    traps: [
      'Paying a third party for a DMV appointment that is free on the state website.',
      'Paying someone to take the test for you. This is fraud and can permanently damage your record.',
      'Driving with a foreign license long after it stops being valid in the state, without checking the rules.',
      'Driving without insurance to save money. One accident becomes a criminal and financial problem.',
      'Buying insurance online from an unlicensed seller, then discovering the policy does not exist at the moment of a crash.',
      'Not updating your address with the DMV and the US Postal Service after moving (and for immigrants, not filing AR-11).',
      'Assuming a consular ID works everywhere a state ID does.',
    ],
    questionsToAsk: [
      'What documents do you accept as proof of identity and residency for someone with my status?',
      'Is the knowledge test available in my language?',
      'Can I use my foreign license to get a license here, and does it need a translation or certification?',
      'Will this license be REAL ID-compliant, and what can I use it for?',
      'What are the fees, and how long is the appointment wait right now?',
    ],
    officialLinks: [
      { name: 'USA.gov — Driver licenses and state IDs', url: 'https://www.usa.gov/motor-vehicle-services' },
      { name: 'DHS — REAL ID information', url: 'https://www.dhs.gov/real-id' },
      { name: 'USA.gov — State motor vehicle agencies', url: 'https://www.usa.gov/state-motor-vehicle-services' },
      { name: 'NCSL — Immigration and state licensing laws', url: 'https://www.ncsl.org/immigration' },
    ],
    relatedScamIds: ['license-fraud', 'insurance-scam', 'gov-impersonation'],
  },
]
