import type { Topic } from '../types'

export const workTopics: Topic[] = [
  {
    id: 'topic-first-job-rights',
    slug: 'your-rights-at-work',
    title: 'Your rights at work: pay, hours, overtime and pay stubs',
    category: 'work',
    oneLiner:
      'US wage law applies to you based on whether you work, not on your immigration status — and the rules about minimum wage, overtime, breaks and pay statements are the same for citizens and immigrants.',
    whyItMatters:
      'Newcomers are the most common victims of wage theft because they are the least likely to complain: they do not know the numbers, they fear losing the job, and employers know it. Restaurants, construction, cleaning, delivery, agriculture and home care are where most of this happens.',
    keywords: [
      'minimum wage', 'overtime', 'paycheck', 'pay stub', 'wages', 'hourly',
      'tips', 'tipped wage', 'unpaid overtime', 'breaks', 'work hours',
      'under the table', 'cash job', 'tax withholding', 'independent contractor',
      'gig work', 'salary', 'worker rights',
    ],
    explain: [
      'Two numbers decide a large share of your income: the minimum wage and the overtime multiplier. The federal minimum wage is a floor, and states and cities can set higher ones — where they do, the higher rate generally applies. Overtime is the standard above 40 hours worked in a week for most hourly employees: hours past 40 must generally be paid at one and a half times your regular rate. The rule is per week, not per day, and it is based on hours actually worked — being "on the clock" is not a formality.',
      'Pay statements matter more than people realize. In most states you are entitled to a written record of hours, rate, gross pay and deductions each pay period. That statement is your evidence if you are underpaid. So is your own record: write down your start and end times on your phone, every shift, for yourself. Wage claims are usually won by whoever has records.',
      'The classification issue is the big quiet theft. Employers sometimes call workers "independent contractors" to avoid overtime, payroll taxes and unemployment insurance, while still controlling their schedule and how they work. If you are a 1099 contractor in name but a employee in practice, you may be owed money. Similarly, being paid "off the books" all in cash feels convenient until you need proof of income for a lease, a loan, or an immigration case — and until you are injured and discover there is no workers\' compensation coverage.',
      'Finally, retaliation is illegal. Employers may not fire you, cut your hours or threaten you with immigration consequences for complaining about unpaid wages. If that happens, get it in writing (a text message is evidence) and contact the state labor office or the US Department of Labor\'s Wage and Hour Division. Also know this: the Department of Labor enforces wage law for all workers regardless of immigration status, and it does not report workers to immigration authorities as part of wage investigations.',
    ],
    facts: [
      {
        id: 'f-min-wage',
        claim: 'The federal minimum wage is $7.25 per hour, and states and localities may set a higher minimum that applies instead; the applicable rate is the higher of the federal, state or local minimum.',
        asOf: '2026-09',
        source: { name: 'US Department of Labor — Minimum wage', url: 'https://www.dol.gov/agencies/whd/minimum-wage' },
        volatility: 'annual',
      },
      {
        id: 'f-overtime',
        claim: 'For most covered employees, hours worked beyond 40 in a workweek must be paid at not less than one and one-half times the regular rate.',
        asOf: '2026-09',
        source: { name: 'US Department of Labor — Overtime pay', url: 'https://www.dol.gov/agencies/whd/overtime' },
        volatility: 'stable',
      },
      {
        id: 'f-dol-status-immaterial',
        claim: 'Wage and hour protections apply to workers regardless of immigration status, and the Department of Labor enforces wage laws for all covered employees.',
        asOf: '2026-09',
        source: { name: 'US Department of Labor — Wage and Hour Division immigration information', url: 'https://www.dol.gov/agencies/whd/immigration' },
        volatility: 'stable',
      },
      {
        id: 'f-retaliation',
        claim: 'It is illegal for an employer to retaliate against you — including by firing, threatening or reporting you — for asserting your wage rights or cooperating with a wage investigation.',
        asOf: '2026-09',
        source: { name: 'US Department of Labor — Retaliation and whistleblower protections', url: 'https://www.dol.gov/agencies/whd/retaliation' },
        volatility: 'stable',
      },
      {
        id: 'f-paystub',
        claim: 'Most states require employers to provide written or electronic pay statements itemizing hours, rates and deductions, and pay records must generally be kept by the employer.',
        asOf: '2026-09',
        source: { name: 'US Department of Labor — Recordkeeping requirements under the FLSA', url: 'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping' },
        volatility: 'stable',
      },
      {
        id: 'f-tipped-wage',
        claim: 'For tipped employees, employers may credit tips toward wages up to a limit, but if tips plus the cash wage do not reach the full minimum wage, the employer must make up the difference.',
        asOf: '2026-09',
        source: { name: 'US Department of Labor — Tipped workers (dual jobs and tip credit)', url: 'https://www.dol.gov/agencies/whd/tipped-workers' },
        volatility: 'annual',
      },
      {
        id: 'f-misclassification',
        claim: 'Misclassifying employees as independent contractors deprives them of minimum wage, overtime, workers\' compensation and unemployment insurance, and the Department of Labor investigates such cases.',
        asOf: '2026-09',
        source: { name: 'US Department of Labor — Independent contractor misclassification', url: 'https://www.dol.gov/agencies/whd/flsa/misclassification' },
        volatility: 'stable',
      },
      {
        id: 'f-whd-complaint',
        claim: 'You can file a wage complaint with the US Department of Labor\'s Wage and Hour Division by phone or online, in multiple languages, at no cost.',
        asOf: '2026-09',
        source: { name: 'US Department of Labor — File a wage complaint', url: 'https://www.dol.gov/agencies/whd/contact/complaints' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'Gross pay vs net pay', plain: 'Gross is before deductions; net is what reaches your account.', watchOut: 'An employer discussing only net pay so you never notice missing overtime.' },
      { term: 'Pay stub', plain: 'Your record of hours, rate and deductions.', watchOut: 'No pay stubs at all, meaning no evidence of anything.' },
      { term: 'Overtime', plain: '1.5x your rate for hours over 40 in a week (most workers).', watchOut: 'Being told you are "salaried" so there is no overtime, while you are paid hourly in practice.' },
      { term: 'Off the books', plain: 'Paid in cash with no record or withholding.', watchOut: 'No proof of income, no unemployment insurance, no workers\' comp if you are injured.' },
      { term: 'Contractor / 1099', plain: 'Paid without tax withholding, and responsible for your own taxes.', watchOut: 'Being called a contractor while being treated like an employee.' },
      { term: 'Tip credit', plain: 'Employers counting your tips toward the minimum wage.', watchOut: 'Your tips bringing you below minimum wage and nobody topping it up.' },
      { term: 'Tip pooling', plain: 'Tips shared among staff.', watchOut: 'Managers and owners taking a share of the pool — often illegal.' },
      { term: 'Wage theft', plain: 'Being paid less than the law requires — including unpaid overtime and off-clock work.', watchOut: 'Being told it is normal. It is theft, and it is prosecutable.' },
    ],
    steps: [
      'Find out your applicable minimum wage: federal, state and city — the highest one applies to you.',
      'Start your own private record today: every shift, start and end time, breaks, and what you were paid. A phone note is enough.',
      'Get copies of every pay stub and compare hours and rate against your own record. Raise discrepancies in writing, not verbally.',
      'If you are paid in cash, ask for a written receipt or a pay statement anyway. If the employer refuses, keep a second record of dates and amounts.',
      'If you are called a contractor, check whether you really control your own work. If you are scheduled, supervised and given the tools, ask why you are 1099.',
      'If wages are withheld or overtime is unpaid, file a complaint with your state labor office or the Department of Labor, and keep copies of everything.',
      'Never destroy evidence. Screenshots, texts and photos of schedules are the core of a wage claim.',
    ],
    timeline: [
      { when: 'Day 1 of the job', what: 'Confirm your rate, pay day, hours and whether you are hourly or salaried — in writing if possible.' },
      { when: 'Every shift', what: 'Record your own hours and breaks.' },
      { when: 'Every payday', what: 'Check the pay stub against your record. Raise problems immediately, in writing.' },
      { when: 'Annually', what: 'Keep W-2s and pay stubs for at least three years. Keep tax returns indefinitely.' },
      { when: 'If you leave or are fired', what: 'Request your final pay and a copy of your personnel file where state law allows it.' },
    ],
    traps: [
      'Accepting "we pay you cash, no questions" and losing all proof of income and legal protection.',
      'Working unpaid "training" or off-the-clock hours because the manager asks.',
      'Being told overtime is only paid over 8 hours in a day, when the rule is usually 40 in a week.',
      'Not keeping your own hours, then having no evidence when you are underpaid.',
      'Signing an arbitration agreement or a "no talking about pay" policy and assuming you have no rights. You still have rights, and consulting an employment lawyer is confidential.',
      'Being threatened with immigration consequences for demanding wages. Being deported for complaining is not a real legal consequence — retaliation is illegal.',
      'Paying an employer for "training" or "equipment" that never materializes. Legitimate jobs do not charge you to work.',
      'Doing a "trial day" for free, repeatedly, at multiple employers.',
    ],
    questionsToAsk: [
      'What is my hourly rate, and when is payday?',
      'Am I an employee or a contractor, and why?',
      'How is overtime calculated here, and is there a written policy?',
      'Can I get a pay stub every period showing hours, rate and deductions?',
      'Do you carry workers\' compensation insurance?',
      'Where is the written wage policy, and what language is it in?',
    ],
    officialLinks: [
      { name: 'DOL — Wage and Hour Division (file a complaint)', url: 'https://www.dol.gov/agencies/whd/contact/complaints' },
      { name: 'DOL — Minimum wage', url: 'https://www.dol.gov/agencies/whd/minimum-wage' },
      { name: 'DOL — Overtime and hours worked', url: 'https://www.dol.gov/agencies/whd/overtime' },
      { name: 'DOL — Immigrant workers and wage protections', url: 'https://www.dol.gov/agencies/whd/immigration' },
      { name: 'DOL — Retaliation protections', url: 'https://www.dol.gov/agencies/whd/retaliation' },
    ],
    relatedScamIds: ['job-scam-equipment', 'visa-job-scam', 'money-mule', 'unpaid-training'],
  },

  {
    id: 'topic-wage-theft',
    slug: 'unpaid-wages',
    title: 'If your employer is not paying you: the actual process',
    category: 'work',
    oneLiner:
      'There are two parallel complaint systems — the state labor office and the federal Wage and Hour Division — and both let you file for free, in your own language, and without regard to your immigration status.',
    whyItMatters:
      'Wage theft is the largest form of theft in the US by dollar value, and it lands hardest on immigrant workers. Most people never file because they assume filing will get them deported, that it costs money, or that they need a lawyer. None of that is true.',
    keywords: [
      'unpaid wages', 'wage theft', 'didnt pay me', 'last paycheck', 'fired',
      'final pay', 'overtime not paid', 'complaint', 'labor board', 'dol',
      'department of labor', 'retaliation', 'threatened', 'small claims wages',
    ],
    explain: [
      'The process starts with evidence, not with anger. Before you file, gather: your own hours log, pay stubs or bank deposits, texts or messages about your schedule and pay, the name of the company and the legal name of the owner if you can find it, the address, and the names of coworkers who saw what happened. Coworkers can support your claim, and in many cases they can file with you — that makes retaliation harder.',
      'Then pick a channel. State labor offices handle state wage law, often quickly and with small claims, and some states have dedicated wage theft units with stronger penalties. The federal Wage and Hour Division handles federal minimum wage and overtime claims and can investigate an employer even if you are one of many workers. Filing with one does not automatically block the other, but you generally cannot recover the same money twice, so tell each office what you have already done.',
      'The most important thing to know is what the law says about your status. The Department of Labor enforces wage law regardless of immigration status and does not report workers to immigration authorities as part of a wage investigation. That is official policy, stated on the agency\'s own website. Retaliation — firing you, threatening you, cutting your hours, or telling you that you will be deported if you complain — is itself illegal and is a separate claim.',
      'And if a lawsuit or small claims court is necessary, some employment lawyers work on contingency, meaning you pay only if you win. Legal aid organizations and worker centers also handle wage cases and often have staff who speak your language. You do not need money to start; you need a folder.',
    ],
    facts: [
      {
        id: 'f-whd-any-status',
        claim: 'All covered employees are protected by federal wage law regardless of immigration status, and the Wage and Hour Division does not use wage investigations to enforce immigration law.',
        asOf: '2026-09',
        source: { name: 'US Department of Labor — Wage and Hour Division: immigration', url: 'https://www.dol.gov/agencies/whd/immigration' },
        volatility: 'stable',
      },
      {
        id: 'f-retaliation-illegal',
        claim: 'Retaliation against an employee for filing a wage complaint — including discharge, threats, or reporting the worker to immigration authorities — is prohibited.',
        asOf: '2026-09',
        source: { name: 'US Department of Labor — Retaliation', url: 'https://www.dol.gov/agencies/whd/retaliation' },
        volatility: 'stable',
      },
      {
        id: 'f-whd-free',
        claim: 'Filing a wage complaint with the Wage and Hour Division is free, and the agency provides services in multiple languages.',
        asOf: '2026-09',
        source: { name: 'DOL — Contact the Wage and Hour Division', url: 'https://www.dol.gov/agencies/whd/contact' },
        volatility: 'stable',
      },
      {
        id: 'f-final-paycheck',
        claim: 'Many states require payment of final wages within a set number of days after termination, and failure can trigger penalties on top of the wages owed.',
        asOf: '2026-09',
        source: { name: 'US Department of Labor — State labor offices', url: 'https://www.dol.gov/agencies/whd/state/contacts' },
        volatility: 'annual',
      },
      {
        id: 'f-small-claims-wage',
        claim: 'Small claims courts can resolve wage disputes under a state-set dollar limit, usually without a lawyer.',
        asOf: '2026-09',
        source: { name: 'USA.gov — Small claims court', url: 'https://www.usa.gov/small-claims-court' },
        volatility: 'annual',
      },
      {
        id: 'f-record-keeping',
        claim: 'Employers are required to keep payroll records, which is one reason a complaint can succeed even when the worker has no pay stubs.',
        asOf: '2026-09',
        source: { name: 'DOL — Recordkeeping requirements under the FLSA', url: 'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'Wage claim / complaint', plain: 'Your formal request that a government agency make your employer pay.', watchOut: 'Paying someone to "file for you". The agencies take complaints directly.' },
      { term: 'Back wages', plain: 'The money you should have been paid.', watchOut: 'Accepting a partial cash settlement with no written agreement.' },
      { term: 'Liquidated damages', plain: 'Extra money an employer may owe when the violation was willful.', watchOut: 'Not asking about it because you did not know it existed.' },
      { term: 'Final paycheck', plain: 'The last payment owed when you leave.', watchOut: 'Being told you will be paid "when we get to it".' },
      { term: 'Contingency fee', plain: 'A lawyer paid out of the winnings, not upfront.', watchOut: 'A lawyer demanding a large retainer for a small unpaid-wage claim.' },
      { term: 'Statute of limitations', plain: 'How long you have to file. Often 2–3 years, less in some states.', watchOut: 'Waiting too long while hoping the job comes back.' },
    ],
    steps: [
      'Gather your evidence in one folder: hours, pay, messages, company name, manager names, coworker names.',
      'Write one page stating what you were owed, for what period, and why. Numbers, not adjectives.',
      'File free with your state labor office and/or the federal Wage and Hour Division. Ask about deadlines.',
      'If you are still employed, keep working while you file unless you are being retaliated against — document any retaliation separately.',
      'Ask a worker center, legal aid office or union for help if the amount is large or the employer is retaliating.',
      'Consider small claims court for smaller amounts with clear evidence.',
      'Never accept a verbal settlement. Get it in writing, with a payment date.',
    ],
    traps: [
      'Never filing because you assume your status disqualifies you. It does not — this is explicit federal policy.',
      'Believing the threat that your employer will call immigration on you. Retaliation is illegal, and using that threat is itself a violation.',
      'Letting deadlines run out. Wage claims have a filing window.',
      'Quitting without collecting evidence first, then having nothing.',
      'Accepting cash under the table to settle for far less than owed, with no written agreement.',
      'Filing a complaint but continuing to work off the clock because nothing changed. Document each new violation separately.',
      'Paying a "labor consultant" a fee to file a free complaint.',
    ],
    questionsToAsk: [
      'What is the filing deadline for my claim in this state?',
      'Am I covered by state law, federal law, or both?',
      'What documents do you need from me, and can I file in my language?',
      'If I am fired after filing, what additional protections do I have and how do I report it?',
      'How long does the investigation usually take?',
    ],
    officialLinks: [
      { name: 'DOL — File a complaint with the Wage and Hour Division', url: 'https://www.dol.gov/agencies/whd/contact/complaints' },
      { name: 'DOL — State labor office directory', url: 'https://www.dol.gov/agencies/whd/state/contacts' },
      { name: 'DOL — Retaliation protections', url: 'https://www.dol.gov/agencies/whd/retaliation' },
      { name: 'USA.gov — Small claims court', url: 'https://www.usa.gov/small-claims-court' },
      { name: 'USA.gov — Legal aid', url: 'https://www.usa.gov/legal-aid' },
    ],
    relatedScamIds: ['visa-job-scam', 'unpaid-training', 'consultant-fee'],
  },

  {
    id: 'topic-unemployment-benefits',
    slug: 'unemployment-benefits',
    title: 'Losing a job: unemployment benefits, and what they are not',
    category: 'work',
    oneLiner:
      'Unemployment insurance is a state-run program that partially replaces wages for people who lose a job through no fault of their own — it is funded by employer taxes, not a welfare program.',
    whyItMatters:
      'Two things ruin this for immigrants: not knowing that a work-authorized immigrant may qualify, and fear that claiming will hurt an immigration case. There is also a big eligibility trap — being unable to work legally means you cannot meet the "able and available" requirement, so the timing of your work permit matters enormously.',
    keywords: [
      'unemployment', 'unemployment benefits', 'lost my job', 'fired', 'laid off',
      'ui', 'weekly claim', 'work search', 'denied unemployment', 'appeal',
      'severance', 'jobless', 'immigrant unemployment', 'dol unemployment',
    ],
    explain: [
      'Unemployment insurance is a partnership: you apply to your state\'s unemployment agency, and eligibility depends on how much you earned in a recent base period, why you lost the job, and whether you are able and available to work. Quitting without good cause or being fired for misconduct usually disqualifies you; a layoff, a reduction in hours, or a firing that broke the employer\'s own rules usually does not.',
      'For immigrants the critical phrase is "able and available to work." You must be authorized to work when you claim and while you receive benefits. If your work permit expires mid-claim, you may become ineligible until you have new authorization. That is one more reason the EAD renewal timing covered elsewhere in this library is so expensive to get wrong.',
      'The other thing to know: unemployment insurance is not a means-tested public benefit. It is insurance paid for by employer taxes, and it is generally not the kind of benefit weighed in a public charge determination. That said, the public charge standard changed in September 2026 and is being applied differently, so if you have an immigration case pending and you are unsure, ask a legal aid organization or licensed attorney before you decide. Do not let a forum post decide it for you.',
      'Apply quickly. Most states impose a waiting week before benefits start and require you to file weekly certifications, and delays in applying can cost you weeks of benefits that are not paid retroactively. If you are denied, appeal — a large share of denials are reversed on appeal, and the appeal process is designed to be used without a lawyer.',
    ],
    facts: [
      {
        id: 'f-ui-employer-funded',
        claim: 'Unemployment insurance is funded through employer payroll taxes, and eligibility is based on earnings history and the reason for job separation, not on household income.',
        asOf: '2026-09',
        source: { name: 'US Department of Labor — Unemployment Insurance', url: 'https://www.dol.gov/general/topic/unemployment-insurance' },
        volatility: 'annual',
      },
      {
        id: 'f-ui-state',
        claim: 'Unemployment insurance is administered by states, with each state setting benefit amounts, base-period earnings requirements and duration.',
        asOf: '2026-09',
        source: { name: 'DOL — State unemployment insurance agencies', url: 'https://www.dol.gov/general/topic/unemployment-insurance' },
        volatility: 'annual',
      },
      {
        id: 'f-ui-work-authorization',
        claim: 'Claimants must generally be able to work, available for work, and authorized to work in the US in order to receive unemployment benefits.',
        detail:
          'If your work authorization lapses while you are claiming benefits, report it — most states have rules for this, and an inaccurate claim creates a much bigger problem than a benefit interruption.',
        asOf: '2026-09',
        source: { name: 'US Department of Labor — Unemployment Insurance eligibility', url: 'https://www.dol.gov/general/topic/unemployment-insurance' },
        volatility: 'annual',
      },
      {
        id: 'f-public-charge-sep-2026',
        claim: 'DHS published a final rule on July 20, 2026 rescinding the 2022 public charge regulation, effective September 18, 2026, returning officers to a broader discretionary standard under which some non-cash benefits can be weighed in certain applications.',
        detail:
          'Public charge does not apply to everyone — refugees, asylees, U and T visa applicants, VAWA self-petitioners, TPS applicants, most green card renewals and naturalization are generally outside it. Because this changed days ago and affects decisions about benefits, get advice specific to your case before you choose.',
        asOf: '2026-07-20',
        source: { name: 'USCIS — Public Charge', url: 'https://www.uscis.gov/green-card/green-card-processes-and-procedures/public-charge' },
        volatility: 'volatile',
        alsoCheck: [
          { name: 'Federal Register — public charge final rule documents', url: 'https://www.federalregister.gov/' },
        ],
      },
      {
        id: 'f-ui-appeal',
        claim: 'Denied unemployment claims can be appealed through a state hearing process, and many states allow decisions to be challenged without a lawyer.',
        asOf: '2026-09',
        source: { name: 'DOL — Unemployment insurance appeals information', url: 'https://www.dol.gov/general/topic/unemployment-insurance' },
        volatility: 'annual',
      },
      {
        id: 'f-severance',
        claim: 'Severance pay and final wages are separate from unemployment benefits, and severance can affect the timing or amount of benefits in some states.',
        asOf: '2026-09',
        source: { name: 'DOL — Unemployment insurance basics', url: 'https://www.dol.gov/general/topic/unemployment-insurance' },
        volatility: 'annual',
      },
    ],
    jargon: [
      { term: 'Base period', plain: 'The months of earnings the state looks at to decide your benefit amount.', watchOut: 'Newly arrived workers whose earnings fall outside the base period and get nothing.' },
      { term: 'Weekly certification', plain: 'The weekly report that you are still unemployed, looking for work, and available.', watchOut: 'Missing one and losing that week of benefits permanently.' },
      { term: 'Work search requirement', plain: 'Proof you are applying for jobs.', watchOut: 'Not keeping a list of applications, then being denied or overpaid.' },
      { term: 'Overpayment', plain: 'Benefits you were not entitled to and must repay.', watchOut: 'Working while claiming and not reporting it.' },
      { term: 'Appeal / hearing', plain: 'Your chance to challenge a denial in front of a referee.', watchOut: 'Not appealing within the deadline. Most denials are final if you do not appeal.' },
      { term: 'Separation reason', plain: 'Why the job ended. Layoff, quit or fired for cause.', watchOut: 'Signing a resignation letter when you were effectively laid off, which can cost you eligibility.' },
    ],
    steps: [
      'File the claim with your state unemployment agency the week you lose the job — not weeks later, because benefits are usually not retroactive.',
      'Have ready: your employment history, the reason for separation, your work authorization document, and your bank details.',
      'Complete every weekly certification on time, and keep a written log of every job application.',
      'If you are denied, appeal within the deadline and appear at the hearing. Ask for an interpreter if you need one.',
      'Check your work permit expiry date. Report any change in work authorization to the agency immediately.',
      'If you have an immigration case pending, get advice on public charge questions from legal aid before deciding how to respond to any benefit question.',
      'If benefits are delayed, contact your state\'s unemployment office and, if unresolved, your state legislator\'s constituent services office — they can push agencies.',
    ],
    traps: [
      'Not applying because you assume immigrants cannot get unemployment. Work-authorized claimants often can.',
      'Working a cash job while collecting benefits. That is fraud, and it carries real penalties.',
      'Missing weekly certifications and losing weeks of benefits permanently.',
      'Resigning to "help" an employer when you were actually being let go, and losing eligibility.',
      'Ignoring a denial letter instead of appealing.',
      'Not reporting a lapse in work authorization while claiming benefits.',
      'Letting strangers on social media decide whether to claim, instead of a legal aid organization and the agency itself.',
    ],
    questionsToAsk: [
      'Do my earnings in the base period qualify me for benefits in this state?',
      'What documentation do you need to prove my work authorization?',
      'What happens to my claim if my work permit expires during the benefit period?',
      'How do I appeal, and what is the deadline?',
      'Do I need to report severance pay, and how does it affect my claim?',
    ],
    officialLinks: [
      { name: 'DOL — Unemployment insurance', url: 'https://www.dol.gov/general/topic/unemployment-insurance' },
      { name: 'DOL — State unemployment agencies list', url: 'https://www.dol.gov/general/topic/unemployment-insurance' },
      { name: 'USCIS — Public Charge', url: 'https://www.uscis.gov/green-card/green-card-processes-and-procedures/public-charge' },
      { name: 'USA.gov — Legal aid', url: 'https://www.usa.gov/legal-aid' },
    ],
    relatedScamIds: ['visa-job-scam', 'benefit-overpayment', 'consultant-fee'],
  },

  {
    id: 'topic-worker-injury',
    slug: 'injured-at-work',
    title: 'Injured at work: workers\' compensation and your options',
    category: 'work',
    oneLiner:
      'Workers\' compensation is an insurance system that pays medical costs and part of lost wages for work injuries, and it generally does not depend on who was at fault or on your immigration status.',
    whyItMatters:
      'Immigrant workers are overrepresented in the most dangerous jobs and least likely to report injuries — often because of a threat that reporting will lead to immigration consequences, or because they are paid off the books. Untreated injuries become permanent disabilities, and those are unfixable.',
    keywords: [
      'injured at work', 'workers comp', 'work accident', 'osha', 'safety',
      'hurt on the job', 'medical care', 'lost wages', 'safety complaint',
      'retaliation injury', 'employee rights injury', 'construction injury',
    ],
    explain: [
      'Workers\' compensation is a trade-off built into US law: employers provide no-fault insurance covering medical care and partial wage replacement for injuries that happen at work, and in exchange employees generally cannot sue the employer directly. The practical consequence is that you rarely have to prove anyone was careless — you have to report the injury promptly, in the right way, to the right people.',
      'That "promptly" is the part that fails. Every state sets deadlines for reporting injuries and filing claims, and missing them can end the case permanently. So the moment something happens: tell a supervisor, ask for first aid or medical care, and get the visit documented. Then write down the date, time, what you were doing, who was present, and what happened — that same day, while it is fresh. If your employer discourages reporting or tells you to use your own health insurance, that is a warning sign, not an instruction.',
      'Two more protections matter. First, OSHA: employers must provide a safe workplace and must not retaliate against workers for reporting hazards or injuries. You can file a safety complaint with OSHA, and you can request an inspection. Second, if you are paid off the books, you may be told there is no coverage for you. That is often false — coverage is usually tied to the employer\'s policy, and workers\' compensation boards decide whether you were an employee. Ask the board rather than accepting the employer\'s answer.',
      'If the injury is serious, or if you are being pressured to settle quickly for a small amount, talk to a workers\' compensation attorney. These cases are usually handled on contingency, meaning no upfront fee, and the percentage is regulated in many states. A rushed settlement can sign away your right to future medical care for a problem that lasts the rest of your life.',
    ],
    facts: [
      {
        id: 'f-workers-comp-basics',
        claim: 'Workers\' compensation is a state-based insurance system that generally covers work-related injury medical costs and a portion of lost wages, regardless of fault.',
        asOf: '2026-09',
        source: { name: 'US Department of Labor — Workers\' compensation', url: 'https://www.dol.gov/general/topic/workcomp' },
        volatility: 'annual',
      },
      {
        id: 'f-osha-rights',
        claim: 'Under OSHA, employers must provide a workplace free of known serious hazards, and workers have the right to report injuries and hazards without retaliation.',
        asOf: '2026-09',
        source: { name: 'OSHA — Worker rights and protections', url: 'https://www.osha.gov/workers' },
        volatility: 'stable',
      },
      {
        id: 'f-osha-complaint',
        claim: 'Workers can file an OSHA complaint and request an inspection, and OSHA protects workers who report hazards or injuries from retaliation.',
        asOf: '2026-09',
        source: { name: 'OSHA — How to file a complaint', url: 'https://www.osha.gov/workers/file-complaint' },
        volatility: 'stable',
      },
      {
        id: 'f-osha-language',
        claim: 'OSHA requires training and information that workers can understand, including in a language they speak, and provides free compliance assistance in multiple languages.',
        asOf: '2026-09',
        source: { name: 'OSHA — Training requirements and language access', url: 'https://www.osha.gov/training' },
        volatility: 'stable',
      },
      {
        id: 'f-injury-reporting-deadline',
        claim: 'States set deadlines for reporting work injuries and filing workers\' compensation claims, and failing to report promptly can bar the claim.',
        detail:
          'Ask your state workers\' compensation board what the deadlines are in writing, and record the date of injury and every treatment in one place.',
        asOf: '2026-09',
        source: { name: 'US Department of Labor — State workers\' compensation programs', url: 'https://www.dol.gov/agencies/owcp' },
        volatility: 'annual',
      },
      {
        id: 'f-day-labor-violations',
        claim: 'Day laborers and other contingent workers are entitled to the same wage, safety and anti-retaliation protections as directly hired employees.',
        asOf: '2026-09',
        source: { name: 'US Department of Labor — Day labor and contingent workers', url: 'https://www.dol.gov/agencies/whd/immigration' },
        volatility: 'stable',
      },
    ],
    jargon: [
      { term: 'Workers\' compensation', plain: 'Employer-funded insurance covering work injuries.', watchOut: 'An employer who says you are not covered because you are a contractor in name only.' },
      { term: 'No-fault system', plain: 'You usually do not have to prove the employer was careless.', watchOut: 'Being told you cannot claim because "it was your fault".' },
      { term: 'Lost wage replacement', plain: 'Partial pay while you cannot work.', watchOut: 'Accepting cash from the employer instead, with no record.' },
      { term: 'OSHA', plain: 'The federal workplace safety agency. You can file a free complaint.', watchOut: 'Employers hiding hazards or threatening workers who report them.' },
      { term: 'Retaliation', plain: 'Being punished for reporting an injury or hazard.', watchOut: 'Getting fired the week after you file a complaint.' },
      { term: 'Settlement', plain: 'Money that ends your claim.', watchOut: 'Signing a settlement that waives future medical care for an ongoing injury.' },
      { term: 'IME', plain: 'Independent Medical Examination — a doctor chosen by the insurer.', watchOut: 'Assuming the "independent" doctor is neutral. Have your own records.' },
    ],
    steps: [
      'Report the injury to a supervisor immediately, and ask for medical care the same day. Say clearly: "This happened at work."',
      'Get medical attention from a provider that takes workers\' compensation. Keep every document, including imaging and prescriptions.',
      'Write down the incident, the date, the location, witnesses and what you were doing. Do it that day.',
      'File the workers\' compensation claim with your state board, and confirm the reporting deadline in writing.',
      'Keep a record of lost workdays and any partial work you are given.',
      'Never sign a settlement or a "release" without having it reviewed by a workers\' compensation attorney or a legal aid clinic. Ask about how it affects future medical care.',
      'If you are threatened with immigration consequences or fired for reporting, report that retaliation to OSHA and the wage and hour authorities separately.',
    ],
    traps: [
      'Not reporting the injury because you need the money or fear losing the job. Untreated injuries cost far more.',
      'Being told to use your own health insurance or to pay for the visit yourself.',
      'Accepting a few hundred dollars in cash in exchange for not reporting, then discovering you need surgery.',
      'Missing the state deadline to report, which can end the claim regardless of how serious the injury is.',
      'Signing a settlement in a language you cannot read without an interpreter and your own review.',
      'Believing off-the-books workers have no rights. Coverage decisions are made by the board, not by the employer.',
      'Going back to the same dangerous task because the employer asked, then being injured more seriously.',
      'Not documenting symptoms that appear days later — repetitive strain and back injuries often develop gradually.',
    ],
    questionsToAsk: [
      'Is this provider covered by workers\' compensation for my employer?',
      'What is my state\'s deadline to report an injury and to file a claim?',
      'Am I an employee for workers\' compensation purposes, and who decides that?',
      'Can I get an interpreter for my medical visits and for the claim paperwork?',
      'What happens to my medical coverage if I sign this settlement?',
    ],
    officialLinks: [
      { name: 'OSHA — Worker rights', url: 'https://www.osha.gov/workers' },
      { name: 'OSHA — File a complaint', url: 'https://www.osha.gov/workers/file-complaint' },
      { name: 'DOL — Workers\' compensation', url: 'https://www.dol.gov/general/topic/workcomp' },
      { name: 'USA.gov — Legal aid', url: 'https://www.usa.gov/legal-aid' },
    ],
    relatedScamIds: ['unpaid-training', 'visa-job-scam', 'insurance-scam'],
  },
]
