import type { Answer, AnswerBlock } from './types'
import { buildGrounding, DISCLAIMER, answerOffline } from './engine'

/**
 * Pluggable LLM layer.
 *
 * The product works with no API key at all (the grounded offline engine). If a
 * key is present in the environment, answers are generated by the model — but
 * only from the retrieved facts, with the dates and sources attached. If the
 * model call fails or returns nothing usable, we fall back to the offline
 * answer so the user never sees an empty screen.
 */

export type ProviderInfo = {
  id: 'openai' | 'anthropic' | 'openrouter' | 'groq' | 'ollama' | 'none'
  label: string
  model: string
  configured: boolean
}

export function detectProvider(): ProviderInfo {
  const forced = process.env.SETTLESAFE_LLM?.toLowerCase()
  if (forced === 'off' || forced === 'none') {
    return { id: 'none', label: 'Grounded offline engine', model: 'curated library', configured: false }
  }
  if (process.env.OPENAI_API_KEY) {
    return {
      id: 'openai',
      label: 'OpenAI',
      model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
      configured: true,
    }
  }
  if (process.env.ANTHROPIC_API_KEY) {
    return {
      id: 'anthropic',
      label: 'Anthropic',
      model: process.env.ANTHROPIC_MODEL || 'claude-3-5-haiku-latest',
      configured: true,
    }
  }
  if (process.env.OPENROUTER_API_KEY) {
    return {
      id: 'openrouter',
      label: 'OpenRouter',
      model: process.env.OPENROUTER_MODEL || 'openai/gpt-4o-mini',
      configured: true,
    }
  }
  if (process.env.GROQ_API_KEY) {
    return {
      id: 'groq',
      label: 'Groq',
      model: process.env.GROQ_MODEL || 'llama-3.3-70b-versatile',
      configured: true,
    }
  }
  if (process.env.OLLAMA_BASE_URL) {
    return {
      id: 'ollama',
      label: 'Ollama (local)',
      model: process.env.OLLAMA_MODEL || 'llama3.1',
      configured: true,
    }
  }
  return { id: 'none', label: 'Grounded offline engine', model: 'curated library', configured: false }
}

const SYSTEM_PROMPT = `You are SettleSafe, a plain-language guide to living in the United States for people who recently immigrated. Your users may not speak fluent English, do not know US systems, and have been targeted by scams.

HARD RULES:
1. Use ONLY the facts in the CONTEXT provided. Do not add rules, dollar amounts, deadlines, fees, or legal claims from your own memory. If the context does not cover something, say so plainly and tell the user where to check.
2. Every factual claim must carry its date and source in the form "(verified 2026-01, USCIS)". The context gives you asOf dates and source names — use them exactly.
3. Never give legal, tax or immigration advice about a specific person's case. Say what the general rule is, then tell them to confirm with a licensed attorney, legal aid, or a VITA tax clinic.
4. Never invent state-specific numbers, dollar amounts or deadlines. If the question is state-specific and the context has no verified state facts, say so and give the official agency link.
5. Write at a level a person with intermediate English can follow: short sentences, active voice, no legal jargon. When you must use a jargon word, define it in the same sentence.
6. Never recommend paying money to an individual, gift cards, cryptocurrency, wire transfers, or payment apps. Name those as fraud signals when relevant.
7. Never ask for or accept personal information (SSN, A-number, account numbers) - you cannot receive it.
8. Be calm and specific. Do not moralize, do not say "I understand your concern", do not pad. Respect the reader's intelligence and their time.

OUTPUT FORMAT: return ONLY valid JSON, no markdown fences, matching:
{"confidence":"high"|"medium"|"low","blocks":[{"kind":"answer"|"means"|"steps"|"watch"|"timeline"|"questions"|"unknown"|"warning"|"scam","heading":"short heading","body":"optional paragraph","bullets":["optional","bullets"],"emphasis":"normal"|"danger"|"done"}]}
Order the blocks as: short answer -> what the words mean -> what to do (steps) -> where people lose money (danger) -> timeline if relevant -> questions to ask -> what this cannot do. Keep it tight: 5-7 blocks maximum, at most 6 bullets per block.`

type ChatMessage = { role: 'system' | 'user'; content: string }

async function callOpenAiCompatible(
  baseUrl: string,
  apiKey: string,
  model: string,
  messages: ChatMessage[]
): Promise<string> {
  const res = await fetch(`${baseUrl.replace(/\/$/, '')}/chat/completions`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', authorization: `Bearer ${apiKey}` },
    body: JSON.stringify({ model, messages, temperature: 0.2, max_tokens: 1400 }),
  })
  if (!res.ok) throw new Error(`LLM ${res.status}: ${(await res.text()).slice(0, 300)}`)
  const json = (await res.json()) as { choices?: { message?: { content?: string } }[] }
  return json.choices?.[0]?.message?.content ?? ''
}

async function callAnthropic(apiKey: string, model: string, system: string, user: string): Promise<string> {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model,
      max_tokens: 1400,
      temperature: 0.2,
      system,
      messages: [{ role: 'user', content: user }],
    }),
  })
  if (!res.ok) throw new Error(`LLM ${res.status}: ${(await res.text()).slice(0, 300)}`)
  const json = (await res.json()) as { content?: { type: string; text?: string }[] }
  return json.content?.map((c) => c.text ?? '').join('') ?? ''
}

function parseBlocks(raw: string): { confidence: Answer['confidence']; blocks: AnswerBlock[] } | undefined {
  const cleaned = raw.replace(/^```(?:json)?/m, '').replace(/```\s*$/m, '').trim()
  const start = cleaned.indexOf('{')
  const end = cleaned.lastIndexOf('}')
  if (start === -1 || end === -1) return undefined
  try {
    const parsed = JSON.parse(cleaned.slice(start, end + 1)) as {
      confidence?: string
      blocks?: unknown[]
    }
    if (!Array.isArray(parsed.blocks) || parsed.blocks.length === 0) return undefined
    const allowed = new Set([
      'answer', 'means', 'steps', 'watch', 'timeline', 'questions', 'unknown', 'warning', 'scam',
    ])
    const blocks: AnswerBlock[] = parsed.blocks
      .map((b) => b as Record<string, unknown>)
      .filter((b) => typeof b?.heading === 'string' && allowed.has(String(b?.kind)))
      .map((b) => ({
        kind: String(b.kind) as AnswerBlock['kind'],
        heading: String(b.heading),
        body: typeof b.body === 'string' ? b.body : undefined,
        bullets: Array.isArray(b.bullets) ? (b.bullets as unknown[]).map(String).slice(0, 8) : undefined,
        emphasis: b.emphasis === 'danger' || b.emphasis === 'done' ? (b.emphasis as 'danger' | 'done') : 'normal',
      }))
    if (!blocks.length) return undefined
    const confidence =
      parsed.confidence === 'high' || parsed.confidence === 'medium' || parsed.confidence === 'low'
        ? (parsed.confidence as Answer['confidence'])
        : 'medium'
    return { confidence, blocks }
  } catch {
    return undefined
  }
}

export async function answerWithLlm(
  question: string,
  opts: { stateCode?: string } = {}
): Promise<Answer> {
  const provider = detectProvider()
  const fallback = answerOffline(question, opts)

  if (provider.id === 'none' || !provider.configured) return fallback

  const grounding = buildGrounding(question, 3)
  const user = [
    `QUESTION FROM USER:\n${question}`,
    opts.stateCode ? `USER'S STATE: ${opts.stateCode} (only use state facts if they appear in the context)` : '',
    `USER PROFILE: an immigrant in the United States, possibly reading in their second language, possibly under financial pressure.`,
    `\nCONTEXT (the only material you may use):\n${grounding.context}`,
    `\nRemember: if the context does not contain the answer, say "our library does not cover this" and give a search plan with official links. Return only JSON.`,
  ]
    .filter(Boolean)
    .join('\n\n')

  try {
    let raw = ''
    if (provider.id === 'anthropic') {
      raw = await callAnthropic(process.env.ANTHROPIC_API_KEY!, provider.model, SYSTEM_PROMPT, user)
    } else if (provider.id === 'openai') {
      raw = await callOpenAiCompatible(
        process.env.OPENAI_BASE_URL || 'https://api.openai.com/v1',
        process.env.OPENAI_API_KEY!,
        provider.model,
        [{ role: 'system', content: SYSTEM_PROMPT }, { role: 'user', content: user }]
      )
    } else if (provider.id === 'openrouter') {
      raw = await callOpenAiCompatible(
        'https://openrouter.ai/api/v1',
        process.env.OPENROUTER_API_KEY!,
        provider.model,
        [{ role: 'system', content: SYSTEM_PROMPT }, { role: 'user', content: user }]
      )
    } else if (provider.id === 'groq') {
      raw = await callOpenAiCompatible(
        'https://api.groq.com/openai/v1',
        process.env.GROQ_API_KEY!,
        provider.model,
        [{ role: 'system', content: SYSTEM_PROMPT }, { role: 'user', content: user }]
      )
    } else if (provider.id === 'ollama') {
      raw = await callOpenAiCompatible(
        `${process.env.OLLAMA_BASE_URL}`,
        'ollama',
        provider.model,
        [{ role: 'system', content: SYSTEM_PROMPT }, { role: 'user', content: user }]
      )
    }

    const parsed = parseBlocks(raw)
    if (!parsed) return { ...fallback, engine: 'llm+grounded-fallback' }

    return {
      question,
      engine: 'llm',
      model: `${provider.label} · ${provider.model}`,
      confidence: parsed.confidence,
      usedTopicIds: grounding.usedTopicIds,
      usedScamIds: grounding.usedScamIds,
      blocks: parsed.blocks,
      disclaimer: DISCLAIMER,
      isFallbackPlan: !grounding.hasGrounding,
    }
  } catch (error) {
    console.error('[settlesafe] LLM call failed, using grounded engine', error)
    return { ...fallback, engine: 'llm+grounded-fallback' }
  }
}
